// ─────────────────────────────────────────────────────────
//  Static data — no database needed
//  When you're ready to connect Supabase, this file gets
//  replaced by src/lib/db.ts pulling from live tables.
// ─────────────────────────────────────────────────────────

export const VERSES = [
  { id: "1", sanskrit: "सर्वं खल्विदं ब्रह्म", transliteration: "Sarvaṃ Khalvidaṃ Brahma", translation_en: "All this is verily Brahman — not some of it, not most of it. All of it. The ground beneath apparent difference.", source: "Chandogya Upanishad", chapter: "3.14.1", category: "advaita", is_mahavakya: false, tags: ["brahman","non-duality"], commentary: "" },
  { id: "2", sanskrit: "अहं ब्रह्मास्मि", transliteration: "Ahaṃ Brahmāsmi", translation_en: "I am Brahman. Not as arrogance — as the recognition that there is no boundary between the knower and the known.", source: "Brihadaranyaka Upanishad", chapter: "1.4.10", category: "advaita", is_mahavakya: true, tags: ["mahavakya","brahman","atman"], commentary: "One of the four Mahavakyas — the great sayings of the Upanishads. Spoken in the Brihadaranyaka, it is the direct assertion of non-difference between the individual self and Brahman." },
  { id: "3", sanskrit: "एकमेवाद्वितीयम्", transliteration: "Ekam Evādvitīyam", translation_en: "One only, without a second. Not one among many — one in which there is no other. The most radical statement in human thought.", source: "Chandogya Upanishad", chapter: "6.2.1", category: "advaita", is_mahavakya: false, tags: ["brahman","oneness","non-duality"], commentary: "" },
  { id: "4", sanskrit: "नेति नेति", transliteration: "Neti Neti", translation_en: "Not this, not this. Arriving at Brahman by negating everything that Brahman is not — until only the negator remains.", source: "Brihadaranyaka Upanishad", chapter: "2.3.6", category: "advaita", is_mahavakya: false, tags: ["inquiry","brahman","method"], commentary: "The method of Neti Neti — not this, not this — is the systematic negation of everything that can be objectified. What remains when all objects are negated is the subject itself: pure awareness." },
  { id: "5", sanskrit: "प्रज्ञानं ब्रह्म", transliteration: "Prajñānaṃ Brahma", translation_en: "Consciousness is Brahman. Pure awareness is the ground of all existence.", source: "Aitareya Upanishad", chapter: "3.3", category: "advaita", is_mahavakya: true, tags: ["mahavakya","consciousness","brahman"], commentary: "The Mahavakya of the Rigveda. It points directly at consciousness itself as the ultimate reality — not an object of consciousness, but consciousness as such." },
  { id: "6", sanskrit: "तत्त्वमसि", transliteration: "Tat Tvam Asi", translation_en: "Thou Art That. The individual self is not different from the ultimate reality.", source: "Chandogya Upanishad", chapter: "6.8.7", category: "advaita", is_mahavakya: true, tags: ["mahavakya","atman","brahman"], commentary: "The Mahavakya of the Samaveda, and the teaching for which this platform is named. Uddalaka gave this teaching to his son Shvetaketu nine times, through nine analogies, until the recognition arose." },
  { id: "7", sanskrit: "अयमात्मा ब्रह्म", transliteration: "Ayam Ātmā Brahma", translation_en: "This Self is Brahman. Look within; there lies the infinite.", source: "Mandukya Upanishad", chapter: "1.2", category: "advaita", is_mahavakya: true, tags: ["mahavakya","atman","brahman"], commentary: "The Mahavakya of the Atharvaveda. The Mandukya Upanishad is the shortest — twelve verses — and this is its central declaration." },
  { id: "8", sanskrit: "ॐ पूर्णमदः पूर्णमिदम्", transliteration: "Oṃ Pūrṇamadaḥ Pūrṇamidam", translation_en: "That is whole. This is whole. From wholeness emerges wholeness. Even after wholeness is taken from wholeness, wholeness remains.", source: "Isha Upanishad", chapter: "Invocation", category: "shruti", is_mahavakya: false, tags: ["purna","wholeness","brahman"], commentary: "The opening invocation of the Isha Upanishad. It describes the nature of Brahman as Purna — complete, whole, lacking nothing. The mathematics of infinity: infinity minus infinity is still infinity." },
];

export const UPANISHADS = [
  { id: "1", slug: "mandukya", name_sanskrit: "माण्डूक्य", name_iast: "Māṇḍūkya Upaniṣad", name_en: "Mandukya Upanishad", veda: "Atharvaveda", verse_count: 12, summary: "The shortest and most complete Upanishad. Twelve verses on Om and the four states of consciousness — waking, dream, deep sleep, and Turiya — the witnessing awareness behind all three.", key_teaching: "Ayam Atma Brahma — This Self is Brahman" },
  { id: "2", slug: "kena", name_sanskrit: "केन", name_iast: "Kena Upaniṣad", name_en: "Kena Upanishad", veda: "Samaveda", verse_count: 35, summary: "Explores the nature of Brahman as that which cannot be known by the ordinary mind. The eye of the eye, the mind of the mind, the ear of the ear.", key_teaching: "That which is not thought by the mind, but by which the mind thinks — that alone is Brahman." },
  { id: "3", slug: "isha", name_sanskrit: "ईश", name_iast: "Īśa Upaniṣad", name_en: "Isha Upanishad", veda: "Yajurveda", verse_count: 18, summary: "The shortest in the Yajurveda. Reconciles knowledge and action, renunciation and engagement. Everything is enveloped by the Lord — renounce and enjoy.", key_teaching: "Tena tyaktena bhuñjīthāḥ — By renouncing, enjoy." },
  { id: "4", slug: "katha", name_sanskrit: "कठ", name_iast: "Kaṭha Upaniṣad", name_en: "Katha Upanishad", veda: "Yajurveda", verse_count: 119, summary: "Nachiketa, a young boy, asks Yama — the lord of death — about what lies beyond death. Yama's answer is the complete teaching on the immortal Self.", key_teaching: "The Self is not born, nor does it die. It did not come from anywhere; nothing came from it." },
  { id: "5", slug: "mundaka", name_sanskrit: "मुण्डक", name_iast: "Muṇḍaka Upaniṣad", name_en: "Mundaka Upanishad", veda: "Atharvaveda", verse_count: 64, summary: "Distinguishes between the higher knowledge of Brahman and lower knowledge of the world. Uses the beautiful image of two birds on the same tree.", key_teaching: "Two birds, inseparable companions, dwell on the same tree. One eats the fruits; the other only watches." },
  { id: "6", slug: "chandogya", name_sanskrit: "छान्दोग्य", name_iast: "Chāndogya Upaniṣad", name_en: "Chandogya Upanishad", veda: "Samaveda", verse_count: 628, summary: "The longest and most storied Upanishad. Contains Tat Tvam Asi — given nine times by a father to his son through nine different analogies of salt in water, the fig seed, and more.", key_teaching: "Tat Tvam Asi — Thou Art That" },
];

export const TEACHERS = [
  { id: "1", slug: "adi-shankaracharya", name: "Adi Shankaracharya", name_sanskrit: "आदि शङ्कराचार्य", era: "8th Century CE", birth_year: 788, death_year: 820, tradition: "Advaita Vedanta", key_works: ["Brahmasutra Bhashya", "Vivekachudamani", "Upadeshasahasri", "Bhagavad Gita Bhashya", "Aparokshanubhuti"], biography: "Born in Kaladi, Kerala, Shankaracharya consolidated and systematised the doctrine of Advaita Vedanta at a time when the philosophical landscape of India was fragmented. He walked the length of India on foot, engaging scholars in debate, establishing four Mathas at the four directions, and writing extensive commentaries on the Prasthanatrayi — the Upanishads, Brahma Sutras, and Bhagavad Gita. He accomplished all of this before the age of 32.", quote: "Brahma satyam, jagan mithya, jivo brahmaiva naparah — Brahman alone is real. The world is appearance. The individual self is none other than Brahman." },
  { id: "2", slug: "ramana-maharshi", name: "Ramana Maharshi", name_sanskrit: "रमण महर्षि", era: "1879 – 1950", birth_year: 1879, death_year: 1950, tradition: "Advaita Vedanta", key_works: ["Who am I?", "Forty Verses on Reality", "Upadesa Saram", "Ulladu Narpadu"], biography: "At age 16, Venkataraman underwent a spontaneous experience of death and Self-realisation in Madurai with no prior spiritual training. He walked to Arunachala and never left. He taught primarily through silence — visitors came with elaborate questions and left with their doubts dissolved. His method of self-enquiry through the question 'Who am I?' is regarded as one of the most direct paths to liberation.", quote: "The degree of freedom from unwanted thoughts and the degree of concentration on a single thought — these are the measure of spiritual progress." },
  { id: "3", slug: "nisargadatta-maharaj", name: "Nisargadatta Maharaj", name_sanskrit: "निसर्गदत्त महाराज", era: "1897 – 1981", birth_year: 1897, death_year: 1981, tradition: "Advaita Vedanta", key_works: ["I Am That", "Prior to Consciousness", "Seeds of Consciousness", "The Experience of Nothingness"], biography: "A humble Mumbai bidi-maker who attained Self-realisation through the instruction of his guru Siddharameshwar Maharaj. His dialogues, compiled in 'I Am That', are considered among the most direct and uncompromising expositions of Advaita in the modern era. He spoke from direct experience, not scholarship, and had no patience for spiritual performance.", quote: "Love says I am everything. Wisdom says I am nothing. Between the two, my life flows." },
];

export const TEMPLES = [
  { id: "1", slug: "brihadeeswarar-temple", name: "Brihadeeswarar Temple", name_local: "பெரிய கோயில்", location: "Thanjavur", state: "Tamil Nadu", dynasty: "Chola", century_built: "11th century CE", architecture_style: "Dravidian", presiding_deity: "Shiva (Brihadeeswara)", description: "Built by Raja Raja Chola I, this UNESCO World Heritage Site towers 66 metres with a vimana made of a single 80-tonne granite capstone — raised without modern machinery. The shadow of the shikhara never falls on the ground at noon.", significance: "The temple demonstrates the Chola understanding that the temple is a model of Mount Meru — the axis of the cosmos. The garbhagriha represents the cave of the heart. The entire structure is a three-dimensional mandala of the universe." },
  { id: "2", slug: "kailasa-temple-ellora", name: "Kailasa Temple", name_local: "कैलास मंदिर", location: "Ellora", state: "Maharashtra", dynasty: "Rashtrakuta", century_built: "8th century CE", architecture_style: "Rock-cut", presiding_deity: "Shiva (Kailashanatha)", description: "Carved from a single basalt cliff, the Kailasa Temple at Ellora is the largest monolithic structure in the world. An estimated 200,000 tonnes of rock were removed by hand over several decades. Not built — subtracted.", significance: "The temple is a three-dimensional mandala — a sacred diagram of the cosmos carved into the living rock of the earth itself. It was not constructed from the outside in, but revealed from the inside out — like the Self." },
  { id: "3", slug: "meenakshi-amman-temple", name: "Meenakshi Amman Temple", name_local: "மீனாக்ஷி அம்மன் கோவில்", location: "Madurai", state: "Tamil Nadu", dynasty: "Nayak", century_built: "17th century CE", architecture_style: "Dravidian", presiding_deity: "Meenakshi (Parvati)", description: "One of the largest temple complexes in India, with 14 gopurams covered in thousands of painted sculptures. The corridors encode the 64 sacred games of Shiva.", significance: "This temple encodes the entire cosmos in its plan. Walking through it is walking through a living scripture. The rituals performed here daily have continued without interruption for over a thousand years." },
  { id: "4", slug: "konark-sun-temple", name: "Konark Sun Temple", name_local: "कोणार्क", location: "Konark", state: "Odisha", dynasty: "Eastern Ganga", century_built: "13th century CE", architecture_style: "Kalinga", presiding_deity: "Surya (Sun God)", description: "Designed as a colossal chariot of the sun god, with 24 intricately carved wheels functioning as sundials. A masterpiece of Odishan architecture encoding the Vedic understanding of time.", significance: "The 24 wheels correspond to the 24 hours. The 8 spokes to the eight praharas of the day. The entire structure is a statement that time itself is sacred — that the movement of the sun is the movement of the divine." },
  { id: "5", slug: "virupaksha-temple-hampi", name: "Virupaksha Temple", name_local: "ವಿರೂಪಾಕ್ಷ ದೇವಾಲಯ", location: "Hampi", state: "Karnataka", dynasty: "Vijayanagara", century_built: "7th century CE", architecture_style: "Dravidian", presiding_deity: "Shiva (Virupaksha)", description: "One of the oldest functioning temples in India, continuously worshipped for over 1,300 years. At the centre of the magnificent Vijayanagara Empire ruins.", significance: "1300 years of unbroken worship. Empires rose and fell around it. The lamp inside has not gone out. This is what Dharma means in stone — not a belief but a continuity that outlasts all circumstance." },
];

export const CONCEPTS = [
  { id: "1", slug: "brahman", term_sanskrit: "ब्रह्मन्", term_iast: "Brahman", term_en: "Brahman", definition: "The ultimate, infinite, unchanging reality underlying all existence.", detailed_explanation: "In Advaita Vedanta, Brahman is the sole reality — infinite, eternal, and self-luminous consciousness. It is described as Sat-Chit-Ananda: pure being, pure consciousness, pure bliss. Everything that appears as the world is Brahman alone, like waves in the ocean of being. Brahman is not a God that exists somewhere — it is existence itself, knowing itself.", category: "advaita", related_concepts: ["atman", "maya", "advaita"] },
  { id: "2", slug: "atman", term_sanskrit: "आत्मन्", term_iast: "Ātman", term_en: "Atman", definition: "The individual Self, which Advaita holds to be identical with Brahman.", detailed_explanation: "Atman is the witness-consciousness within every being. Unlike the ego or mind, Atman is unborn, undying, and unchanging. The central teaching of Advaita is that the apparent individual self (jiva) is, in its deepest nature, none other than Brahman. The Atman is not something you have — it is what you are, prior to all thought and experience.", category: "advaita", related_concepts: ["brahman", "maya", "moksha"] },
  { id: "3", slug: "maya", term_sanskrit: "माया", term_iast: "Māyā", term_en: "Maya", definition: "The cosmic creative power that causes the appearance of multiplicity in the one Brahman.", detailed_explanation: "Maya is neither real nor unreal — it is the inexplicable power (shakti) of Brahman by which the infinite appears as the finite world. It operates through two functions: avarana (veiling of Brahman) and viksepa (projection of the world). Maya is often misunderstood as meaning the world is an illusion in the sense of being unreal. It means something more precise: the world is real as appearance but not real as an independent existence apart from Brahman.", category: "advaita", related_concepts: ["brahman", "viveka", "moksha"] },
  { id: "4", slug: "advaita", term_sanskrit: "अद्वैत", term_iast: "Advaita", term_en: "Non-duality", definition: "The philosophical position that reality is one, without a second.", detailed_explanation: "Advaita (a + dvaita = not two) is the conclusion of Vedantic inquiry: that Brahman, Atman, and the world are not three different things but one undivided reality. The diversity of appearances is due to Maya, not to any real difference in the substrate. This is not a belief to adopt but a recognition to arrive at through inquiry.", category: "advaita", related_concepts: ["brahman", "atman", "maya"] },
  { id: "5", slug: "moksha", term_sanskrit: "मोक्ष", term_iast: "Mokṣa", term_en: "Liberation", definition: "Freedom from the cycle of birth and death through Self-realisation.", detailed_explanation: "Moksha in Advaita is not a state to be achieved in the future but the recognition of what already is. It is the direct knowing that one has never been bound — that the Self is always free. This recognition dissolves the false identification with body and mind that constitutes bondage. You do not attain Moksha. You recognise that you were always free.", category: "advaita", related_concepts: ["atman", "brahman", "viveka"] },
  { id: "6", slug: "viveka", term_sanskrit: "विवेक", term_iast: "Viveka", term_en: "Discrimination", definition: "The faculty of discernment between the real and the unreal.", detailed_explanation: "Viveka is the first qualification for Vedantic inquiry. It is the capacity to clearly distinguish between what is eternal and what is transient, between consciousness itself and the objects that appear in it. Without viveka, the teaching cannot take root. With it, everything becomes a pointer toward the Self.", category: "advaita", related_concepts: ["vairagya", "moksha", "atman"] },
];

export const MATHAS = [
  { id: "1", slug: "sringeri", name: "Sringeri Sharada Peetham", location: "Sringeri", state: "Karnataka", direction: "south", veda: "Yajurveda", mahavakya: "Aham Brahmasmi", presiding_deity: "Sharadamba", founded_by: "Adi Shankaracharya", description: "The southern Matha, established on the banks of the Tunga river in Karnataka. Shankara is said to have watched a frog sheltered from the sun by the hood of a cobra — and chose this spot of natural harmony as his first foundation. It is the most prominent of the four and maintains the Yajurveda tradition." },
  { id: "2", slug: "jyotirmath", name: "Jyotirmath", location: "Joshimath", state: "Uttarakhand", direction: "north", veda: "Atharvaveda", mahavakya: "Ayam Atma Brahma", presiding_deity: "Narayana", founded_by: "Adi Shankaracharya", description: "The northern Matha in the Himalayas, near Badrinath. The northernmost seat, keeper of the Atharvaveda tradition. The mulberry tree under which Shankara is said to have meditated still stands at Joshimath." },
  { id: "3", slug: "govardhana", name: "Govardhana Peetham", location: "Puri", state: "Odisha", direction: "east", veda: "Rigveda", mahavakya: "Prajnanam Brahma", presiding_deity: "Vimala", founded_by: "Adi Shankaracharya", description: "The eastern Matha at the sacred city of Puri, home of Jagannatha. Keeper of the Rigveda — the oldest of the four Vedas — and of the Mahavakya Prajnanam Brahma: Consciousness is Brahman." },
  { id: "4", slug: "dwarka", name: "Dwarka Sharada Peetham", location: "Dwarka", state: "Gujarat", direction: "west", veda: "Samaveda", mahavakya: "Tat Tvam Asi", presiding_deity: "Siddheshwari", founded_by: "Adi Shankaracharya", description: "The western Matha at the sacred city of Dwarka on the coast of Gujarat. Keeper of the Samaveda and of Tat Tvam Asi — the teaching for which this entire platform is named." },
];

// Helper to get verse of the day based on day of year
export function getVerseOfTheDay() {
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000);
  return VERSES[dayOfYear % VERSES.length];
}

export function getMahavakyas() {
  return VERSES.filter(v => v.is_mahavakya);
}
