import type { Locale } from "@/i18n/config";
import commons from "../../../public/images/bhajans/commons.json";

// ─────────────────────────────────────────────────────────
//  Pictures for the bhajan groups.
//
//  Two sources, and the credit always says which:
//
//    Wikimedia Commons — generated by
//      scripts/wordpress/fetch-devata-images.mjs, which asks the API
//      for each file's real licence and author and refuses anything
//      non-free. The credits below are whatever Commons actually said,
//      not what anyone typed. Several are Raja Ravi Varma paintings,
//      long out of copyright: a card needs a picture that reads at
//      210px, and a dark temple carving does not. The first pass used
//      carvings and one of them turned out to be a photograph of a
//      signboard outside the temple.
//
//    The site's owner — four photographs of temple murtis he supplied.
//      Their original photographer and licence are not recorded, so
//      they carry no source link and the credit names him, exactly as
//      seed/stuti-images.ts already does for the Ganesha pages.
//
//  A group with no picture is a normal state, not a hole to be filled
//  with something approximate. Those groups get a drawn treatment
//  instead — see .bh-plate in styles/bhajans.css. Never illustrate a
//  devata with a picture of a different one.
// ─────────────────────────────────────────────────────────

export interface GroupImage {
  src: string;
  width: number;
  height: number;
  credit: string;
  /** Absent for a picture supplied without a recorded source. */
  sourceUrl?: string;
  /** Which part to keep when a frame crops it. */
  position?: string;
  alt: Record<Locale, string>;
}

const OWNER = "Supplied by the site owner";

/** Photographs the owner supplied. These win over the Commons file. */
const OWNED: Record<string, Omit<GroupImage, "alt"> & { alt: Record<Locale, string> }> = {
  ganesha: {
    src: "/images/bhajans/ganesha-owner.jpg",
    width: 736,
    height: 1308,
    position: "50% 30%",
    credit: OWNER,
    alt: {
      en: "A crowned Ganesha murti in close view, the trunk curled and the ear spread wide",
      kn: "ಕಿರೀಟಧಾರಿ ಗಣೇಶನ ಸಮೀಪ ನೋಟ — ಸುರುಟಿದ ಸೊಂಡಿಲು, ಅಗಲವಾದ ಕಿವಿ",
      hi: "मुकुटधारी गणेश की निकट छवि — मुड़ी हुई सूँड़ और फैला हुआ कान",
    },
  },
  venkateshwara: {
    src: "/images/bhajans/venkateshwara.jpg",
    width: 1080,
    height: 1439,
    position: "50% 35%",
    credit: OWNER,
    alt: {
      en: "Venkateshwara standing between his consorts, heaped with flower garlands",
      kn: "ಇಕ್ಕೆಲದಲ್ಲಿ ದೇವಿಯರೊಂದಿಗೆ ನಿಂತ ವೆಂಕಟೇಶ್ವರ, ಹೂಮಾಲೆಗಳಿಂದ ಅಲಂಕೃತ",
      hi: "दोनों ओर देवियों के साथ खड़े वेंकटेश्वर, पुष्पमालाओं से अलंकृत",
    },
  },
  devi: {
    src: "/images/bhajans/devi.jpg",
    width: 1053,
    height: 1336,
    position: "50% 30%",
    credit: OWNER,
    alt: {
      en: "The Devi in a lamplit shrine, garlanded, with a lion mask below her",
      kn: "ದೀಪ ಬೆಳಗುವ ಗರ್ಭಗುಡಿಯಲ್ಲಿ ಮಾಲಾಲಂಕೃತ ದೇವಿ, ಕೆಳಗೆ ಸಿಂಹಮುಖ",
      hi: "दीपों से आलोकित गर्भगृह में मालालंकृत देवी, नीचे सिंहमुख",
    },
  },
  lakshmi: {
    src: "/images/bhajans/lakshmi.jpg",
    width: 1076,
    height: 1252,
    position: "50% 35%",
    credit: OWNER,
    alt: {
      en: "Lakshmi crowned and garlanded in pink and violet flowers",
      kn: "ಕಿರೀಟ ತೊಟ್ಟು ಗುಲಾಬಿ ಮತ್ತು ನೇರಳೆ ಹೂಗಳ ಮಾಲೆಯಲ್ಲಿ ಲಕ್ಷ್ಮಿ",
      hi: "मुकुट धारण किए गुलाबी और बैंगनी पुष्पों की माला में लक्ष्मी",
    },
  },
};

/** Alt text for the Commons pictures, which the manifest cannot carry. */
const COMMONS_ALT: Record<string, Record<Locale, string>> = {
  krishna: {
    en: "Krishna as envoy, a painting by Raja Ravi Varma",
    kn: "ದೂತನಾಗಿ ನಿಂತ ಕೃಷ್ಣ — ರಾಜಾ ರವಿವರ್ಮರ ಚಿತ್ರ",
    hi: "दूत के रूप में कृष्ण — राजा रवि वर्मा की कृति",
  },
  vitthala: {
    en: "Vitthala standing with his hands on his hips, as at Pandharpur",
    kn: "ಪಂಢರಪುರದಲ್ಲಿನಂತೆ ಸೊಂಟದ ಮೇಲೆ ಕೈಇಟ್ಟು ನಿಂತ ವಿಠ್ಠಲ",
    hi: "पंढरपुर की तरह कमर पर हाथ धरे खड़े विट्ठल",
  },
  vishnu: {
    en: "Vishnu carved at the Jagdish temple, Udaipur",
    kn: "ಉದಯಪುರದ ಜಗದೀಶ ದೇವಾಲಯದಲ್ಲಿ ಕೆತ್ತಿದ ವಿಷ್ಣು",
    hi: "उदयपुर के जगदीश मंदिर में उत्कीर्ण विष्णु",
  },
  anjaneya: {
    en: "Hanuman carved on a temple wall at Madurai",
    kn: "ಮಧುರೈನ ದೇವಾಲಯದ ಗೋಡೆಯಲ್ಲಿ ಕೆತ್ತಿದ ಹನುಮಂತ",
    hi: "मदुरै के मंदिर की भित्ति पर उत्कीर्ण हनुमान",
  },
  shiva: {
    en: "Shiva with Parvati, a painting by Raja Ravi Varma",
    kn: "ಪಾರ್ವತಿಯೊಂದಿಗೆ ಶಿವ — ರಾಜಾ ರವಿವರ್ಮರ ಚಿತ್ರ",
    hi: "पार्वती के साथ शिव — राजा रवि वर्मा की कृति",
  },
  raghavendra: {
    en: "A statue of Raghavendra Swami",
    kn: "ರಾಘವೇಂದ್ರ ಸ್ವಾಮಿಗಳ ಪ್ರತಿಮೆ",
    hi: "राघवेंद्र स्वामी की प्रतिमा",
  },
  saraswati: {
    en: "Saraswati with her veena, a painting by Raja Ravi Varma",
    kn: "ವೀಣೆ ಹಿಡಿದ ಸರಸ್ವತಿ — ರಾಜಾ ರವಿವರ್ಮರ ಚಿತ್ರ",
    hi: "वीणा लिए सरस्वती — राजा रवि वर्मा की कृति",
  },
  rama: {
    en: "Rama breaking the bow, a painting by Raja Ravi Varma",
    kn: "ಬಿಲ್ಲನ್ನು ಮುರಿಯುತ್ತಿರುವ ರಾಮ — ರಾಜಾ ರವಿವರ್ಮರ ಚಿತ್ರ",
    hi: "धनुष भंग करते राम — राजा रवि वर्मा की कृति",
  },
  narasimha: {
    en: "Narasimha, the lion-faced avatara, in a painting",
    kn: "ಸಿಂಹಮುಖದ ಅವತಾರ ನರಸಿಂಹ — ಚಿತ್ರ",
    hi: "सिंहमुख अवतार नरसिंह — चित्र",
  },
  ganesha: {
    en: "A Ganesha carved at Halebidu",
    kn: "ಹಳೇಬೀಡಿನಲ್ಲಿ ಕೆತ್ತಿದ ಗಣೇಶ",
    hi: "हलेबीडु में उत्कीर्ण गणेश",
  },
};

type CommonsEntry = { src: string; width: number; height: number; credit: string; sourceUrl: string };

const FROM_COMMONS = commons as Record<string, CommonsEntry>;

const IMAGES: Record<string, GroupImage> = {};

for (const [id, entry] of Object.entries(FROM_COMMONS)) {
  const alt = COMMONS_ALT[id];
  if (!alt) continue; // no alt text written yet means the picture is not used
  IMAGES[id] = { ...entry, position: "50% 40%", alt };
}
// The owner's photographs take precedence where he supplied one.
for (const [id, entry] of Object.entries(OWNED)) IMAGES[id] = entry;

/** The picture for a group, or undefined when it has none. */
export function groupImage(id: string): GroupImage | undefined {
  return IMAGES[id];
}

export function hasGroupImage(id: string): boolean {
  return id in IMAGES;
}

export function allGroupImages(): [string, GroupImage][] {
  return Object.entries(IMAGES);
}
