import type { Locale } from "@/i18n/config";
import commons from "../../../public/images/festivals/commons.json";

// ─────────────────────────────────────────────────────────
//  A photograph for every festival.
//
//  Generated by scripts/images/fetch-commons.mjs, which asks the
//  Commons API for each file's real licence and author and refuses
//  anything not freely licensed. The credits below are whatever
//  Commons actually returned, not what anyone typed here.
//
//  Alt text is written by hand, because a manifest cannot carry it
//  and because alt text describing the wrong thing is worse than
//  none. Each one says what is in the frame, not what the festival
//  means.
// ─────────────────────────────────────────────────────────

export interface FestivalImage {
  src: string;
  width: number;
  height: number;
  credit: string;
  sourceUrl: string;
  alt: Record<Locale, string>;
  /** Which part of the frame to keep when a hero crops it. */
  position?: string;
}

const ALT: Record<string, Record<Locale, string>> = {
  ugadi: {
    en: "A tray laid out for Ugadi, with flowers, fruit and the day's offerings",
    kn: "ಯುಗಾದಿಗಾಗಿ ಸಿದ್ಧಪಡಿಸಿದ ಹರಿವಾಣ — ಹೂವು, ಹಣ್ಣು ಮತ್ತು ಅಂದಿನ ನೈವೇದ್ಯ",
    hi: "उगादि के लिए सजी थाली — फूल, फल और दिन का नैवेद्य",
  },
  "rama-navami": {
    en: "A Rama Navami gathering",
    kn: "ರಾಮ ನವಮಿಯ ಸಮಾರಂಭ",
    hi: "राम नवमी का आयोजन",
  },
  "akshaya-tritiya": {
    en: "An Akshaya Tritiya observance",
    kn: "ಅಕ್ಷಯ ತದಿಗೆಯ ಆಚರಣೆ",
    hi: "अक्षय तृतीया का आचरण",
  },
  "guru-purnima": {
    en: "A Guru Purnima gathering",
    kn: "ಗುರು ಪೂರ್ಣಿಮೆಯ ಸಮಾರಂಭ",
    hi: "गुरु पूर्णिमा का आयोजन",
  },
  "nagara-panchami": {
    en: "An eighteenth-century naga stone, the coiled serpent carved in relief",
    kn: "ಹದಿನೆಂಟನೇ ಶತಮಾನದ ನಾಗರಕಲ್ಲು — ಸುರುಳಿ ಸುತ್ತಿದ ಸರ್ಪದ ಉಬ್ಬುಶಿಲ್ಪ",
    hi: "अठारहवीं सदी का नागकल्ल — कुंडली मारे सर्प का उभरा शिल्प",
  },
  varamahalakshmi: {
    en: "A Varamahalakshmi kalasha dressed as the goddess, with face, flowers and ornaments",
    kn: "ದೇವಿಯಂತೆ ಅಲಂಕರಿಸಿದ ವರಮಹಾಲಕ್ಷ್ಮಿ ಕಲಶ — ಮುಖ, ಹೂವು ಮತ್ತು ಒಡವೆಗಳೊಂದಿಗೆ",
    hi: "देवी की तरह सजाया वरमहालक्ष्मी कलश — मुख, पुष्प और आभूषणों सहित",
  },
  "krishna-janmashtami": {
    en: "A Janmashtami celebration",
    kn: "ಜನ್ಮಾಷ್ಟಮಿಯ ಆಚರಣೆ",
    hi: "जन्माष्टमी का उत्सव",
  },
  "ganesha-chaturthi": {
    en: "A Ganesha image set up for the festival",
    kn: "ಹಬ್ಬಕ್ಕಾಗಿ ಪ್ರತಿಷ್ಠಾಪಿಸಿದ ಗಣೇಶ ಮೂರ್ತಿ",
    hi: "पर्व के लिए स्थापित गणेश मूर्ति",
  },
  navaratri: {
    en: "A golu — dolls arranged on stepped shelves for the nine nights",
    kn: "ಗೊಂಬೆ ಹಬ್ಬ — ಒಂಬತ್ತು ರಾತ್ರಿಗಳಿಗಾಗಿ ಮೆಟ್ಟಿಲು ಜಗಲಿಯ ಮೇಲೆ ಜೋಡಿಸಿದ ಗೊಂಬೆಗಳು",
    hi: "गोलू — नौ रातों के लिए सीढ़ीनुमा तख्तों पर सजाई गुड़ियाँ",
  },
  vijayadashami: {
    en: "The Mysore Palace lit for Dasara",
    kn: "ದಸರೆಗಾಗಿ ದೀಪಾಲಂಕೃತ ಮೈಸೂರು ಅರಮನೆ",
    hi: "दसरा के लिए दीपों से सजा मैसूर महल",
  },
  deepavali: {
    en: "Rows of oil lamps lit for Deepavali",
    kn: "ದೀಪಾವಳಿಗಾಗಿ ಸಾಲಾಗಿ ಹಚ್ಚಿದ ಎಣ್ಣೆ ದೀಪಗಳು",
    hi: "दीपावली के लिए पंक्तियों में जलाए तेल के दीप",
  },
  "utthana-dwadashi": {
    en: "A tulasi vivaha — the plant dressed and married with a canopy over it",
    kn: "ತುಳಸಿ ವಿವಾಹ — ಅಲಂಕರಿಸಿದ ಗಿಡ, ಮೇಲೆ ಚಪ್ಪರ",
    hi: "तुलसी विवाह — सजाया हुआ पौधा, ऊपर मंडप",
  },
  "gita-jayanti": {
    en: "A nineteenth-century illustrated Bhagavad Gita manuscript",
    kn: "ಹತ್ತೊಂಬತ್ತನೇ ಶತಮಾನದ ಚಿತ್ರಸಹಿತ ಭಗವದ್ಗೀತಾ ಹಸ್ತಪ್ರತಿ",
    hi: "उन्नीसवीं सदी की सचित्र भगवद्गीता पांडुलिपि",
  },
  "makara-sankranti": {
    en: "The Pongal dish cooking in its pot, boiling over as it should",
    kn: "ಮಡಕೆಯಲ್ಲಿ ಬೇಯುತ್ತಿರುವ ಪೊಂಗಲ್ — ಆಗಬೇಕಾದಂತೆಯೇ ಉಕ್ಕಿ ಹರಿಯುತ್ತ",
    hi: "बर्तन में पकता पोंगल — जैसा होना चाहिए वैसे ही उफनता हुआ",
  },
  "maha-shivaratri": {
    en: "A Mahashivaratri observance",
    kn: "ಮಹಾಶಿವರಾತ್ರಿಯ ಆಚರಣೆ",
    hi: "महाशिवरात्रि का आचरण",
  },
  holi: {
    en: "Colour thrown at Holi",
    kn: "ಹೋಳಿಯಲ್ಲಿ ಎರಚುವ ಬಣ್ಣ",
    hi: "होली में उड़ता रंग",
  },
};

type Entry = { src: string; width: number; height: number; credit: string; sourceUrl: string };
const FROM_COMMONS = commons as Record<string, Entry>;

const IMAGES: Record<string, FestivalImage> = {};
for (const [id, entry] of Object.entries(FROM_COMMONS)) {
  const alt = ALT[id];
  // No alt text written means the picture is not used. A photograph
  // with no description is not an improvement on no photograph.
  if (!alt) continue;
  IMAGES[id] = { ...entry, alt, position: "50% 50%" };
}

export function festivalImage(slug: string): FestivalImage | undefined {
  return IMAGES[slug];
}

export function allFestivalImages(): [string, FestivalImage][] {
  return Object.entries(IMAGES);
}
