import type { Locale } from "@/i18n/config";
import commons from "../../../public/images/festivals/commons.json";

// ─────────────────────────────────────────────────────────
//  A picture for every festival.
//
//  Generated by scripts/images/fetch-commons.mjs, which asks the
//  Commons API for each file's real licence and author and refuses
//  anything not freely licensed.
//
//  **These are paintings, prints and sculpture, not snapshots.** The
//  first pass filtered on licence, size and filename without ever
//  looking at the results, and shipped a museum exhibit label with its
//  caption in frame, a boy with a water pistol, a bowl of flour, and a
//  cardboard cutout beside a woman at a microphone. Commons is full of
//  amateur festival photography and a keyword search surfaces it
//  first. Public domain artwork — Ravi Varma, Kalighat, Thanjavur,
//  Rajput miniatures, museum bronzes — is both better and freer.
//
//  **Look at every picture before it ships.** That is the rule the
//  bhajan images already wrote down and this section ignored.
//
//  **Alt text says what is in the frame**, not what the festival
//  means, and it is rewritten whenever a picture is. Alt text left
//  describing a picture that has been replaced is worse than none.
//
//  **`position` is not decoration.** Most of these are tall paintings
//  and the card crops them to 4:3; centred, that beheaded Lakshmi,
//  Vasantika and Dakshinamurti. Each one names the part of the frame
//  the crop must keep.
// ─────────────────────────────────────────────────────────

export interface FestivalImage {
  src: string;
  width: number;
  height: number;
  credit: string;
  sourceUrl: string;
  alt: Record<Locale, string>;
  /** Which part of the frame the card must keep when it crops. */
  position?: string;
}

const ALT: Record<string, Record<Locale, string>> = {
  ugadi: {
    en: "Vasantika, spring personified, in a print by Raja Ravi Varma",
    kn: "ವಸಂತಿಕಾ — ವಸಂತ ಋತುವಿನ ಮೂರ್ತರೂಪ; ರಾಜಾ ರವಿವರ್ಮರ ಮುದ್ರಣ",
    hi: "वसंतिका — वसंत का मूर्त रूप; राजा रवि वर्मा का मुद्रण",
  },
  "rama-navami": {
    en: "The Ramapanchayan — Rama and Sita enthroned with Lakshmana, Bharata, Shatrughna and Hanuman, after Raja Ravi Varma",
    kn: "ರಾಮಪಂಚಾಯನ — ಲಕ್ಷ್ಮಣ, ಭರತ, ಶತ್ರುಘ್ನ ಮತ್ತು ಹನುಮಂತನೊಡನೆ ಸಿಂಹಾಸನಸ್ಥ ರಾಮ-ಸೀತೆಯರು; ರಾಜಾ ರವಿವರ್ಮರ ಶೈಲಿ",
    hi: "रामपंचायन — लक्ष्मण, भरत, शत्रुघ्न और हनुमान सहित सिंहासनस्थ राम-सीता; राजा रवि वर्मा शैली",
  },
  "akshaya-tritiya": {
    en: "Gajalakshmi — Lakshmi bathed by elephants, seated on a lotus",
    kn: "ಗಜಲಕ್ಷ್ಮಿ — ಆನೆಗಳಿಂದ ಅಭಿಷಿಕ್ತಳಾಗಿ, ಕಮಲದ ಮೇಲೆ ಆಸೀನಳಾದ ಲಕ್ಷ್ಮಿ",
    hi: "गजलक्ष्मी — हाथियों द्वारा अभिषिक्त, कमल पर आसीन लक्ष्मी",
  },
  "guru-purnima": {
    en: "Dakshinamurti, Shiva as the teacher who instructs in silence — a stone sculpture",
    kn: "ದಕ್ಷಿಣಾಮೂರ್ತಿ — ಮೌನದಿಂದಲೇ ಬೋಧಿಸುವ ಗುರುರೂಪಿ ಶಿವ; ಶಿಲಾಶಿಲ್ಪ",
    hi: "दक्षिणामूर्ति — मौन से उपदेश देने वाले गुरुरूप शिव; प्रस्तर शिल्प",
  },
  "nagara-panchami": {
    en: "Krishna dancing on the hood of the serpent king Kaliya, in a miniature painting",
    kn: "ನಾಗರಾಜ ಕಾಳಿಂಗನ ಫಣೆಯ ಮೇಲೆ ನರ್ತಿಸುತ್ತಿರುವ ಕೃಷ್ಣ — ಲಘುಚಿತ್ರ",
    hi: "नागराज कालिय के फण पर नृत्य करते कृष्ण — लघुचित्र",
  },
  varamahalakshmi: {
    en: "Lakshmi standing among lotuses, in a Ravi Varma Press print of the 1930s",
    kn: "ಕಮಲಗಳ ನಡುವೆ ನಿಂತ ಲಕ್ಷ್ಮಿ — ೧೯೩೦ರ ದಶಕದ ರವಿವರ್ಮ ಪ್ರೆಸ್ ಮುದ್ರಣ",
    hi: "कमलों के बीच खड़ी लक्ष्मी — १९३० के दशक का रवि वर्मा प्रेस मुद्रण",
  },
  "krishna-janmashtami": {
    en: "A painting of the night of Krishna's birth, the child carried across the river to Gokula",
    kn: "ಕೃಷ್ಣ ಜನಿಸಿದ ರಾತ್ರಿಯ ಚಿತ್ರ — ಮಗುವನ್ನು ನದಿ ದಾಟಿಸಿ ಗೋಕುಲಕ್ಕೆ ಒಯ್ಯುವ ಸನ್ನಿವೇಶ",
    hi: "कृष्ण के जन्म की रात का चित्र — शिशु को नदी पार कराकर गोकुल ले जाते हुए",
  },
  "ganesha-chaturthi": {
    en: "Ganesha riding his mount, in a Thanjavur painting",
    kn: "ವಾಹನಾರೂಢ ಗಣೇಶ — ತಂಜಾವೂರು ಶೈಲಿಯ ಚಿತ್ರ",
    hi: "वाहन पर आरूढ़ गणेश — तंजावुर शैली का चित्र",
  },
  navaratri: {
    en: "Durga slaying the buffalo demon Mahishasura, in a nineteenth-century painting",
    kn: "ಮಹಿಷಾಸುರನನ್ನು ಸಂಹರಿಸುತ್ತಿರುವ ದುರ್ಗೆ — ಹತ್ತೊಂಬತ್ತನೇ ಶತಮಾನದ ಚಿತ್ರ",
    hi: "महिषासुर का वध करती दुर्गा — उन्नीसवीं सदी का चित्र",
  },
  vijayadashami: {
    en: "The Mysore Palace lit for Dasara",
    kn: "ದಸರೆಗಾಗಿ ದೀಪಾಲಂಕೃತ ಮೈಸೂರು ಅರಮನೆ",
    hi: "दसरा के लिए दीपों से सजा मैसूर महल",
  },
  deepavali: {
    en: "A single clay lamp burning against the dark",
    kn: "ಕತ್ತಲೆಯ ಎದುರು ಉರಿಯುತ್ತಿರುವ ಒಂದೇ ಮಣ್ಣಿನ ಹಣತೆ",
    hi: "अँधेरे के सामने जलता एक मिट्टी का दीपक",
  },
  "utthana-dwadashi": {
    en: "A tulasi vivaha — the plant dressed and married with a canopy over it",
    kn: "ತುಳಸಿ ವಿವಾಹ — ಅಲಂಕರಿಸಿದ ಗಿಡ, ಮೇಲೆ ಚಪ್ಪರ",
    hi: "तुलसी विवाह — सजाया हुआ पौधा, ऊपर मंडप",
  },
  "gita-jayanti": {
    en: "Krishna and Arjuna in the chariot between the two armies",
    kn: "ಎರಡು ಸೇನೆಗಳ ನಡುವೆ ರಥದಲ್ಲಿ ಕೃಷ್ಣ ಮತ್ತು ಅರ್ಜುನ",
    hi: "दो सेनाओं के बीच रथ में कृष्ण और अर्जुन",
  },
  "makara-sankranti": {
    en: "A wheel of the sun god's chariot, carved at the Konark temple",
    kn: "ಕೋನಾರ್ಕ ದೇವಾಲಯದಲ್ಲಿ ಕೆತ್ತಿದ ಸೂರ್ಯದೇವನ ರಥಚಕ್ರ",
    hi: "कोणार्क मंदिर में उत्कीर्ण सूर्यदेव के रथ का चक्र",
  },
  "maha-shivaratri": {
    en: "Shiva as Nataraja, lord of the dance — a bronze",
    kn: "ನಟರಾಜ ಶಿವ — ನೃತ್ಯದ ಅಧಿಪತಿ; ಕಂಚಿನ ಮೂರ್ತಿ",
    hi: "नटराज शिव — नृत्य के स्वामी; कांस्य प्रतिमा",
  },
  holi: {
    en: "Krishna and Radha playing Holi with the gopis, in a miniature painting",
    kn: "ಗೋಪಿಕೆಯರೊಡನೆ ಹೋಳಿ ಆಡುತ್ತಿರುವ ಕೃಷ್ಣ ಮತ್ತು ರಾಧೆ — ಲಘುಚಿತ್ರ",
    hi: "गोपियों के साथ होली खेलते कृष्ण और राधा — लघुचित्र",
  },
};

/**
 * Where the 4:3 card must crop. A tall painting centred loses the
 * head, which is the one part of a portrait that has to survive.
 */
const POSITION: Record<string, string> = {
  ugadi: "50% 20%",
  "akshaya-tritiya": "50% 40%",
  "rama-navami": "50% 28%",
  "guru-purnima": "50% 18%",
  varamahalakshmi: "50% 20%",
  navaratri: "50% 26%",
  "ganesha-chaturthi": "50% 34%",
  "gita-jayanti": "50% 26%",
  "maha-shivaratri": "50% 38%",
  holi: "50% 32%",
  "nagara-panchami": "50% 30%",
  "makara-sankranti": "50% 44%",
};

type Entry = { src: string; width: number; height: number; credit: string; sourceUrl: string };
const FROM_COMMONS = commons as Record<string, Entry>;

const IMAGES: Record<string, FestivalImage> = {};
for (const [id, entry] of Object.entries(FROM_COMMONS)) {
  const alt = ALT[id];
  // No alt text written means the picture is not used. A photograph
  // with no description is not an improvement on no photograph.
  if (!alt) continue;
  IMAGES[id] = { ...entry, alt, position: POSITION[id] ?? "50% 50%" };
}

export function festivalImage(slug: string): FestivalImage | undefined {
  return IMAGES[slug];
}

export function allFestivalImages(): [string, FestivalImage][] {
  return Object.entries(IMAGES);
}
