import type { Locale } from "@/i18n/config";

// ─────────────────────────────────────────────────────────
//  Commentary on the Īśāvāsya Upaniṣad.
//
//  Split out from isha.ts on purpose. The mūla and its
//  transliteration are fixed — they have not changed in two and a
//  half thousand years and they will not change here. Commentary
//  is the opposite: it is the living layer, it will be revised,
//  argued with and lengthened, and it should be editable without
//  anyone going near the verse text.
//
//  What the commentary draws on, and what it does not:
//
//    · Śaṅkara's bhāṣya is the reference reading, and where his
//      interpretation is contested — verses 9–14 especially — the
//      disagreement is named rather than smoothed over.
//    · The Kāṇva recension (18 verses) is the one set here. The
//      Mādhyandina has 17 and orders 9–14 differently; that is
//      flagged where it changes the sense.
//    · Where Madhva, Rāmānuja or Aurobindo read a verse in a way
//      that genuinely diverges from Śaṅkara, that is said plainly
//      instead of presenting one school's reading as the meaning.
//
//  This is still the site's own editorial prose, not a translation
//  of anyone's published bhāṣya, and it is labelled as such
//  everywhere it appears.
// ─────────────────────────────────────────────────────────

export type Commentary = Record<Locale, string>;

export const ISHA_COMMENTARY: Record<string, Commentary> = {
  "isha-shanti": {
    en: "The invocation is not decoration; it states the arithmetic the whole text depends on. 'That' (adaḥ) is Brahman unmanifest, 'this' (idam) the world in front of you, and the verse refuses at once to make the second a fragment of the first. Both are called pūrṇa — full, lacking nothing.\n\nThen it introduces subtraction only to defeat it. Remove the whole from the whole and the whole remains. Any quantity behaves otherwise: take from it and it diminishes. What is being denied, then, is not a particular measurement but measurement itself as a way of thinking about what is real. This is why the Upaniṣad can later insist that the world is to be enjoyed rather than escaped — a world that is pūrṇa is not a lesser thing you are trapped inside.\n\nThe threefold śānti is not repetition for emphasis. It quiets three specific classes of obstacle: ādhyātmika, arising in oneself; ādhibhautika, from other beings; ādhidaivika, from forces beyond anyone's control.",
    kn: "ಈ ಶಾಂತಿಮಂತ್ರ ಅಲಂಕಾರವಲ್ಲ; ಇಡೀ ಪಠ್ಯವು ಆಧರಿಸಿರುವ ಗಣಿತವನ್ನೇ ಅದು ಹೇಳುತ್ತದೆ. 'ಅದಃ' ಎಂದರೆ ಅವ್ಯಕ್ತ ಬ್ರಹ್ಮ, 'ಇದಂ' ಎಂದರೆ ನಿಮ್ಮೆದುರಿನ ಜಗತ್ತು; ಎರಡನೆಯದನ್ನು ಮೊದಲನೆಯದರ ತುಣುಕೆಂದು ಒಪ್ಪಲು ಶ್ಲೋಕ ಆರಂಭದಲ್ಲಿಯೇ ನಿರಾಕರಿಸುತ್ತದೆ. ಎರಡನ್ನೂ 'ಪೂರ್ಣ' ಎಂದೇ ಕರೆದಿದೆ — ಯಾವ ಕೊರತೆಯೂ ಇಲ್ಲದ್ದು.\n\nಆಮೇಲೆ ವ್ಯವಕಲನವನ್ನು ತರುವುದೇ ಅದನ್ನು ಸೋಲಿಸುವುದಕ್ಕಾಗಿ. ಪೂರ್ಣದಿಂದ ಪೂರ್ಣವನ್ನು ತೆಗೆದರೂ ಪೂರ್ಣವೇ ಉಳಿಯುತ್ತದೆ. ಯಾವ ಪರಿಮಾಣವೂ ಹೀಗೆ ವರ್ತಿಸುವುದಿಲ್ಲ: ಅದರಿಂದ ತೆಗೆದರೆ ಅದು ಕಡಿಮೆಯಾಗುತ್ತದೆ. ಆದ್ದರಿಂದ ಇಲ್ಲಿ ನಿರಾಕರಿಸಲ್ಪಡುತ್ತಿರುವುದು ಒಂದು ನಿರ್ದಿಷ್ಟ ಅಳತೆಯಲ್ಲ, ವಾಸ್ತವವನ್ನು ಕುರಿತು ಯೋಚಿಸುವ ಕ್ರಮವಾಗಿ ಅಳತೆಯೇ. ಜಗತ್ತನ್ನು ತೊರೆಯುವುದಲ್ಲ, ಅನುಭವಿಸುವುದೇ ಎಂದು ಮುಂದೆ ಉಪನಿಷತ್ತು ಹೇಳಲು ಇದೇ ಕಾರಣ — ಪೂರ್ಣವಾದ ಜಗತ್ತು ನೀವು ಸಿಕ್ಕಿಬಿದ್ದಿರುವ ಕೀಳು ವಸ್ತುವಲ್ಲ.\n\nಮೂರು ಬಾರಿಯ ಶಾಂತಿ ಒತ್ತು ಕೊಡುವ ಪುನರಾವರ್ತನೆಯಲ್ಲ. ಅದು ಮೂರು ನಿರ್ದಿಷ್ಟ ವಿಘ್ನಗಳನ್ನು ಶಮನಗೊಳಿಸುತ್ತದೆ: ತನ್ನಲ್ಲಿಯೇ ಹುಟ್ಟುವ ಆಧ್ಯಾತ್ಮಿಕ, ಇತರ ಜೀವಿಗಳಿಂದ ಬರುವ ಆಧಿಭೌತಿಕ, ಮತ್ತು ಯಾರ ಹಿಡಿತಕ್ಕೂ ಸಿಗದ ಶಕ್ತಿಗಳಿಂದ ಬರುವ ಆಧಿದೈವಿಕ.",
    hi: "यह शांतिमंत्र अलंकार नहीं; यह उस गणित को कहता है जिस पर सारा पाठ टिका है। 'अदः' अव्यक्त ब्रह्म है, 'इदम्' आपके सामने का जगत्, और श्लोक आरंभ में ही दूसरे को पहले का टुकड़ा मानने से इनकार कर देता है। दोनों को 'पूर्ण' कहा गया है — जिसमें कोई कमी नहीं।\n\nफिर घटाव को लाया ही इसलिए जाता है कि उसे परास्त किया जाए। पूर्ण में से पूर्ण निकाल लीजिए, पूर्ण ही शेष रहता है। कोई भी परिमाण ऐसा व्यवहार नहीं करता: उसमें से निकालिए, वह घट जाता है। अतः यहाँ जिसका निषेध है वह कोई विशेष माप नहीं, बल्कि वास्तविकता के बारे में सोचने के ढंग के रूप में माप ही है। इसीलिए उपनिषद् आगे कह पाता है कि जगत् त्याज्य नहीं, भोग्य है — जो जगत् पूर्ण है वह कोई हीन वस्तु नहीं जिसमें आप फँसे हों।\n\nतीन बार का शांतिपाठ बल देने की पुनरुक्ति नहीं। वह तीन विशिष्ट विघ्नों को शांत करता है: स्वयं में उठने वाला आध्यात्मिक, अन्य प्राणियों से आने वाला आधिभौतिक, और किसी के वश से परे शक्तियों से आने वाला आधिदैविक।",
  },

  "isha-1": {
    en: "Everything the Upaniṣad will argue is compressed into this verse, and it moves in three steps.\n\nFirst, īśā vāsyam. The world is to be clothed, indwelt, pervaded by the Lord. Vāsya is from the root meaning to cover or to dwell in — not a wall between you and the divine but a garment the divine is wearing. Nothing is excluded, which means nothing requires escaping. Note the world is described as jagat, 'the moving' — the transient is named as transient and included anyway.\n\nSecond, tena tyaktena bhuñjīthāḥ. This is the line everything turns on, and it is routinely mistranslated as a bargain: give things up now, be rewarded later. It says something stranger. The renouncing is itself the enjoying. Grasping is what spoils a thing; released, the same world becomes available for the first time. Śaṅkara reads tyakta as renunciation proper; others read it as 'what is left to you', what is given rather than seized. Both readings converge on the practice.\n\nThird, the reason nobody can own anything: mā gṛdhaḥ kasya svid dhanam — whose is wealth, anyway? The question is not rhetorical scolding. It is a plain observation that ownership was never a fact about the world.",
    kn: "ಉಪನಿಷತ್ತು ಮುಂದೆ ಮಂಡಿಸಲಿರುವ ಎಲ್ಲವೂ ಈ ಒಂದೇ ಶ್ಲೋಕದಲ್ಲಿ ಸಂಗ್ರಹವಾಗಿದೆ, ಮತ್ತು ಅದು ಮೂರು ಹೆಜ್ಜೆಗಳಲ್ಲಿ ಸಾಗುತ್ತದೆ.\n\nಮೊದಲನೆಯದು: 'ಈಶಾ ವಾಸ್ಯಮ್'. ಜಗತ್ತನ್ನು ಈಶ್ವರನಿಂದ ಹೊದಿಸಬೇಕು, ಅವನು ಅದರಲ್ಲಿ ನೆಲೆಸಬೇಕು. 'ವಾಸ್ಯ' ಎಂಬುದು ಹೊದಿಸು ಅಥವಾ ವಾಸಿಸು ಎಂಬ ಧಾತುವಿನಿಂದ ಬಂದದ್ದು — ನಿಮಗೂ ದೈವಕ್ಕೂ ನಡುವಿನ ಗೋಡೆಯಲ್ಲ, ದೈವವೇ ಧರಿಸಿರುವ ವಸ್ತ್ರ. ಯಾವುದೂ ಹೊರಗಿಲ್ಲ, ಅಂದರೆ ಯಾವುದರಿಂದಲೂ ಓಡಿಹೋಗಬೇಕಿಲ್ಲ. ಜಗತ್ತನ್ನು 'ಜಗತ್' ಅಂದರೆ 'ಚಲಿಸುವುದು' ಎಂದೇ ಕರೆದಿರುವುದನ್ನು ಗಮನಿಸಿ — ಅನಿತ್ಯವನ್ನು ಅನಿತ್ಯವೆಂದೇ ಹೆಸರಿಸಿ, ಆದರೂ ಒಳಗೊಂಡಿದೆ.\n\nಎರಡನೆಯದು: 'ತೇನ ತ್ಯಕ್ತೇನ ಭುಂಜೀಥಾಃ'. ಎಲ್ಲವೂ ತಿರುಗುವ ಸಾಲಿದು, ಮತ್ತು ಇದನ್ನು ಸಾಮಾನ್ಯವಾಗಿ ಒಂದು ವ್ಯಾಪಾರವೆಂಬಂತೆ ತಪ್ಪಾಗಿ ಅನುವಾದಿಸಲಾಗುತ್ತದೆ: ಈಗ ಬಿಡು, ಮುಂದೆ ಫಲ ಪಡೆ. ಆದರೆ ಅದು ಹೇಳುವುದು ಬೇರೆಯದೇ. ತ್ಯಜಿಸುವುದೇ ಅನುಭವಿಸುವುದು. ಹಿಡಿದಿಟ್ಟುಕೊಳ್ಳುವುದೇ ವಸ್ತುವನ್ನು ಕೆಡಿಸುತ್ತದೆ; ಬಿಟ್ಟಾಗ ಅದೇ ಜಗತ್ತು ಮೊದಲ ಬಾರಿಗೆ ಲಭ್ಯವಾಗುತ್ತದೆ. ಶಂಕರರು 'ತ್ಯಕ್ತ'ವನ್ನು ಸಂನ್ಯಾಸವೆಂದು ಓದುತ್ತಾರೆ; ಇತರರು 'ನಿಮಗೆ ಉಳಿಸಿಕೊಟ್ಟದ್ದು', ಕಸಿದುಕೊಳ್ಳದೆ ದೊರೆತದ್ದು ಎಂದು ಓದುತ್ತಾರೆ. ಎರಡೂ ಓದುಗಳು ಆಚರಣೆಯಲ್ಲಿ ಒಂದೇ ಕಡೆ ಸೇರುತ್ತವೆ.\n\nಮೂರನೆಯದು: ಯಾರೂ ಏನನ್ನೂ ಸ್ವಂತ ಮಾಡಿಕೊಳ್ಳಲಾರರು ಎಂಬುದಕ್ಕೆ ಕಾರಣ — 'ಮಾ ಗೃಧಃ ಕಸ್ಯಸ್ವಿದ್ಧನಮ್', ಸಂಪತ್ತು ಯಾರದು? ಇದು ಬೈಗುಳದ ಪ್ರಶ್ನೆಯಲ್ಲ. ಒಡೆತನವೆಂಬುದು ಜಗತ್ತಿನ ಸತ್ಯವೇ ಆಗಿರಲಿಲ್ಲ ಎಂಬ ಸರಳ ಗಮನಿಕೆ.",
    hi: "उपनिषद् आगे जो कुछ कहेगा, वह सब इसी एक श्लोक में संपिंडित है, और वह तीन चरणों में चलता है।\n\nपहला: 'ईशा वास्यम्'। जगत् को ईश्वर से आवृत होना है, उसमें ईश्वर का वास होना है। 'वास्य' उस धातु से है जिसका अर्थ ढकना या बसना है — आपके और दैवी के बीच दीवार नहीं, बल्कि वह वस्त्र जो दैवी पहने है। कुछ भी बाहर नहीं, अर्थात् किसी से भागना नहीं। ध्यान दें कि जगत् को 'जगत्' अर्थात् 'जो चलता है' कहा गया — अनित्य को अनित्य कहकर भी सम्मिलित किया गया।\n\nदूसरा: 'तेन त्यक्तेन भुञ्जीथाः'। यही वह पंक्ति है जिस पर सब घूमता है, और इसका प्रायः सौदे की तरह गलत अनुवाद होता है: अभी छोड़ो, बाद में फल पाओ। किंतु यह कुछ और ही कहती है। त्यागना ही भोगना है। पकड़ना ही वस्तु को बिगाड़ता है; छोड़ देने पर वही जगत् पहली बार सुलभ होता है। शंकर 'त्यक्त' को संन्यास पढ़ते हैं; अन्य इसे 'जो तुम्हारे लिए छोड़ा गया', जो छीना नहीं बल्कि दिया गया, पढ़ते हैं। दोनों पाठ आचरण में एक ही जगह मिलते हैं।\n\nतीसरा: कोई किसी वस्तु का स्वामी क्यों नहीं — 'मा गृधः कस्यस्विद्धनम्', धन है किसका? यह उलाहने का प्रश्न नहीं। यह सीधी टिप्पणी है कि स्वामित्व कभी जगत् का तथ्य था ही नहीं।",
  },

  "isha-2": {
    en: "Having praised renunciation, the text immediately refuses to let it become an excuse to withdraw — and the speed of that reversal is the point.\n\nA hundred years of action is not a concession to the weak. It is the recommended course, stated with kurvann eva, 'performing works indeed'. The Upaniṣad is not embarrassed by a full life.\n\nThe operative word is lipyate, 'smears' or 'adheres'. Action is not the problem; adhesion is. Once verse 1 has removed ownership from the picture, work can be done at full stretch and leave no residue on the doer. What sticks to a person is not the deed but the claim on the deed.\n\nŚaṅkara reads verses 1 and 2 as addressed to two different competences — verse 1 to the renunciate capable of knowledge, verse 2 to the householder who must still act. This is a real interpretive fork, and it matters: on his reading the text offers two paths, while on the plainer reading it offers one instruction in two halves. Sri Aurobindo argued strongly for the latter, and the structure of verses 9–14 — which insists twice that both members of a pair be held together — supports him.",
    kn: "ತ್ಯಾಗವನ್ನು ಹೊಗಳಿದ ಕೂಡಲೇ ಅದು ಹಿಂದೆ ಸರಿಯುವುದಕ್ಕೆ ನೆಪವಾಗದಂತೆ ಪಠ್ಯ ತಡೆಯುತ್ತದೆ — ಮತ್ತು ಆ ತಿರುಗುವಿಕೆಯ ವೇಗವೇ ಇಲ್ಲಿನ ಸಾರ.\n\nಕರ್ಮದಲ್ಲಿ ಕಳೆದ ನೂರು ವರ್ಷ ದುರ್ಬಲರಿಗೆ ಕೊಟ್ಟ ರಿಯಾಯಿತಿಯಲ್ಲ. 'ಕುರ್ವನ್ನೇವ' — ಕರ್ಮಗಳನ್ನು ಮಾಡುತ್ತಲೇ — ಎಂದು ಹೇಳಿರುವ ಇದೇ ಶಿಫಾರಸು ಮಾಡಿದ ಮಾರ್ಗ. ಪೂರ್ಣ ಬದುಕಿನ ಬಗ್ಗೆ ಉಪನಿಷತ್ತಿಗೆ ಸಂಕೋಚವಿಲ್ಲ.\n\nಮುಖ್ಯ ಪದ 'ಲಿಪ್ಯತೇ' — ಅಂಟುವುದು, ಲೇಪಿಸುವುದು. ಕರ್ಮ ಸಮಸ್ಯೆಯಲ್ಲ; ಅಂಟುವಿಕೆ ಸಮಸ್ಯೆ. ಮೊದಲ ಶ್ಲೋಕ ಒಡೆತನವನ್ನು ತೆಗೆದುಹಾಕಿದ ಮೇಲೆ, ಕರ್ತೃವಿನ ಮೇಲೆ ಯಾವ ಕಲೆಯನ್ನೂ ಉಳಿಸದೆ ಪೂರ್ಣ ಶಕ್ತಿಯಿಂದ ಕೆಲಸ ಮಾಡಬಹುದು. ಮನುಷ್ಯನಿಗೆ ಅಂಟುವುದು ಕರ್ಮವಲ್ಲ, ಕರ್ಮದ ಮೇಲಿನ ಹಕ್ಕು.\n\nಶಂಕರರು ೧ ಮತ್ತು ೨ನೆಯ ಶ್ಲೋಕಗಳನ್ನು ಬೇರೆ ಬೇರೆ ಅಧಿಕಾರಿಗಳಿಗೆ ಹೇಳಿದ್ದೆಂದು ಓದುತ್ತಾರೆ — ಮೊದಲನೆಯದು ಜ್ಞಾನಕ್ಕೆ ಅರ್ಹನಾದ ಸಂನ್ಯಾಸಿಗೆ, ಎರಡನೆಯದು ಇನ್ನೂ ಕರ್ಮ ಮಾಡಬೇಕಾದ ಗೃಹಸ್ಥನಿಗೆ. ಇದು ನಿಜವಾದ ವ್ಯಾಖ್ಯಾನ ಭೇದ ಮತ್ತು ಮುಖ್ಯವಾದದ್ದು: ಅವರ ಓದಿನಲ್ಲಿ ಪಠ್ಯವು ಎರಡು ಮಾರ್ಗಗಳನ್ನು ಕೊಡುತ್ತದೆ, ಸರಳ ಓದಿನಲ್ಲಿ ಒಂದೇ ಉಪದೇಶವನ್ನು ಎರಡು ಅರ್ಧಗಳಲ್ಲಿ ಕೊಡುತ್ತದೆ. ಶ್ರೀ ಅರವಿಂದರು ಎರಡನೆಯದನ್ನು ಬಲವಾಗಿ ಪ್ರತಿಪಾದಿಸಿದರು, ಮತ್ತು ಜೋಡಿಯ ಎರಡೂ ಸದಸ್ಯರನ್ನು ಜೊತೆಯಾಗಿ ಹಿಡಿಯಬೇಕೆಂದು ಎರಡು ಬಾರಿ ಒತ್ತಿಹೇಳುವ ೯–೧೪ನೆಯ ಶ್ಲೋಕಗಳ ರಚನೆ ಅವರಿಗೆ ಬೆಂಬಲ ನೀಡುತ್ತದೆ.",
    hi: "त्याग की प्रशंसा करते ही पाठ उसे पलायन का बहाना बनने से रोक देता है — और उस पलटाव की तेज़ी ही यहाँ का सार है।\n\nकर्म में बीते सौ वर्ष दुर्बलों को दी गई छूट नहीं। 'कुर्वन्नेव' — कर्म करते हुए ही — कहकर यही अनुशंसित मार्ग बताया गया है। पूर्ण जीवन से उपनिषद् को संकोच नहीं।\n\nमुख्य शब्द 'लिप्यते' है — लिपटना, लेप लगना। कर्म समस्या नहीं; चिपकना समस्या है। पहला श्लोक स्वामित्व हटा चुका, इसलिए कर्ता पर कोई अवशेष छोड़े बिना पूरी शक्ति से काम किया जा सकता है। मनुष्य से चिपकता कर्म नहीं, कर्म पर किया गया दावा है।\n\nशंकर १ और २ को दो भिन्न अधिकारियों के लिए पढ़ते हैं — पहला ज्ञान के योग्य संन्यासी के लिए, दूसरा उस गृहस्थ के लिए जिसे अभी कर्म करना है। यह वास्तविक व्याख्या-भेद है और महत्वपूर्ण है: उनके पाठ में पाठ दो मार्ग देता है, सीधे पाठ में एक ही उपदेश दो आधों में। श्री अरविंद ने दूसरे का प्रबल समर्थन किया, और ९–१४ की वह संरचना जो दो बार आग्रह करती है कि युग्म के दोनों सदस्य साथ थामे जाएँ, उन्हीं का पक्ष लेती है।",
  },

  "isha-3": {
    en: "The severest verse in the text, and its force comes from a pun that cannot be carried into English.\n\nAsurya means 'sunless'. Asurya also means 'belonging to the asuras'. The Upaniṣad uses both at once: the worlds in question are lightless and they are demonic, and these turn out to be the same description. Darkness here is not a punishment administered from outside. It is simply the condition of a life lived without reference to what one actually is.\n\nĀtmahan — 'Self-slayer' — is the phrase that startles. Taken literally it is impossible: the Ātman by definition cannot be killed, as the Kaṭha and the Gītā both insist at length. So the word must mean something else, and Śaṅkara's reading is the natural one — the Self-slayer is not someone who has destroyed the Self but someone who has lived as though it were absent. The killing is a killing of relevance, not of being.\n\nThat matters for what follows. Because the obscuring is self-administered, it can be undone; the remaining fifteen verses would be pointless otherwise. Ralph Griffith connected this verse specifically to the pursuit of ritual for future reward — action aimed at heaven rather than at truth — which links it directly back to verse 2's warning about adhesion.",
    kn: "ಪಠ್ಯದ ಅತ್ಯಂತ ಕಠಿಣ ಶ್ಲೋಕ, ಮತ್ತು ಅದರ ಬಲ ಇಂಗ್ಲಿಷಿಗೆ ಒಯ್ಯಲಾಗದ ಒಂದು ಶ್ಲೇಷೆಯಿಂದ ಬರುತ್ತದೆ.\n\n'ಅಸುರ್ಯ' ಎಂದರೆ 'ಸೂರ್ಯನಿಲ್ಲದ್ದು'. 'ಅಸುರ್ಯ' ಎಂದರೆ 'ಅಸುರರಿಗೆ ಸೇರಿದ್ದು' ಎಂದೂ ಆಗುತ್ತದೆ. ಉಪನಿಷತ್ತು ಎರಡನ್ನೂ ಏಕಕಾಲದಲ್ಲಿ ಬಳಸುತ್ತದೆ: ಆ ಲೋಕಗಳು ಬೆಳಕಿಲ್ಲದವು ಮತ್ತು ಅಸುರಸಂಬಂಧಿ, ಮತ್ತು ಇವೆರಡೂ ಒಂದೇ ವರ್ಣನೆಯೆಂದು ತಿಳಿಯುತ್ತದೆ. ಇಲ್ಲಿನ ಕತ್ತಲೆ ಹೊರಗಿನಿಂದ ವಿಧಿಸಿದ ಶಿಕ್ಷೆಯಲ್ಲ. ತಾನು ನಿಜಕ್ಕೂ ಏನೆಂಬುದರ ಉಲ್ಲೇಖವಿಲ್ಲದೆ ಬದುಕಿದ ಬದುಕಿನ ಸ್ಥಿತಿಯಷ್ಟೇ ಅದು.\n\n'ಆತ್ಮಹನ್' — ಆತ್ಮಘಾತಕ — ಎಂಬ ಪದವೇ ಬೆಚ್ಚಿಬೀಳಿಸುತ್ತದೆ. ಅಕ್ಷರಶಃ ತೆಗೆದುಕೊಂಡರೆ ಅದು ಅಸಾಧ್ಯ: ಆತ್ಮವನ್ನು ಕೊಲ್ಲಲಾಗದು ಎಂದು ಕಠ ಮತ್ತು ಗೀತೆ ಎರಡೂ ವಿಸ್ತಾರವಾಗಿ ಹೇಳುತ್ತವೆ. ಆದ್ದರಿಂದ ಆ ಪದದ ಅರ್ಥ ಬೇರೆಯದೇ ಇರಬೇಕು, ಮತ್ತು ಶಂಕರರ ಓದೇ ಸಹಜವಾದದ್ದು — ಆತ್ಮಘಾತಕನೆಂದರೆ ಆತ್ಮವನ್ನು ನಾಶಮಾಡಿದವನಲ್ಲ, ಆತ್ಮವೇ ಇಲ್ಲವೆಂಬಂತೆ ಬದುಕಿದವನು. ಇಲ್ಲಿ ಕೊಲ್ಲಲ್ಪಡುವುದು ಇರುವಿಕೆಯಲ್ಲ, ಪ್ರಸ್ತುತತೆ.\n\nಮುಂದಿನದಕ್ಕೆ ಇದು ಮುಖ್ಯ. ಈ ಮರೆಮಾಚುವಿಕೆ ತಾನೇ ಮಾಡಿಕೊಂಡದ್ದಾದ್ದರಿಂದ ಅದನ್ನು ಪರಿಹರಿಸಬಹುದು; ಇಲ್ಲದಿದ್ದರೆ ಉಳಿದ ಹದಿನೈದು ಶ್ಲೋಕಗಳಿಗೆ ಅರ್ಥವೇ ಇರುತ್ತಿರಲಿಲ್ಲ. ರಾಲ್ಫ್ ಗ್ರಿಫಿತ್ ಈ ಶ್ಲೋಕವನ್ನು ಮುಂದಿನ ಫಲಕ್ಕಾಗಿ ಮಾಡುವ ಕರ್ಮಕ್ಕೆ — ಸತ್ಯಕ್ಕಾಗಿ ಅಲ್ಲ, ಸ್ವರ್ಗಕ್ಕಾಗಿ ಮಾಡುವ ಕರ್ಮಕ್ಕೆ — ನೇರವಾಗಿ ಜೋಡಿಸಿದರು, ಇದು ಎರಡನೆಯ ಶ್ಲೋಕದ ಅಂಟುವಿಕೆಯ ಎಚ್ಚರಿಕೆಗೆ ಮರಳಿ ಸೇರುತ್ತದೆ.",
    hi: "पाठ का सबसे कठोर श्लोक, और उसका बल एक ऐसे श्लेष से आता है जो अंग्रेज़ी में नहीं जाता।\n\n'असुर्य' का अर्थ है 'सूर्यहीन'। 'असुर्य' का अर्थ 'असुरों का' भी है। उपनिषद् दोनों का एक साथ प्रयोग करता है: वे लोक प्रकाशहीन हैं और आसुरी हैं, और ये दोनों एक ही वर्णन निकलते हैं। यहाँ अंधकार बाहर से दिया गया दंड नहीं। वह उस जीवन की दशा मात्र है जो इस संदर्भ के बिना बीता कि वह वस्तुतः क्या है।\n\n'आत्महन्' — आत्महंता — वही शब्द है जो चौंकाता है। शब्दशः लें तो यह असंभव है: आत्मा मारी नहीं जा सकती, यह कठ और गीता दोनों विस्तार से कहते हैं। अतः शब्द का अर्थ कुछ और होना चाहिए, और शंकर का पाठ ही स्वाभाविक है — आत्महंता वह नहीं जिसने आत्मा को नष्ट किया, बल्कि वह जो ऐसे जिया मानो वह है ही नहीं। यहाँ जो मारा जाता है वह सत्ता नहीं, प्रासंगिकता है।\n\nआगे के लिए यह महत्वपूर्ण है। चूँकि यह आवरण स्वयं ओढ़ा हुआ है, इसे हटाया जा सकता है; अन्यथा शेष पंद्रह श्लोक निरर्थक होते। रैल्फ़ ग्रिफ़िथ ने इस श्लोक को विशेष रूप से भावी फल के लिए किए गए कर्म से जोड़ा — सत्य के लिए नहीं, स्वर्ग के लिए किया गया कर्म — जो सीधे दूसरे श्लोक की चिपकने वाली चेतावनी पर लौटता है।",
  },

  "isha-4": {
    en: "The first of the paradox verses, and the paradox is precise rather than decorative.\n\nSpeed is a property of things that travel between two places. What is already at every place cannot be overtaken, and therefore appears infinitely fast while never moving at all. Anejat — unmoving — and manaso javīyaḥ — swifter than mind — are not in tension once you see that motion has been ruled out as a category rather than assigned a value.\n\nThe line about the senses is sharper than it looks. They 'could not overtake It, for It ran ahead' — pūrvam arṣat. The senses arrive late by definition, not by misfortune: they set out to find the very thing that is doing the finding. Every act of looking presupposes what it is looking for. This is the Kena Upaniṣad's argument in compressed form — the eye of the eye, the mind of the mind.\n\nThe final line grounds the abstraction in cosmology. Mātariśvan, the cosmic wind, supports the waters — but 'in It', tasmin. The still centre is what permits the movement to happen at all. Immobility here is not inertness; it is the condition of every motion, the way a stage does not move so that the play can.",
    kn: "ವಿರೋಧಾಭಾಸದ ಶ್ಲೋಕಗಳಲ್ಲಿ ಮೊದಲನೆಯದು, ಮತ್ತು ಈ ವಿರೋಧಾಭಾಸ ಅಲಂಕಾರವಲ್ಲ, ನಿಖರವಾದದ್ದು.\n\nವೇಗವೆಂಬುದು ಎರಡು ಸ್ಥಳಗಳ ನಡುವೆ ಸಂಚರಿಸುವ ವಸ್ತುವಿನ ಗುಣ. ಈಗಾಗಲೇ ಎಲ್ಲ ಕಡೆ ಇರುವುದನ್ನು ಹಿಡಿಯಲಾಗದು, ಆದ್ದರಿಂದ ಅದು ಚಲಿಸದೆಯೇ ಅನಂತವೇಗವಾಗಿ ಕಾಣುತ್ತದೆ. 'ಅನೇಜತ್' — ಚಲಿಸದ್ದು — ಮತ್ತು 'ಮನಸೋ ಜವೀಯಃ' — ಮನಸ್ಸಿಗಿಂತ ವೇಗವಾದದ್ದು — ಇವೆರಡರ ನಡುವೆ ವಿರೋಧವಿಲ್ಲ, ಏಕೆಂದರೆ ಚಲನೆಗೆ ಒಂದು ಮೌಲ್ಯ ಕೊಡುವ ಬದಲು ಆ ಪರಿಕಲ್ಪನೆಯನ್ನೇ ಇಲ್ಲಿ ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ.\n\nಇಂದ್ರಿಯಗಳ ಕುರಿತ ಸಾಲು ಕಾಣುವುದಕ್ಕಿಂತ ತೀಕ್ಷ್ಣ. ಅವು 'ಅದನ್ನು ಹಿಡಿಯಲಾರವು, ಏಕೆಂದರೆ ಅದು ಮೊದಲೇ ಮುಂದೆ ಹೋಗಿತ್ತು' — 'ಪೂರ್ವಮರ್ಷತ್'. ಇಂದ್ರಿಯಗಳು ದುರದೃಷ್ಟದಿಂದಲ್ಲ, ಸ್ವಭಾವತಃ ತಡವಾಗಿ ತಲುಪುತ್ತವೆ: ಹುಡುಕುತ್ತಿರುವುದನ್ನೇ ಹುಡುಕಲು ಅವು ಹೊರಡುತ್ತವೆ. ಪ್ರತಿ ನೋಟವೂ ತಾನು ಹುಡುಕುತ್ತಿರುವುದನ್ನು ಈಗಾಗಲೇ ಊಹಿಸಿಕೊಂಡಿರುತ್ತದೆ. ಇದೇ ಕೇನೋಪನಿಷತ್ತಿನ ವಾದದ ಸಂಗ್ರಹ ರೂಪ — ಕಣ್ಣಿನ ಕಣ್ಣು, ಮನಸ್ಸಿನ ಮನಸ್ಸು.\n\nಕೊನೆಯ ಸಾಲು ಈ ಅಮೂರ್ತತೆಯನ್ನು ವಿಶ್ವರಚನೆಯಲ್ಲಿ ನೆಲೆಗೊಳಿಸುತ್ತದೆ. ವಿಶ್ವವಾಯುವಾದ ಮಾತರಿಶ್ವನು ಜಲಗಳನ್ನು ಧರಿಸುತ್ತಾನೆ — ಆದರೆ 'ತಸ್ಮಿನ್', ಅದರಲ್ಲಿಯೇ. ನಿಶ್ಚಲ ಕೇಂದ್ರವಿರುವುದರಿಂದಲೇ ಚಲನೆ ಸಾಧ್ಯ. ಇಲ್ಲಿ ನಿಶ್ಚಲತೆ ಜಡತೆಯಲ್ಲ; ಪ್ರತಿ ಚಲನೆಯ ಷರತ್ತು ಅದು — ನಾಟಕ ನಡೆಯಲೆಂದು ರಂಗಮಂಚ ಚಲಿಸದಿರುವಂತೆ.",
    hi: "विरोधाभास वाले श्लोकों में पहला, और यह विरोधाभास अलंकार नहीं, सटीक है।\n\nगति उस वस्तु का गुण है जो दो स्थानों के बीच चलती है। जो पहले से सर्वत्र है उसे पकड़ा नहीं जा सकता, इसलिए वह बिना चले अनंत वेग वाला प्रतीत होता है। 'अनेजत्' — अचल — और 'मनसो जवीयः' — मन से तीव्र — में कोई तनाव नहीं, क्योंकि यहाँ गति को कोई मान देने के बजाय उस श्रेणी को ही रद्द कर दिया गया है।\n\nइंद्रियों वाली पंक्ति दिखने से अधिक तीक्ष्ण है। वे 'उसे नहीं पा सकीं, क्योंकि वह पहले ही आगे निकल चुका था' — 'पूर्वमर्षत्'। इंद्रियाँ दुर्भाग्य से नहीं, स्वभाव से देर से पहुँचती हैं: वे उसी को खोजने निकलती हैं जो खोज रहा है। हर देखना उसी को पूर्वमान लेता है जिसे वह खोज रहा है। यही केनोपनिषद् का तर्क संक्षेप में है — आँख की आँख, मन का मन।\n\nअंतिम पंक्ति इस अमूर्तता को ब्रह्मांड-रचना में टिकाती है। विश्ववायु मातरिश्वा जल को धारण करता है — किंतु 'तस्मिन्', उसी में। स्थिर केंद्र के कारण ही गति संभव है। यहाँ अचलता जड़ता नहीं; वह हर गति की शर्त है — जैसे नाटक चले इसलिए रंगमंच नहीं चलता।",
  },

  "isha-5": {
    en: "Four contradictions in two lines, and not one of them is resolved. That refusal is the method.\n\nEach pair cancels a category the mind would otherwise use to file the Absolute away and stop thinking. It moves / it moves not cancels motion. Far / near cancels distance. Within / outside cancels containment. What survives the cancelling is not a description — you cannot picture what is left — but a direction of attention.\n\nNotice what is not done here. 'Far' and 'near' are not compromised into 'at a moderate distance'. Both are asserted fully and simultaneously. This is deliberate: distance is a relation that requires two things, and the entire argument of the Upaniṣad is that there are not two. Once the second term is gone the relation does not become small, it becomes inapplicable.\n\nThis is the technique later formalised as neti neti in the Bṛhadāraṇyaka — approaching by negation, not because the Absolute is a void but because every positive term brings a limit with it. Aurobindo read this verse as the text's clearest statement that the transcendent and the immanent are not two orders of being but one, described from two sides.",
    kn: "ಎರಡು ಸಾಲುಗಳಲ್ಲಿ ನಾಲ್ಕು ವಿರೋಧಗಳು, ಒಂದನ್ನೂ ಬಗೆಹರಿಸಿಲ್ಲ. ಈ ನಿರಾಕರಣೆಯೇ ವಿಧಾನ.\n\nಪ್ರತಿ ಜೋಡಿಯೂ, ಮನಸ್ಸು ಪರಬ್ರಹ್ಮವನ್ನು ಒಂದು ಕಡೆ ಇಟ್ಟು ಯೋಚನೆ ನಿಲ್ಲಿಸಲು ಬಳಸಬಹುದಾದ ಒಂದೊಂದು ಪರಿಕಲ್ಪನೆಯನ್ನು ರದ್ದುಗೊಳಿಸುತ್ತದೆ. ಚಲಿಸುತ್ತದೆ/ಚಲಿಸುವುದಿಲ್ಲ ಎಂಬುದು ಚಲನೆಯನ್ನು ರದ್ದುಗೊಳಿಸುತ್ತದೆ. ದೂರ/ಹತ್ತಿರ ಅಂತರವನ್ನು. ಒಳಗೆ/ಹೊರಗೆ ಆವರಣವನ್ನು. ಈ ರದ್ದತಿಯ ನಂತರ ಉಳಿಯುವುದು ವರ್ಣನೆಯಲ್ಲ — ಉಳಿದದ್ದನ್ನು ಚಿತ್ರಿಸಲಾಗದು — ಬದಲಾಗಿ ಗಮನದ ಒಂದು ದಿಕ್ಕು.\n\nಇಲ್ಲಿ ಏನು ಮಾಡಿಲ್ಲ ಎಂಬುದನ್ನು ಗಮನಿಸಿ. 'ದೂರ' ಮತ್ತು 'ಹತ್ತಿರ'ವನ್ನು 'ಮಧ್ಯಮ ಅಂತರ' ಎಂದು ರಾಜಿ ಮಾಡಿಲ್ಲ. ಎರಡನ್ನೂ ಪೂರ್ಣವಾಗಿ, ಏಕಕಾಲದಲ್ಲಿ ಹೇಳಲಾಗಿದೆ. ಇದು ಉದ್ದೇಶಪೂರ್ವಕ: ಅಂತರವೆಂಬುದು ಎರಡು ವಸ್ತುಗಳನ್ನು ಬೇಡುವ ಸಂಬಂಧ, ಮತ್ತು ಎರಡಿಲ್ಲ ಎಂಬುದೇ ಉಪನಿಷತ್ತಿನ ಇಡೀ ವಾದ. ಎರಡನೆಯ ಪದ ಹೋದ ಮೇಲೆ ಆ ಸಂಬಂಧ ಚಿಕ್ಕದಾಗುವುದಿಲ್ಲ, ಅನ್ವಯಿಸದಂತಾಗುತ್ತದೆ.\n\nಇದೇ ತಂತ್ರವು ಬೃಹದಾರಣ್ಯಕದಲ್ಲಿ 'ನೇತಿ ನೇತಿ' ಎಂದು ಸೂತ್ರರೂಪ ಪಡೆಯುತ್ತದೆ — ನಿಷೇಧದಿಂದ ಸಮೀಪಿಸುವುದು; ಪರಬ್ರಹ್ಮ ಶೂನ್ಯವೆಂದಲ್ಲ, ಪ್ರತಿಯೊಂದು ವಿಧ್ಯಾತ್ಮಕ ಪದವೂ ತನ್ನೊಂದಿಗೆ ಒಂದು ಮಿತಿಯನ್ನು ತರುತ್ತದೆಂದು. ಅತೀತ ಮತ್ತು ಅಂತರ್ಯಾಮಿ ಎರಡು ಬೇರೆ ಸ್ತರಗಳಲ್ಲ, ಎರಡು ಬದಿಗಳಿಂದ ವರ್ಣಿಸಿದ ಒಂದೇ ಎಂಬುದಕ್ಕೆ ಇದೇ ಪಠ್ಯದ ಸ್ಪಷ್ಟ ಹೇಳಿಕೆಯೆಂದು ಅರವಿಂದರು ಓದಿದರು.",
    hi: "दो पंक्तियों में चार विरोध, और एक भी सुलझाया नहीं गया। यही इनकार ही विधि है।\n\nप्रत्येक युग्म उस श्रेणी को रद्द करता है जिससे मन परब्रह्म को कहीं रखकर सोचना बंद कर देता। चलता है/नहीं चलता — गति रद्द। दूर/निकट — दूरी रद्द। भीतर/बाहर — आवरण रद्द। इस रद्दीकरण के बाद जो बचता है वह वर्णन नहीं — बचे हुए की कल्पना नहीं की जा सकती — बल्कि ध्यान की एक दिशा है।\n\nध्यान दें कि यहाँ क्या नहीं किया गया। 'दूर' और 'निकट' को 'मध्यम दूरी' में समझौता नहीं किया गया। दोनों पूर्णतः और एक साथ कहे गए हैं। यह जानबूझकर है: दूरी वह संबंध है जिसके लिए दो चाहिए, और उपनिषद् का सारा तर्क यही है कि दो हैं ही नहीं। दूसरा पद हट जाने पर वह संबंध छोटा नहीं होता, अप्रयोज्य हो जाता है।\n\nयही युक्ति बृहदारण्यक में 'नेति नेति' के रूप में सूत्रबद्ध होती है — निषेध से पहुँचना; इसलिए नहीं कि परब्रह्म शून्य है, बल्कि इसलिए कि हर विधेय पद अपने साथ एक सीमा लाता है। अरविंद ने इस श्लोक को पाठ का सबसे स्पष्ट कथन माना कि अतीत और अंतर्यामी सत्ता के दो स्तर नहीं, दो ओर से वर्णित एक ही हैं।",
  },

  "isha-6": {
    en: "The turn from metaphysics to conduct, and it happens inside a single word.\n\nVijugupsate means to recoil, to feel revulsion, to want to hide from. The verse does not say that such a person overcomes disgust by effort or discipline. It says the seeing removes the possibility. Once the other is no longer other there is nothing left to recoil from — not because one has become tolerant but because the object of intolerance has dissolved.\n\nThe two directions are given exactly equal weight, and this is the verse's real precision. All beings in the Self: that alone would collapse into absorption, the world swallowed by the subject. The Self in all beings: that alone would be pantheism, the subject spread thin across objects. Held together, neither collapse happens, and what emerges is an ethics that needs no rule. Nothing is prohibited here. Prohibition has simply become unnecessary.\n\nAnupaśyati is worth noting too: not paśyati, 'sees', but anupaśyati, 'goes on seeing', sees along, sees continuously. This is not a moment of insight to be had once. It is a way of looking that is sustained, and the verb form quietly makes that the requirement.",
    kn: "ತತ್ತ್ವಶಾಸ್ತ್ರದಿಂದ ನಡವಳಿಕೆಗೆ ತಿರುವು, ಮತ್ತು ಅದು ಒಂದೇ ಪದದ ಒಳಗೆ ನಡೆಯುತ್ತದೆ.\n\n'ವಿಜುಗುಪ್ಸತೇ' ಎಂದರೆ ಹಿಂಜರಿಯುವುದು, ಅಸಹ್ಯಪಡುವುದು, ಮರೆಯಾಗಬಯಸುವುದು. ಅಂಥವನು ಪ್ರಯತ್ನದಿಂದ ಅಥವಾ ಶಿಸ್ತಿನಿಂದ ಅಸಹ್ಯವನ್ನು ಗೆಲ್ಲುತ್ತಾನೆಂದು ಶ್ಲೋಕ ಹೇಳುವುದಿಲ್ಲ. ಆ ದರ್ಶನವೇ ಆ ಸಾಧ್ಯತೆಯನ್ನು ತೆಗೆದುಹಾಕುತ್ತದೆ ಎನ್ನುತ್ತದೆ. ಬೇರೆಯವನು ಬೇರೆಯಲ್ಲವಾದ ಮೇಲೆ ಹಿಂಜರಿಯುವುದಕ್ಕೆ ಏನೂ ಉಳಿಯುವುದಿಲ್ಲ — ಸಹಿಷ್ಣುತೆ ಬೆಳೆದದ್ದರಿಂದಲ್ಲ, ಅಸಹಿಷ್ಣುತೆಯ ವಿಷಯವೇ ಕರಗಿಹೋದದ್ದರಿಂದ.\n\nಎರಡು ದಿಕ್ಕುಗಳಿಗೂ ನಿಖರವಾಗಿ ಸಮಾನ ತೂಕ ಕೊಟ್ಟಿರುವುದೇ ಈ ಶ್ಲೋಕದ ನಿಜವಾದ ಸೂಕ್ಷ್ಮತೆ. ಆತ್ಮದಲ್ಲಿ ಸಮಸ್ತ ಭೂತಗಳು: ಅಷ್ಟೇ ಇದ್ದರೆ ಅದು ಲಯವಾಗುತ್ತಿತ್ತು, ಜಗತ್ತನ್ನು ವಿಷಯಿ ನುಂಗಿಬಿಡುತ್ತಿತ್ತು. ಸಮಸ್ತ ಭೂತಗಳಲ್ಲಿ ಆತ್ಮ: ಅಷ್ಟೇ ಇದ್ದರೆ ಅದು ಸರ್ವೇಶ್ವರವಾದವಾಗುತ್ತಿತ್ತು, ವಿಷಯಿ ವಸ್ತುಗಳಲ್ಲಿ ತೆಳುವಾಗಿ ಹರಡಿಹೋಗುತ್ತಿದ್ದ. ಎರಡನ್ನೂ ಜೊತೆಗಿಟ್ಟಾಗ ಯಾವ ಕುಸಿತವೂ ಆಗುವುದಿಲ್ಲ, ಮತ್ತು ನಿಯಮವೇ ಬೇಡದ ನೀತಿ ಹುಟ್ಟುತ್ತದೆ. ಇಲ್ಲಿ ಯಾವುದನ್ನೂ ನಿಷೇಧಿಸಿಲ್ಲ. ನಿಷೇಧವೇ ಅನಗತ್ಯವಾಗಿಬಿಟ್ಟಿದೆ.\n\n'ಅನುಪಶ್ಯತಿ' ಎಂಬ ಪದವೂ ಗಮನಾರ್ಹ: 'ಪಶ್ಯತಿ' ಅಂದರೆ 'ನೋಡುತ್ತಾನೆ' ಅಲ್ಲ, 'ಅನುಪಶ್ಯತಿ' ಅಂದರೆ 'ನೋಡುತ್ತಲೇ ಇರುತ್ತಾನೆ', ನಿರಂತರವಾಗಿ ನೋಡುತ್ತಾನೆ. ಇದು ಒಮ್ಮೆ ಪಡೆದು ಮುಗಿಸುವ ಒಳನೋಟವಲ್ಲ. ಇದು ಸತತವಾಗಿ ಉಳಿಸಿಕೊಳ್ಳಬೇಕಾದ ನೋಟದ ಕ್ರಮ, ಮತ್ತು ಕ್ರಿಯಾರೂಪವೇ ಅದನ್ನು ಸದ್ದಿಲ್ಲದೆ ಷರತ್ತಾಗಿಸುತ್ತದೆ.",
    hi: "तत्त्व से आचरण की ओर मोड़, और वह एक ही शब्द के भीतर घटित होता है।\n\n'विजुगुप्सते' का अर्थ है सिकुड़ना, घृणा करना, छिप जाना चाहना। श्लोक यह नहीं कहता कि ऐसा व्यक्ति प्रयत्न या अनुशासन से घृणा जीत लेता है। वह कहता है कि वह दर्शन उस संभावना को ही समाप्त कर देता है। जब दूसरा दूसरा रहा ही नहीं, तो सिकुड़ने के लिए कुछ बचता ही नहीं — सहिष्णुता बढ़ने से नहीं, बल्कि असहिष्णुता का विषय ही घुल जाने से।\n\nदोनों दिशाओं को ठीक समान भार देना ही इस श्लोक की असली सूक्ष्मता है। आत्मा में समस्त भूत: अकेला यह लय में ढह जाता, विषयी जगत् को निगल लेता। समस्त भूतों में आत्मा: अकेला यह सर्वेश्वरवाद होता, विषयी वस्तुओं पर पतला फैल जाता। दोनों साथ रहने पर कोई ढहाव नहीं होता, और वह नीति जन्म लेती है जिसे नियम की आवश्यकता नहीं। यहाँ कुछ भी वर्जित नहीं। वर्जना ही अनावश्यक हो गई।\n\n'अनुपश्यति' भी ध्यान देने योग्य है: 'पश्यति' अर्थात् 'देखता है' नहीं, 'अनुपश्यति' अर्थात् 'देखता रहता है', निरंतर देखता है। यह एक बार पा लेने वाली अंतर्दृष्टि नहीं। यह देखने की वह रीति है जो बनी रहनी चाहिए, और क्रियारूप चुपचाप उसी को शर्त बना देता है।",
  },

  "isha-7": {
    en: "The consequence of verse 6, and the grammar carries the argument.\n\nTwo questions are asked and neither expects an answer: ko mohaḥ, kaḥ śokaḥ — what delusion, what sorrow? The form matters enormously. The text does not say that such a person's sorrow is lessened, or borne better, or outweighed. It asks what sorrow could even be, for someone in that position. The category has lost its footing.\n\nWhy it loses its footing is worth spelling out. Grief requires a gap between what is and what one wanted to be. Delusion requires a second thing for the first to be mistaken as. Remove twoness and neither has anywhere to stand — not suppressed, not transcended, simply without the conditions that made them possible.\n\nThe tense is the detail most readers pass over. Ātmaivābhūt — 'has become the Self', a past form, not 'will become'. Nothing is under construction. The verse describes a recognition of what was already the case, which is why the Upaniṣad can present liberation as removal rather than achievement. Śaṅkara builds heavily on exactly this point: mokṣa is not produced, it is uncovered.",
    kn: "ಆರನೆಯ ಶ್ಲೋಕದ ಪರಿಣಾಮ, ಮತ್ತು ವ್ಯಾಕರಣವೇ ವಾದವನ್ನು ಹೊತ್ತಿದೆ.\n\nಎರಡು ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಲಾಗಿದೆ, ಎರಡೂ ಉತ್ತರ ನಿರೀಕ್ಷಿಸುವುದಿಲ್ಲ: 'ಕೋ ಮೋಹಃ, ಕಃ ಶೋಕಃ' — ಯಾವ ಮೋಹ, ಯಾವ ಶೋಕ? ಈ ರೂಪ ಅತ್ಯಂತ ಮುಖ್ಯ. ಅಂಥವನ ಶೋಕ ಕಡಿಮೆಯಾಗುತ್ತದೆ, ಅಥವಾ ಸಹಿಸಲು ಸುಲಭವಾಗುತ್ತದೆ ಎಂದು ಪಠ್ಯ ಹೇಳುವುದಿಲ್ಲ. ಆ ಸ್ಥಿತಿಯಲ್ಲಿರುವವನಿಗೆ ಶೋಕವೆಂಬುದು ಏನಾಗಿರಲು ಸಾಧ್ಯ ಎಂದು ಕೇಳುತ್ತದೆ. ಆ ಪರಿಕಲ್ಪನೆಗೇ ನೆಲೆ ಇಲ್ಲವಾಗಿದೆ.\n\nಅದಕ್ಕೆ ನೆಲೆ ಏಕೆ ಇಲ್ಲವಾಯಿತೆಂದು ಬಿಡಿಸಿ ಹೇಳುವುದು ಯೋಗ್ಯ. ಶೋಕಕ್ಕೆ ಇರುವುದಕ್ಕೂ ಬಯಸಿದ್ದಕ್ಕೂ ನಡುವೆ ಅಂತರ ಬೇಕು. ಮೋಹಕ್ಕೆ ಮೊದಲನೆಯದನ್ನು ತಪ್ಪಾಗಿ ತಿಳಿಯಲು ಎರಡನೆಯದೊಂದು ಬೇಕು. ದ್ವಿತ್ವವನ್ನು ತೆಗೆದರೆ ಎರಡಕ್ಕೂ ನಿಲ್ಲಲು ಜಾಗವಿಲ್ಲ — ಅವನ್ನು ಅದುಮಿಲ್ಲ, ಮೀರಿಲ್ಲ, ಅವನ್ನು ಸಾಧ್ಯಗೊಳಿಸಿದ್ದ ಷರತ್ತುಗಳೇ ಇಲ್ಲವಾಗಿವೆ.\n\nಹೆಚ್ಚಿನ ಓದುಗರು ದಾಟಿಹೋಗುವ ವಿವರವೆಂದರೆ ಕಾಲ. 'ಆತ್ಮೈವಾಭೂತ್' — 'ಆತ್ಮವೇ ಆಗಿಬಿಟ್ಟಿದೆ', ಇದು ಭೂತಕಾಲ, 'ಆಗುತ್ತದೆ' ಅಲ್ಲ. ಏನೂ ನಿರ್ಮಾಣವಾಗುತ್ತಿಲ್ಲ. ಈಗಾಗಲೇ ಹಾಗಿದ್ದುದನ್ನು ಗುರುತಿಸುವುದನ್ನು ಶ್ಲೋಕ ವರ್ಣಿಸುತ್ತದೆ, ಆದ್ದರಿಂದಲೇ ಉಪನಿಷತ್ತು ಮೋಕ್ಷವನ್ನು ಸಾಧನೆಯಲ್ಲ, ತೆಗೆದುಹಾಕುವಿಕೆಯೆಂದು ಮಂಡಿಸಬಲ್ಲದು. ಶಂಕರರು ನಿಖರವಾಗಿ ಇದೇ ಅಂಶದ ಮೇಲೆ ಬಹಳಷ್ಟನ್ನು ಕಟ್ಟುತ್ತಾರೆ: ಮೋಕ್ಷವು ಉತ್ಪಾದಿಸಲ್ಪಡುವುದಿಲ್ಲ, ಅನಾವರಣಗೊಳ್ಳುತ್ತದೆ.",
    hi: "छठे श्लोक का परिणाम, और व्याकरण ही तर्क को उठाए हुए है।\n\nदो प्रश्न पूछे गए हैं और दोनों उत्तर की अपेक्षा नहीं करते: 'को मोहः, कः शोकः' — कौन-सा मोह, कौन-सा शोक? यह रूप अत्यंत महत्वपूर्ण है। पाठ यह नहीं कहता कि ऐसे व्यक्ति का शोक घट जाता है, या सहना आसान हो जाता है। वह पूछता है कि उस स्थिति में शोक हो ही क्या सकता है। उस श्रेणी का आधार जाता रहा।\n\nआधार क्यों जाता रहा, यह खोलकर कहना उचित है। शोक के लिए जो है और जो चाहा था, उनके बीच अंतर चाहिए। मोह के लिए पहले को जिस रूप में गलत समझा जाए, वह दूसरा चाहिए। द्वैत हटाइए, दोनों के खड़े होने की जगह नहीं बचती — वे दबाए नहीं गए, लाँघे नहीं गए; बस वे शर्तें ही नहीं रहीं जिनसे वे संभव थे।\n\nअधिकांश पाठक जिस विवरण को छोड़ जाते हैं वह काल है। 'आत्मैवाभूत्' — 'आत्मा ही हो चुका', यह भूतकाल है, 'हो जाएगा' नहीं। कुछ भी निर्मित नहीं हो रहा। श्लोक उस पहचान का वर्णन करता है जो पहले से ही तथ्य थी, इसीलिए उपनिषद् मोक्ष को उपलब्धि नहीं, आवरण-हटाव के रूप में रख पाता है। शंकर ठीक इसी बिंदु पर बहुत कुछ खड़ा करते हैं: मोक्ष उत्पन्न नहीं होता, अनावृत होता है।",
  },

  "isha-8": {
    en: "The verse works by stripping, and the order of the stripping is the argument.\n\nAkāyam — bodiless. Avraṇam — without wound. Asnāviram — without sinew. Apāpaviddham — unpierced by evil. Each negation removes something that could be damaged, and what remains cannot be harmed for the simple reason that there is nothing in it to break. This is not a claim about exceptional toughness. It is a claim about what kind of thing the Self is: not a durable object but not an object at all.\n\nOnly then do the positive terms arrive, and they are cognitive rather than physical: kavi, seer; manīṣī, thinker; paribhūḥ, all-encompassing; svayambhū, self-existent. Kavi is worth pausing on — in Vedic usage it does not mean poet in our sense but the one who sees, the seer whose seeing is itself the making.\n\nThe final clause is why the Upaniṣad can stay calm about the world's evident disorder. Things were arranged yāthātathyataḥ — 'according to what actually is' — śāśvatībhyaḥ samābhyaḥ, through years without beginning. The ordering is not pending, not promised, not a project awaiting completion. It is already the case, and what looks like disorder is a failure of view rather than a failure of arrangement.",
    kn: "ಈ ಶ್ಲೋಕ ಕಳೆಯುವ ಮೂಲಕ ಕೆಲಸ ಮಾಡುತ್ತದೆ, ಮತ್ತು ಕಳೆಯುವ ಕ್ರಮವೇ ವಾದ.\n\n'ಅಕಾಯಮ್' — ದೇಹರಹಿತ. 'ಅವ್ರಣಮ್' — ವ್ರಣರಹಿತ. 'ಅಸ್ನಾವಿರಮ್' — ಸ್ನಾಯುರಹಿತ. 'ಅಪಾಪವಿದ್ಧಮ್' — ಪಾಪದಿಂದ ಅಭೇದ್ಯ. ಪ್ರತಿ ನಿಷೇಧವೂ ಹಾನಿಗೊಳಗಾಗಬಲ್ಲ ಒಂದೊಂದನ್ನು ತೆಗೆದುಹಾಕುತ್ತದೆ, ಮತ್ತು ಉಳಿದದ್ದಕ್ಕೆ ಹಾನಿಯಾಗದು — ಕಾರಣ ಸರಳ: ಅದರಲ್ಲಿ ಒಡೆಯುವಂಥದ್ದೇನೂ ಇಲ್ಲ. ಇದು ಅಸಾಧಾರಣ ಗಟ್ಟಿತನದ ಹೇಳಿಕೆಯಲ್ಲ. ಆತ್ಮ ಯಾವ ಬಗೆಯ ವಸ್ತು ಎಂಬುದರ ಹೇಳಿಕೆ: ಬಾಳಿಕೆ ಬರುವ ವಸ್ತುವಲ್ಲ, ವಸ್ತುವೇ ಅಲ್ಲ.\n\nಆಮೇಲೆಯೇ ವಿಧ್ಯಾತ್ಮಕ ಪದಗಳು ಬರುತ್ತವೆ, ಮತ್ತು ಅವು ಭೌತಿಕವಲ್ಲ, ಜ್ಞಾನಾತ್ಮಕ: 'ಕವಿ' — ದ್ರಷ್ಟಾ; 'ಮನೀಷೀ' — ಚಿಂತಕ; 'ಪರಿಭೂಃ' — ಸರ್ವವ್ಯಾಪಿ; 'ಸ್ವಯಂಭೂಃ' — ತಾನಾಗಿಯೇ ಇರುವವನು. 'ಕವಿ' ಎಂಬಲ್ಲಿ ನಿಲ್ಲುವುದು ಯೋಗ್ಯ — ವೈದಿಕ ಬಳಕೆಯಲ್ಲಿ ಅದು ನಮ್ಮ ಅರ್ಥದ ಕವಿಯಲ್ಲ, ನೋಡುವವನು, ಯಾರ ನೋಟವೇ ರಚನೆಯೋ ಆ ದ್ರಷ್ಟಾ.\n\nಜಗತ್ತಿನ ಸ್ಪಷ್ಟ ಅವ್ಯವಸ್ಥೆಯ ಬಗ್ಗೆ ಉಪನಿಷತ್ತು ಶಾಂತವಾಗಿರಲು ಕೊನೆಯ ಭಾಗವೇ ಕಾರಣ. ವಸ್ತುಗಳನ್ನು 'ಯಾಥಾತಥ್ಯತಃ' — ವಾಸ್ತವವಾಗಿ ಇರುವಂತೆಯೇ — 'ಶಾಶ್ವತೀಭ್ಯಃ ಸಮಾಭ್ಯಃ', ಆದಿಯಿಲ್ಲದ ವರ್ಷಗಳಿಂದ ವಿಧಿಸಲಾಗಿದೆ. ಆ ವ್ಯವಸ್ಥೆ ಬಾಕಿಯಿಲ್ಲ, ವಾಗ್ದಾನವಲ್ಲ, ಪೂರ್ಣಗೊಳ್ಳಬೇಕಾದ ಯೋಜನೆಯಲ್ಲ. ಅದು ಈಗಾಗಲೇ ಹಾಗಿದೆ, ಮತ್ತು ಅವ್ಯವಸ್ಥೆಯಂತೆ ಕಾಣುವುದು ವ್ಯವಸ್ಥೆಯ ಸೋಲಲ್ಲ, ನೋಟದ ಸೋಲು.",
    hi: "यह श्लोक घटाकर काम करता है, और घटाने का क्रम ही तर्क है।\n\n'अकायम्' — अशरीरी। 'अव्रणम्' — व्रणरहित। 'अस्नाविरम्' — स्नायुरहित। 'अपापविद्धम्' — पाप से अभेद्य। प्रत्येक निषेध उस एक वस्तु को हटाता है जो क्षतिग्रस्त हो सकती थी, और जो शेष रहता है उसे हानि नहीं पहुँच सकती — कारण सरल है: उसमें टूटने योग्य कुछ है ही नहीं। यह असाधारण दृढ़ता का दावा नहीं। यह इस बात का दावा है कि आत्मा किस प्रकार की वस्तु है: टिकाऊ वस्तु नहीं, वस्तु ही नहीं।\n\nतभी विधेय पद आते हैं, और वे भौतिक नहीं, ज्ञानात्मक हैं: 'कवि' — द्रष्टा; 'मनीषी' — चिंतक; 'परिभूः' — सर्वव्यापी; 'स्वयंभूः' — स्वयं से विद्यमान। 'कवि' पर रुकना उचित है — वैदिक प्रयोग में यह हमारे अर्थ का कवि नहीं, बल्कि वह जो देखता है, वह द्रष्टा जिसका देखना ही रचना है।\n\nजगत् की स्पष्ट अव्यवस्था पर उपनिषद् शांत क्यों रह पाता है, इसका कारण अंतिम अंश है। पदार्थों को 'याथातथ्यतः' — जैसा वस्तुतः है वैसा ही — 'शाश्वतीभ्यः समाभ्यः', अनादि वर्षों से विहित किया गया है। वह व्यवस्था लंबित नहीं, वचन नहीं, पूर्ण होने की प्रतीक्षा में कोई परियोजना नहीं। वह पहले से ही तथ्य है, और जो अव्यवस्था दिखती है वह व्यवस्था की विफलता नहीं, दृष्टि की विफलता है।",
  },
  "isha-9": {
    en: "The most startling verse in the text, because it condemns the devout reader more sharply than the ignorant one — and its whole difficulty lies in two words that do not mean what they usually mean.\n\nIn ordinary usage avidyā is ignorance and vidyā is knowledge. Here, on Śaṅkara's reading and the mainstream tradition after him, avidyā means ritual action — karma, works — and vidyā means meditative knowledge of the deities, upāsanā. So the target is not learning. It is exclusive attachment to either half.\n\nThe person who performs only rites is in darkness: their activity is aimed at results inside time. But the person who has knowledge and therefore despises rites is 'in greater darkness still', because their darkness arrives with the conviction of being enlightened. Nothing is harder to correct than an error that feels like insight.\n\nThe iva — 'as it were' — is doing careful work. It softens the comparison just enough to stop the verse hardening into a doctrine that knowledge is worse than ritual. The point is not a ranking. The point is that both, taken alone, fail.",
    kn: "ಪಠ್ಯದ ಅತ್ಯಂತ ಬೆಚ್ಚಿಬೀಳಿಸುವ ಶ್ಲೋಕ, ಏಕೆಂದರೆ ಅಜ್ಞಾನಿಗಿಂತ ಭಕ್ತ ಓದುಗನನ್ನೇ ಇದು ಹೆಚ್ಚು ಕಠಿಣವಾಗಿ ಖಂಡಿಸುತ್ತದೆ — ಮತ್ತು ಇದರ ಇಡೀ ಕಷ್ಟ ಸಾಮಾನ್ಯ ಅರ್ಥವನ್ನು ಕೊಡದ ಎರಡು ಪದಗಳಲ್ಲಿದೆ.\n\nಸಾಮಾನ್ಯ ಬಳಕೆಯಲ್ಲಿ 'ಅವಿದ್ಯಾ' ಎಂದರೆ ಅಜ್ಞಾನ, 'ವಿದ್ಯಾ' ಎಂದರೆ ಜ್ಞಾನ. ಇಲ್ಲಿ, ಶಂಕರರ ಓದಿನಲ್ಲಿ ಮತ್ತು ಅವರ ನಂತರದ ಮುಖ್ಯಧಾರೆಯಲ್ಲಿ, 'ಅವಿದ್ಯಾ' ಎಂದರೆ ಕರ್ಮಕಾಂಡ ಮತ್ತು 'ವಿದ್ಯಾ' ಎಂದರೆ ದೇವತೋಪಾಸನೆ. ಆದ್ದರಿಂದ ಗುರಿ ಜ್ಞಾನವಲ್ಲ. ಎರಡು ಅರ್ಧಗಳಲ್ಲಿ ಯಾವುದಾದರೂ ಒಂದಕ್ಕೆ ಮಾತ್ರ ಅಂಟಿಕೊಳ್ಳುವುದು.\n\nಕೇವಲ ಕರ್ಮ ಮಾಡುವವನು ಕತ್ತಲೆಯಲ್ಲಿದ್ದಾನೆ: ಅವನ ಚಟುವಟಿಕೆ ಕಾಲದೊಳಗಿನ ಫಲಗಳಿಗೆ ಗುರಿಯಿಟ್ಟಿದೆ. ಆದರೆ ಜ್ಞಾನವಿದೆಯೆಂದು ಕರ್ಮವನ್ನು ತಿರಸ್ಕರಿಸುವವನು 'ಅದಕ್ಕಿಂತಲೂ ಹೆಚ್ಚಿನ ಕತ್ತಲೆಯಲ್ಲಿ' ಇದ್ದಾನೆ, ಏಕೆಂದರೆ ಅವನ ಕತ್ತಲೆಯ ಜೊತೆಗೆ ತಾನು ಬೆಳಗಿದ್ದೇನೆಂಬ ನಂಬಿಕೆಯೂ ಬರುತ್ತದೆ. ಒಳನೋಟದಂತೆ ಭಾಸವಾಗುವ ತಪ್ಪನ್ನು ತಿದ್ದುವುದಕ್ಕಿಂತ ಕಠಿಣವಾದದ್ದು ಬೇರೊಂದಿಲ್ಲ.\n\n'ಇವ' ಎಂಬ ಪದ ಎಚ್ಚರಿಕೆಯ ಕೆಲಸ ಮಾಡುತ್ತಿದೆ. ಜ್ಞಾನವು ಕರ್ಮಕ್ಕಿಂತ ಕೆಟ್ಟದ್ದೆಂಬ ಸಿದ್ಧಾಂತವಾಗಿ ಈ ಶ್ಲೋಕ ಗಟ್ಟಿಯಾಗದಂತೆ ಅದು ಹೋಲಿಕೆಯನ್ನು ಸಾಕಷ್ಟು ಮೃದುಗೊಳಿಸುತ್ತದೆ. ಇಲ್ಲಿನ ಸಾರ ಶ್ರೇಣಿಯಲ್ಲ. ಎರಡೂ, ಒಂಟಿಯಾಗಿ ತೆಗೆದುಕೊಂಡರೆ, ಸೋಲುತ್ತವೆ ಎಂಬುದೇ ಸಾರ.",
    hi: "पाठ का सबसे चौंकाने वाला श्लोक, क्योंकि यह अज्ञानी से अधिक कठोरता से भक्त पाठक की भर्त्सना करता है — और इसकी सारी कठिनाई उन दो शब्दों में है जो अपना सामान्य अर्थ नहीं देते।\n\nसामान्य प्रयोग में 'अविद्या' अज्ञान है और 'विद्या' ज्ञान। यहाँ, शंकर के पाठ में और उनके बाद की मुख्यधारा में, 'अविद्या' का अर्थ कर्मकांड है और 'विद्या' का अर्थ देवोपासना। अतः लक्ष्य विद्या नहीं। लक्ष्य है दोनों में से किसी एक आधे से विशेष आसक्ति।\n\nजो केवल कर्म करता है वह अंधकार में है: उसकी क्रिया काल के भीतर के फलों पर लक्षित है। किंतु जो ज्ञान के बल पर कर्म को तुच्छ मानता है वह 'उससे भी अधिक अंधकार में' है, क्योंकि उसके अंधकार के साथ प्रबुद्ध होने का विश्वास भी आता है। जो त्रुटि अंतर्दृष्टि जैसी लगती है, उससे कठिन कुछ भी सुधारना नहीं।\n\n'इव' शब्द सावधानी का काम कर रहा है। वह तुलना को इतना नरम कर देता है कि यह श्लोक इस सिद्धांत में कठोर न हो जाए कि ज्ञान कर्म से बुरा है। यहाँ सार क्रम-निर्धारण नहीं। सार यह है कि दोनों, अकेले लिए जाने पर, विफल होते हैं।",
  },

  "isha-10": {
    en: "A verse about how a teaching travels, placed exactly where the reasoning becomes hardest.\n\nThe speaker makes no first-hand claim. Śuśruma — 'we have heard' — is from the same root that gives śruti its name, the whole category of revealed text. What is being offered is transmission, not invention, and the verse says so in the moment it would be most tempting to assert.\n\nThe content is deliberately withheld. 'One thing... another thing' — anyad eva, anyad — and no statement of what either thing is. This is not evasiveness. The withholding makes a point that a direct statement could not: the two produce genuinely different results, results that cannot be substituted for one another, and the first requirement is to stop conflating them. Verse 11 will then supply what this verse refuses to.\n\nDhīra is worth noting: not paṇḍita, not vidvān, but dhīra — the steady one, the person whose mind does not move. The authority being cited is not scholarly credential but a quality of attention.",
    kn: "ಬೋಧನೆ ಹೇಗೆ ಸಾಗಿಬರುತ್ತದೆ ಎಂಬುದರ ಶ್ಲೋಕ, ಮತ್ತು ತರ್ಕ ಅತ್ಯಂತ ಕಠಿಣವಾಗುವ ನಿಖರ ಸ್ಥಾನದಲ್ಲಿಯೇ ಇಡಲಾಗಿದೆ.\n\nವಕ್ತೃ ತನ್ನದೇ ಅನುಭವದ ಹಕ್ಕನ್ನು ಸಾಧಿಸುವುದಿಲ್ಲ. 'ಶುಶ್ರುಮ' — ನಾವು ಕೇಳಿದ್ದೇವೆ — ಇದೇ ಧಾತುವಿನಿಂದ 'ಶ್ರುತಿ' ಎಂಬ ಇಡೀ ವರ್ಗದ ಹೆಸರು ಬಂದದ್ದು. ಇಲ್ಲಿ ಕೊಡುತ್ತಿರುವುದು ಪರಂಪರೆಯ ಹಸ್ತಾಂತರ, ಸ್ವಂತ ಸೃಷ್ಟಿಯಲ್ಲ, ಮತ್ತು ಪ್ರತಿಪಾದಿಸಲು ಅತ್ಯಂತ ಪ್ರಲೋಭನೆಯಿರುವ ಗಳಿಗೆಯಲ್ಲಿಯೇ ಶ್ಲೋಕ ಇದನ್ನು ಹೇಳುತ್ತದೆ.\n\nವಿಷಯವನ್ನು ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಹೇಳಿಲ್ಲ. 'ಅನ್ಯದೇವ, ಅನ್ಯತ್' — ಒಂದು ಬೇರೆ, ಇನ್ನೊಂದು ಬೇರೆ — ಆದರೆ ಯಾವುದೆಂದು ಹೇಳಿಲ್ಲ. ಇದು ತಪ್ಪಿಸಿಕೊಳ್ಳುವಿಕೆಯಲ್ಲ. ನೇರ ಹೇಳಿಕೆ ಮಾಡಲಾಗದ ಒಂದು ಸಂಗತಿಯನ್ನು ಈ ತಡೆಹಿಡಿಯುವಿಕೆ ಮಾಡುತ್ತದೆ: ಆ ಎರಡೂ ನಿಜಕ್ಕೂ ಬೇರೆ ಬೇರೆ ಫಲ ಕೊಡುತ್ತವೆ, ಒಂದರ ಬದಲಿಗೆ ಇನ್ನೊಂದನ್ನು ಇಡಲಾಗದು, ಮತ್ತು ಮೊದಲ ಅಗತ್ಯ ಅವನ್ನು ಬೆರೆಸುವುದನ್ನು ನಿಲ್ಲಿಸುವುದು. ಈ ಶ್ಲೋಕ ನಿರಾಕರಿಸಿದ್ದನ್ನು ಹನ್ನೊಂದನೆಯದು ಕೊಡುತ್ತದೆ.\n\n'ಧೀರ' ಎಂಬ ಪದ ಗಮನಾರ್ಹ: 'ಪಂಡಿತ' ಅಲ್ಲ, 'ವಿದ್ವಾನ್' ಅಲ್ಲ, 'ಧೀರ' — ಸ್ಥಿರನಾದವನು, ಯಾರ ಮನಸ್ಸು ಕದಲುವುದಿಲ್ಲವೋ ಅವನು. ಇಲ್ಲಿ ಉಲ್ಲೇಖಿಸುತ್ತಿರುವ ಅಧಿಕಾರ ಪಾಂಡಿತ್ಯದ ಪ್ರಮಾಣಪತ್ರವಲ್ಲ, ಗಮನದ ಒಂದು ಗುಣ.",
    hi: "यह श्लोक इस बारे में है कि उपदेश कैसे चला आता है, और उसे ठीक वहाँ रखा गया है जहाँ तर्क सबसे कठिन होता है।\n\nवक्ता प्रत्यक्ष अनुभव का दावा नहीं करता। 'शुश्रुम' — हमने सुना — उसी धातु से है जिससे 'श्रुति' नाम, अर्थात् प्रकट पाठ की पूरी श्रेणी बनी। यहाँ जो दिया जा रहा है वह परंपरा का हस्तांतरण है, आविष्कार नहीं, और श्लोक यह ठीक उस क्षण कहता है जब प्रतिपादन का सबसे अधिक प्रलोभन होता।\n\nविषय जानबूझकर रोक लिया गया है। 'अन्यदेव, अन्यत्' — एक अलग, दूसरा अलग — किंतु कौन-सा, यह नहीं। यह टालमटोल नहीं। यह रोकना वह बात कहता है जो सीधा कथन नहीं कह सकता: दोनों वस्तुतः भिन्न फल देते हैं, एक के स्थान पर दूसरा नहीं रखा जा सकता, और पहली आवश्यकता है उन्हें मिलाना बंद करना। जो यह श्लोक नहीं देता, ग्यारहवाँ वही देगा।\n\n'धीर' ध्यान देने योग्य है: 'पंडित' नहीं, 'विद्वान्' नहीं, 'धीर' — स्थिर, जिसका मन नहीं हिलता। यहाँ जो अधिकार उद्धृत है वह विद्वत्ता का प्रमाणपत्र नहीं, ध्यान का एक गुण है।",
  },

  "isha-11": {
    en: "The resolution the whole text has been building toward, and it is a synthesis rather than a choice.\n\nRitual action carries one across death — avidyayā mṛtyuṃ tīrtvā. Read that carefully: works are not dismissed, they are given a specific and real function. They operate inside time and settle what belongs to time. Knowledge then gives what was never in time to begin with: vidyayāmṛtam aśnute.\n\nEach does what the other structurally cannot, which is why neither can be discarded. Saha — 'together' — is the pivot of the verse and of the Upaniṣad. Not one after the other, not one instead of the other, not one for beginners and one for the advanced. Both, held at once.\n\nThis is the same problem the Bhagavad Gītā spends eighteen chapters on, and it is worth noticing that the Gītā's answer has the same shape: not karma or jñāna but karma performed with the understanding that jñāna supplies. Aurobindo took this verse as proof that the Isha was arguing against the renunciate reading of its own opening — that verses 1 and 2 were never two paths for two kinds of person, but one instruction that requires both hands.",
    kn: "ಇಡೀ ಪಠ್ಯ ಸಾಗಿಬಂದ ಪರಿಹಾರ, ಮತ್ತು ಇದು ಆಯ್ಕೆಯಲ್ಲ, ಸಮನ್ವಯ.\n\nಕರ್ಮವು ಮೃತ್ಯುವನ್ನು ದಾಟಿಸುತ್ತದೆ — 'ಅವಿದ್ಯಯಾ ಮೃತ್ಯುಂ ತೀರ್ತ್ವಾ'. ಇದನ್ನು ಎಚ್ಚರಿಕೆಯಿಂದ ಓದಿ: ಕರ್ಮಗಳನ್ನು ತಳ್ಳಿಹಾಕಿಲ್ಲ, ಅವಕ್ಕೆ ನಿರ್ದಿಷ್ಟ ಮತ್ತು ನಿಜವಾದ ಕಾರ್ಯವನ್ನು ಕೊಡಲಾಗಿದೆ. ಅವು ಕಾಲದೊಳಗೆ ಕೆಲಸ ಮಾಡುತ್ತವೆ ಮತ್ತು ಕಾಲಕ್ಕೆ ಸೇರಿದ್ದನ್ನು ಇತ್ಯರ್ಥಗೊಳಿಸುತ್ತವೆ. ಆಮೇಲೆ ಜ್ಞಾನವು ಎಂದೂ ಕಾಲದೊಳಗೆ ಇಲ್ಲದಿದ್ದುದನ್ನು ಕೊಡುತ್ತದೆ: 'ವಿದ್ಯಯಾಽಮೃತಮಶ್ನುತೇ'.\n\nಒಂದು ಮಾಡಲಾಗದ್ದನ್ನು ಇನ್ನೊಂದು ಮಾಡುತ್ತದೆ, ಆದ್ದರಿಂದಲೇ ಯಾವುದನ್ನೂ ಬಿಡಲಾಗದು. 'ಸಹ' ಎಂಬುದೇ ಈ ಶ್ಲೋಕದ ಮತ್ತು ಇಡೀ ಉಪನಿಷತ್ತಿನ ಕೀಲು. ಒಂದಾದ ಮೇಲೆ ಇನ್ನೊಂದಲ್ಲ, ಒಂದರ ಬದಲಿಗೆ ಇನ್ನೊಂದಲ್ಲ, ಆರಂಭಿಕರಿಗೆ ಒಂದು ಮತ್ತು ಮುಂದುವರಿದವರಿಗೆ ಇನ್ನೊಂದೂ ಅಲ್ಲ. ಎರಡೂ, ಏಕಕಾಲದಲ್ಲಿ.\n\nಭಗವದ್ಗೀತೆಯು ಹದಿನೆಂಟು ಅಧ್ಯಾಯಗಳನ್ನು ಕಳೆಯುವುದು ಇದೇ ಸಮಸ್ಯೆಯ ಮೇಲೆ, ಮತ್ತು ಗೀತೆಯ ಉತ್ತರಕ್ಕೂ ಇದೇ ಆಕಾರವಿದೆ ಎಂಬುದು ಗಮನಾರ್ಹ: ಕರ್ಮವೋ ಜ್ಞಾನವೋ ಅಲ್ಲ, ಜ್ಞಾನ ಕೊಡುವ ತಿಳಿವಳಿಕೆಯೊಂದಿಗೆ ಮಾಡಿದ ಕರ್ಮ. ತನ್ನದೇ ಆರಂಭದ ಸಂನ್ಯಾಸ-ಓದಿನ ವಿರುದ್ಧ ಈಶಾವಾಸ್ಯ ವಾದಿಸುತ್ತಿತ್ತು ಎಂಬುದಕ್ಕೆ ಈ ಶ್ಲೋಕವೇ ಸಾಕ್ಷಿಯೆಂದು ಅರವಿಂದರು ತೆಗೆದುಕೊಂಡರು — ೧ ಮತ್ತು ೨ನೆಯ ಶ್ಲೋಕಗಳು ಎರಡು ಬಗೆಯ ವ್ಯಕ್ತಿಗಳಿಗೆ ಎರಡು ಮಾರ್ಗಗಳಾಗಿರಲಿಲ್ಲ, ಎರಡೂ ಕೈಗಳನ್ನು ಬೇಡುವ ಒಂದೇ ಉಪದೇಶವಾಗಿತ್ತು.",
    hi: "वही समाधान जिसकी ओर सारा पाठ बढ़ रहा था, और यह चुनाव नहीं, समन्वय है।\n\nकर्म मृत्यु के पार ले जाता है — 'अविद्यया मृत्युं तीर्त्वा'। इसे ध्यान से पढ़िए: कर्मों को खारिज नहीं किया गया, उन्हें एक विशिष्ट और वास्तविक कार्य दिया गया है। वे काल के भीतर काम करते हैं और जो काल का है उसे निपटाते हैं। फिर ज्ञान वह देता है जो कभी काल में था ही नहीं: 'विद्ययाऽमृतमश्नुते'।\n\nएक वह करता है जो दूसरा संरचनात्मक रूप से नहीं कर सकता, इसीलिए किसी को छोड़ा नहीं जा सकता। 'सह' — साथ — इस श्लोक की और पूरे उपनिषद् की धुरी है। एक के बाद दूसरा नहीं, एक के बदले दूसरा नहीं, आरंभिकों के लिए एक और प्रौढ़ों के लिए दूसरा भी नहीं। दोनों, एक साथ।\n\nभगवद्गीता अठारह अध्याय इसी समस्या पर लगाती है, और ध्यान देने योग्य है कि गीता के उत्तर का आकार भी यही है: कर्म या ज्ञान नहीं, बल्कि उस समझ के साथ किया गया कर्म जो ज्ञान देता है। अरविंद ने इस श्लोक को इस बात का प्रमाण माना कि ईशावास्य अपने ही आरंभ के संन्यास-पाठ के विरुद्ध तर्क कर रहा था — कि १ और २ कभी दो प्रकार के व्यक्तियों के लिए दो मार्ग नहीं थे, बल्कि एक ही उपदेश थे जिसे दोनों हाथ चाहिए।",
  },

  "isha-12": {
    en: "The structure of verse 9 returns with a new pair, and the repetition is itself the argument.\n\nWhere 9 balanced works against knowledge, 12 balances asambhūti — the unmanifest, the unborn ground — against sambhūti, becoming, the world that has come to be. Again both exclusive positions are condemned. Again the more refined-looking one is condemned harder.\n\nThat second point deserves emphasis, because it is aimed at a particular reader. Someone who has absorbed the first eleven verses has just learned to value the formless, the unmoving, the ground behind appearance. This verse catches that person as squarely as it catches the materialist. Preferring the unmanifest is still preferring one half.\n\nA textual note that matters here: this is the Kāṇva recension, which has eighteen verses. The Mādhyandina has seventeen and places these verses in a different order — its 9–11 are Kāṇva's 12–14 and vice versa. Since the two pairs are doing structurally identical work, the reordering does not change the argument, which is itself evidence that the pattern rather than the specific content is what the text is transmitting.",
    kn: "ಒಂಬತ್ತನೆಯ ಶ್ಲೋಕದ ರಚನೆ ಹೊಸ ಜೋಡಿಯೊಂದಿಗೆ ಮರಳುತ್ತದೆ, ಮತ್ತು ಈ ಪುನರಾವರ್ತನೆಯೇ ವಾದ.\n\nಒಂಬತ್ತನೆಯದು ಕರ್ಮ ಮತ್ತು ಜ್ಞಾನವನ್ನು ತೂಗಿದರೆ, ಹನ್ನೆರಡನೆಯದು 'ಅಸಂಭೂತಿ' — ಅವ್ಯಕ್ತ, ಹುಟ್ಟಿಲ್ಲದ ಮೂಲ — ಮತ್ತು 'ಸಂಭೂತಿ' — ಆಗುವಿಕೆ, ಆಗಿಬಂದ ಜಗತ್ತು — ಇವನ್ನು ತೂಗುತ್ತದೆ. ಇಲ್ಲಿಯೂ ಎರಡೂ ಏಕಪಕ್ಷೀಯ ನಿಲುವುಗಳು ಖಂಡಿಸಲ್ಪಡುತ್ತವೆ. ಇಲ್ಲಿಯೂ ಹೆಚ್ಚು ಸೂಕ್ಷ್ಮವಾಗಿ ಕಾಣುವುದೇ ಹೆಚ್ಚು ಕಠಿಣವಾಗಿ.\n\nಆ ಎರಡನೆಯ ಅಂಶಕ್ಕೆ ಒತ್ತು ಬೇಕು, ಏಕೆಂದರೆ ಅದು ಒಬ್ಬ ನಿರ್ದಿಷ್ಟ ಓದುಗನ ಮೇಲೆ ಗುರಿಯಿಟ್ಟಿದೆ. ಮೊದಲ ಹನ್ನೊಂದು ಶ್ಲೋಕಗಳನ್ನು ಜೀರ್ಣಿಸಿಕೊಂಡವನು ಈಗಷ್ಟೇ ನಿರಾಕಾರವನ್ನು, ನಿಶ್ಚಲವನ್ನು, ತೋರಿಕೆಯ ಹಿಂದಿನ ಆಧಾರವನ್ನು ಬೆಲೆಬಾಳುವಂತೆ ಕಲಿತಿದ್ದಾನೆ. ಈ ಶ್ಲೋಕ ಆ ವ್ಯಕ್ತಿಯನ್ನು ಭೌತವಾದಿಯಷ್ಟೇ ನೇರವಾಗಿ ಹಿಡಿಯುತ್ತದೆ. ಅವ್ಯಕ್ತವನ್ನು ಬಯಸುವುದೂ ಒಂದು ಅರ್ಧವನ್ನೇ ಬಯಸುವುದು.\n\nಇಲ್ಲಿ ಮುಖ್ಯವಾದ ಪಠ್ಯಸಂಬಂಧಿ ಟಿಪ್ಪಣಿ: ಇದು ಕಾಣ್ವ ಪಾಠ, ಇದರಲ್ಲಿ ಹದಿನೆಂಟು ಶ್ಲೋಕಗಳಿವೆ. ಮಾಧ್ಯಂದಿನ ಪಾಠದಲ್ಲಿ ಹದಿನೇಳಿವೆ ಮತ್ತು ಈ ಶ್ಲೋಕಗಳ ಕ್ರಮ ಬೇರೆ — ಅದರ ೯–೧೧ ಕಾಣ್ವದ ೧೨–೧೪, ಮತ್ತು ವ್ಯತಿರಿಕ್ತವಾಗಿಯೂ. ಎರಡೂ ಜೋಡಿಗಳು ರಚನಾತ್ಮಕವಾಗಿ ಒಂದೇ ಕೆಲಸ ಮಾಡುತ್ತಿರುವುದರಿಂದ ಈ ಕ್ರಮಬದಲಾವಣೆ ವಾದವನ್ನು ಬದಲಿಸುವುದಿಲ್ಲ — ಮತ್ತು ನಿರ್ದಿಷ್ಟ ವಿಷಯವಲ್ಲ, ಆ ಮಾದರಿಯೇ ಪಠ್ಯ ಹಸ್ತಾಂತರಿಸುತ್ತಿರುವುದು ಎಂಬುದಕ್ಕೆ ಇದೇ ಸಾಕ್ಷಿ.",
    hi: "नवें श्लोक की संरचना नए युग्म के साथ लौटती है, और यह पुनरावृत्ति ही तर्क है।\n\nजहाँ नवाँ कर्म और ज्ञान को तौलता है, वहाँ बारहवाँ 'असंभूति' — अव्यक्त, अजन्मा मूल — और 'संभूति' — होना, जो जगत् हो चुका — को तौलता है। यहाँ भी दोनों एकांगी पक्षों की भर्त्सना है। यहाँ भी जो अधिक सूक्ष्म दिखता है उसकी अधिक कठोर।\n\nउस दूसरी बात पर बल चाहिए, क्योंकि वह एक विशेष पाठक पर लक्षित है। जिसने पहले ग्यारह श्लोक आत्मसात् किए हैं, उसने अभी-अभी निराकार को, अचल को, प्रतीति के पीछे के आधार को मूल्यवान मानना सीखा है। यह श्लोक उस व्यक्ति को उतनी ही सीधाई से पकड़ता है जितनी भौतिकवादी को। अव्यक्त को वरीयता देना भी एक आधे को ही वरीयता देना है।\n\nयहाँ एक महत्वपूर्ण पाठ-संबंधी टिप्पणी: यह काण्व पाठ है, जिसमें अठारह श्लोक हैं। माध्यंदिन में सत्रह हैं और इन श्लोकों का क्रम भिन्न है — उसके ९–११ काण्व के १२–१४ हैं और इसके विपरीत भी। चूँकि दोनों युग्म संरचनात्मक रूप से एक ही काम कर रहे हैं, यह क्रम-परिवर्तन तर्क को नहीं बदलता — और यही प्रमाण है कि पाठ जो हस्तांतरित कर रहा है वह विशिष्ट विषय नहीं, वह प्रतिरूप है।",
  },

  "isha-13": {
    en: "Verse 10 repeated exactly, with the new pair substituted in, and the repetition is doing structural work rather than filling space.\n\nIt signals that this second problem is to be handled by the same method as the first — you already know what to do here, the text is saying, because you have just watched it done. And it hands authority back to the tradition at precisely the moment the reasoning is hardest to follow, which is a rhetorical choice worth noticing. The Upaniṣad does not claim to have solved the relation between being and non-being by argument. It reports what the steady ones said.\n\nVicacakṣire, 'they expounded, they made it clear', is a strong verb. Whatever the dhīras did, it was not gesturing at a mystery. Something was actually explained, and the explanation was passed down intact enough that the speaker can appeal to it.\n\nThe effect of placing 10 and 13 identically is to frame verses 11 and 14 as the two halves of one answer, delivered in the same voice, arrived at the same way.",
    kn: "ಹತ್ತನೆಯ ಶ್ಲೋಕವೇ ಹೊಸ ಜೋಡಿಯೊಂದಿಗೆ ಯಥಾವತ್ತಾಗಿ ಪುನರಾವರ್ತನೆಗೊಂಡಿದೆ, ಮತ್ತು ಈ ಪುನರಾವರ್ತನೆ ಜಾಗ ತುಂಬುವುದಲ್ಲ, ರಚನಾತ್ಮಕ ಕೆಲಸ ಮಾಡುತ್ತಿದೆ.\n\nಈ ಎರಡನೆಯ ಸಮಸ್ಯೆಯನ್ನೂ ಮೊದಲನೆಯದರ ವಿಧಾನದಿಂದಲೇ ಪರಿಹರಿಸಬೇಕೆಂದು ಅದು ಸೂಚಿಸುತ್ತದೆ — ಇಲ್ಲಿ ಏನು ಮಾಡಬೇಕೆಂದು ನಿಮಗೆ ಈಗಾಗಲೇ ಗೊತ್ತು, ಏಕೆಂದರೆ ಅದನ್ನು ಮಾಡುವುದನ್ನು ನೀವು ಈಗಷ್ಟೇ ನೋಡಿದ್ದೀರಿ ಎಂದು ಪಠ್ಯ ಹೇಳುತ್ತಿದೆ. ಮತ್ತು ತರ್ಕವನ್ನು ಅನುಸರಿಸುವುದು ಅತ್ಯಂತ ಕಠಿಣವಾಗುವ ನಿಖರ ಗಳಿಗೆಯಲ್ಲಿಯೇ ಅದು ಅಧಿಕಾರವನ್ನು ಪರಂಪರೆಗೆ ಹಿಂತಿರುಗಿಸುತ್ತದೆ, ಇದು ಗಮನಿಸಬೇಕಾದ ವಾಗ್ವಿಧಾನ. ಇರುವಿಕೆ ಮತ್ತು ಇಲ್ಲದಿರುವಿಕೆಯ ಸಂಬಂಧವನ್ನು ತಾನು ವಾದದಿಂದ ಬಗೆಹರಿಸಿದೆನೆಂದು ಉಪನಿಷತ್ತು ಹೇಳಿಕೊಳ್ಳುವುದಿಲ್ಲ. ಧೀರರು ಏನು ಹೇಳಿದರೆಂದು ವರದಿ ಮಾಡುತ್ತದೆ.\n\n'ವಿಚಚಕ್ಷಿರೇ' — 'ಅವರು ವಿವರಿಸಿದರು, ಸ್ಪಷ್ಟಗೊಳಿಸಿದರು' — ಇದೊಂದು ಬಲವಾದ ಕ್ರಿಯಾಪದ. ಆ ಧೀರರು ಏನೇ ಮಾಡಿರಲಿ, ಅದು ರಹಸ್ಯದತ್ತ ಕೈತೋರಿಸುವುದಾಗಿರಲಿಲ್ಲ. ನಿಜಕ್ಕೂ ಏನೋ ವಿವರಿಸಲ್ಪಟ್ಟಿತು, ಮತ್ತು ಆ ವಿವರಣೆ ವಕ್ತೃ ಅದನ್ನು ಆಶ್ರಯಿಸಬಲ್ಲಷ್ಟು ಅಖಂಡವಾಗಿ ಸಾಗಿಬಂತು.\n\n೧೦ ಮತ್ತು ೧೩ನ್ನು ಒಂದೇ ರೀತಿ ಇಟ್ಟದ್ದರ ಪರಿಣಾಮವೆಂದರೆ, ೧೧ ಮತ್ತು ೧೪ ಒಂದೇ ಉತ್ತರದ ಎರಡು ಅರ್ಧಗಳಾಗಿ, ಒಂದೇ ಧ್ವನಿಯಲ್ಲಿ, ಒಂದೇ ಮಾರ್ಗದಿಂದ ಬಂದವಾಗಿ ನಿಲ್ಲುತ್ತವೆ.",
    hi: "दसवाँ श्लोक ज्यों का त्यों दोहराया गया है, नए युग्म के साथ, और यह पुनरावृत्ति जगह भरना नहीं, संरचनात्मक काम है।\n\nयह संकेत देती है कि इस दूसरी समस्या को भी पहली वाली विधि से सुलझाना है — यहाँ क्या करना है यह तुम्हें पहले से पता है, क्योंकि तुमने अभी-अभी उसे होते देखा है, ऐसा पाठ कह रहा है। और वह ठीक उस क्षण अधिकार परंपरा को लौटा देता है जब तर्क का अनुसरण सबसे कठिन होता है, यह ध्यान देने योग्य वाक्-चयन है। उपनिषद् यह दावा नहीं करता कि उसने सत् और असत् के संबंध को तर्क से सुलझा लिया। वह बताता है कि धीरों ने क्या कहा।\n\n'विचचक्षिरे' — 'उन्होंने समझाया, स्पष्ट किया' — यह सशक्त क्रिया है। उन धीरों ने जो भी किया, वह किसी रहस्य की ओर इशारा भर नहीं था। वस्तुतः कुछ समझाया गया, और वह व्याख्या इतनी अखंड चली आई कि वक्ता उसका आश्रय ले सके।\n\n१० और १३ को एक-सा रखने का प्रभाव यह है कि ११ और १४ एक ही उत्तर के दो आधे बनकर खड़े होते हैं — एक ही स्वर में, एक ही मार्ग से आए हुए।",
  },

  "isha-14": {
    en: "The second synthesis, matching verse 11 exactly in form, and the parallel is the point.\n\nWhat passes away is precisely what carries one through death — vināśena mṛtyuṃ tīrtvā. This reads as paradox only if dissolution is taken as failure. Read the other way, dissolution is how the temporal completes itself: a thing that ends is a thing that has been fully what it was. Manifestation understood rightly is not a fall away from the absolute but its availability, the mode in which it can be met at all.\n\nAs in verse 11, saha holds the two together and refuses the reader an exit into either half.\n\nWith this the argument of the Upaniṣad is finished. Twice it has set up an opposition that every reader wants to resolve by choosing, and twice it has refused. What remains — verses 15 to 18 — is not further reasoning. It is what someone does once the reasoning is complete, which turns out to be prayer.",
    kn: "ಎರಡನೆಯ ಸಮನ್ವಯ, ಹನ್ನೊಂದನೆಯ ಶ್ಲೋಕದ ರೂಪಕ್ಕೆ ನಿಖರವಾಗಿ ಹೊಂದುತ್ತದೆ, ಮತ್ತು ಆ ಸಮಾನಾಂತರವೇ ಸಾರ.\n\nನಶಿಸಿಹೋಗುವುದೇ ಮೃತ್ಯುವನ್ನು ದಾಟಿಸುತ್ತದೆ — 'ವಿನಾಶೇನ ಮೃತ್ಯುಂ ತೀರ್ತ್ವಾ'. ಲಯವನ್ನು ಸೋಲೆಂದು ತೆಗೆದುಕೊಂಡರೆ ಮಾತ್ರ ಇದು ವಿರೋಧಾಭಾಸವಾಗಿ ಕಾಣುತ್ತದೆ. ಇನ್ನೊಂದು ರೀತಿ ಓದಿದರೆ, ಲಯವೆಂಬುದು ಕಾಲಿಕವಾದದ್ದು ತನ್ನನ್ನು ಪೂರ್ಣಗೊಳಿಸಿಕೊಳ್ಳುವ ಕ್ರಮ: ಮುಗಿಯುವ ವಸ್ತು ತಾನು ಏನಾಗಿತ್ತೋ ಅದನ್ನು ಪೂರ್ಣವಾಗಿ ಆಗಿ ಮುಗಿದ ವಸ್ತು. ಸರಿಯಾಗಿ ಅರ್ಥಮಾಡಿಕೊಂಡ ವ್ಯಕ್ತವಾಗುವಿಕೆ ಪರಬ್ರಹ್ಮದಿಂದ ಬಿದ್ದದ್ದಲ್ಲ, ಅದರ ಲಭ್ಯತೆ — ಅದನ್ನು ಎದುರುಗೊಳ್ಳಬಹುದಾದ ಏಕೈಕ ರೀತಿ.\n\nಹನ್ನೊಂದನೆಯದರಲ್ಲಿಯಂತೆ, 'ಸಹ' ಎರಡನ್ನೂ ಜೊತೆಗಿಟ್ಟು, ಯಾವುದೋ ಒಂದು ಅರ್ಧಕ್ಕೆ ತಪ್ಪಿಸಿಕೊಂಡು ಹೋಗುವುದನ್ನು ಓದುಗನಿಗೆ ನಿರಾಕರಿಸುತ್ತದೆ.\n\nಇದರೊಂದಿಗೆ ಉಪನಿಷತ್ತಿನ ವಾದ ಮುಗಿಯಿತು. ಎರಡು ಬಾರಿ ಅದು ಪ್ರತಿಯೊಬ್ಬ ಓದುಗನೂ ಆರಿಸಿಕೊಂಡು ಬಗೆಹರಿಸಬಯಸುವ ವಿರೋಧವನ್ನು ನಿಲ್ಲಿಸಿತು, ಮತ್ತು ಎರಡು ಬಾರಿಯೂ ನಿರಾಕರಿಸಿತು. ಉಳಿದದ್ದು — ೧೫ರಿಂದ ೧೮ — ಮತ್ತಷ್ಟು ತರ್ಕವಲ್ಲ. ತರ್ಕ ಮುಗಿದ ಮೇಲೆ ಮನುಷ್ಯ ಏನು ಮಾಡುತ್ತಾನೋ ಅದು, ಮತ್ತು ಅದು ಪ್ರಾರ್ಥನೆಯೆಂದು ತಿಳಿಯುತ್ತದೆ.",
    hi: "दूसरा समन्वय, ग्यारहवें श्लोक के रूप से ठीक मेल खाता, और यही समांतरता सार है।\n\nजो नष्ट होता है वही मृत्यु के पार ले जाता है — 'विनाशेन मृत्युं तीर्त्वा'। यह विरोधाभास तभी लगता है जब लय को विफलता माना जाए। दूसरी तरह पढ़ें तो लय वह रीति है जिससे कालिक स्वयं को पूर्ण करता है: जो वस्तु समाप्त होती है वह वह वस्तु है जो पूर्णतः वही हो चुकी जो वह थी। ठीक से समझी गई व्यक्तता परब्रह्म से पतन नहीं, उसकी सुलभता है — वही एक ढंग जिसमें उससे भेंट हो सकती है।\n\nग्यारहवें की भाँति, 'सह' दोनों को साथ थामे रखता है और पाठक को किसी एक आधे में भाग निकलने से रोकता है।\n\nइसके साथ उपनिषद् का तर्क पूरा हुआ। दो बार उसने वह विरोध खड़ा किया जिसे हर पाठक चुनकर सुलझाना चाहता है, और दो बार इनकार किया। जो शेष है — १५ से १८ — वह और तर्क नहीं। वह वही है जो मनुष्य तर्क पूरा होने पर करता है, और वह प्रार्थना निकलती है।",
  },

  "isha-15": {
    en: "The last four verses turn from argument to prayer, and this is the most quoted of them.\n\nWhat covers the face of truth is golden. Not a wall, not a darkness — a brilliance, the sun's own disc, hiraṇmaya. That choice is the whole insight of the verse. What obscures the real is not its opposite but a lesser radiance mistaken for it. Beauty is precisely what makes the covering hard to see past, because nobody wants to look through something that is already glorious.\n\nThe request is correspondingly modest. Not for a new vision, not for a revelation, but for a removal: apāvṛṇu, uncover. The truth is not absent and does not need to be delivered. It needs the thing in front of it moved.\n\nThe speaker states their qualification plainly — satyadharmāya, one whose dharma is truth. There is no false humility here and no boasting either; it is a statement of standing, the way one names one's competence when making a formal request. Śaṅkara reads the golden vessel as the whole realm of empirical experience, dazzling and therefore mistaken for final.",
    kn: "ಕೊನೆಯ ನಾಲ್ಕು ಶ್ಲೋಕಗಳು ವಾದದಿಂದ ಪ್ರಾರ್ಥನೆಗೆ ತಿರುಗುತ್ತವೆ, ಮತ್ತು ಇವುಗಳಲ್ಲಿ ಇದೇ ಅತ್ಯಂತ ಉಲ್ಲೇಖಿತ.\n\nಸತ್ಯದ ಮುಖವನ್ನು ಮುಚ್ಚಿರುವುದು ಸುವರ್ಣಮಯ. ಗೋಡೆಯಲ್ಲ, ಕತ್ತಲೆಯಲ್ಲ — ಪ್ರಕಾಶ, ಸೂರ್ಯನ ಬಿಂಬವೇ, 'ಹಿರಣ್ಮಯ'. ಈ ಆಯ್ಕೆಯೇ ಶ್ಲೋಕದ ಸಂಪೂರ್ಣ ಒಳನೋಟ. ವಾಸ್ತವವನ್ನು ಮರೆಮಾಚುವುದು ಅದರ ವಿರುದ್ಧವಲ್ಲ, ಅದೆಂದೇ ಭ್ರಮಿಸಲ್ಪಟ್ಟ ಒಂದು ಕಿರಿಯ ಪ್ರಕಾಶ. ಸೌಂದರ್ಯವೇ ಆ ಆವರಣವನ್ನು ದಾಟಿ ನೋಡುವುದನ್ನು ಕಷ್ಟಗೊಳಿಸುತ್ತದೆ, ಏಕೆಂದರೆ ಈಗಾಗಲೇ ವೈಭವವಾಗಿರುವುದರ ಆಚೆ ನೋಡಲು ಯಾರೂ ಬಯಸುವುದಿಲ್ಲ.\n\nಕೋರಿಕೆಯೂ ಅಷ್ಟೇ ವಿನಮ್ರ. ಹೊಸ ದರ್ಶನಕ್ಕಲ್ಲ, ಪ್ರಕಟನೆಗಲ್ಲ, ತೆಗೆದುಹಾಕುವಿಕೆಗೆ: 'ಅಪಾವೃಣು' — ತೆರೆ. ಸತ್ಯ ಇಲ್ಲದಿಲ್ಲ, ಅದನ್ನು ತಲುಪಿಸಬೇಕಿಲ್ಲ. ಅದರ ಮುಂದಿರುವುದನ್ನು ಸರಿಸಬೇಕಷ್ಟೆ.\n\nವಕ್ತೃ ತನ್ನ ಅರ್ಹತೆಯನ್ನು ನೇರವಾಗಿ ಹೇಳುತ್ತಾನೆ — 'ಸತ್ಯಧರ್ಮಾಯ', ಸತ್ಯವೇ ಧರ್ಮವಾದವನಿಗೆ. ಇಲ್ಲಿ ಸುಳ್ಳು ವಿನಯವೂ ಇಲ್ಲ, ಜಂಬವೂ ಇಲ್ಲ; ಔಪಚಾರಿಕ ಕೋರಿಕೆ ಮಾಡುವಾಗ ತನ್ನ ಅರ್ಹತೆಯನ್ನು ಹೆಸರಿಸುವ ಕ್ರಮದಂತೆ ಇದೊಂದು ಸ್ಥಾನದ ಹೇಳಿಕೆ. ಶಂಕರರು ಈ ಸುವರ್ಣಪಾತ್ರೆಯನ್ನು ಇಡೀ ಅನುಭವಜಗತ್ತೆಂದು ಓದುತ್ತಾರೆ — ಕಣ್ಣುಕುಕ್ಕುವಂಥದ್ದು, ಆದ್ದರಿಂದಲೇ ಅಂತಿಮವೆಂದು ತಪ್ಪಾಗಿ ತಿಳಿಯಲ್ಪಡುವಂಥದ್ದು.",
    hi: "अंतिम चार श्लोक तर्क से प्रार्थना की ओर मुड़ते हैं, और उनमें यही सर्वाधिक उद्धृत है।\n\nसत्य का मुख जो ढके है वह स्वर्णमय है। दीवार नहीं, अंधकार नहीं — आभा, सूर्य का ही बिंब, 'हिरण्मय'। यही चयन इस श्लोक की पूरी अंतर्दृष्टि है। वास्तविकता को उसका विपरीत नहीं ढकता, बल्कि एक छोटी आभा ढकती है जिसे वही मान लिया गया। सुंदरता ही उस आवरण के पार देखना कठिन बनाती है, क्योंकि जो पहले से वैभवमय है उसके पार कोई देखना नहीं चाहता।\n\nयाचना भी उतनी ही विनम्र है। नए दर्शन की नहीं, प्रकटन की नहीं, हटाने की: 'अपावृणु' — अनावृत कर। सत्य अनुपस्थित नहीं, उसे पहुँचाना नहीं है। उसके सामने जो है, उसे हटाना है।\n\nवक्ता अपनी पात्रता सीधे बताता है — 'सत्यधर्माय', जिसका धर्म सत्य है। यहाँ न झूठी विनम्रता है न बड़बोलापन; यह स्थिति का कथन है, जैसे औपचारिक निवेदन करते समय कोई अपनी योग्यता बताता है। शंकर इस स्वर्णपात्र को समस्त अनुभव-जगत् पढ़ते हैं — चकाचौंध करने वाला, और इसीलिए अंतिम मान लिया जाने वाला।",
  },

  "isha-16": {
    en: "The prayer becomes an address, and then does something no petition prepares you for.\n\nThe sun is named five times over — Pūṣan the nourisher, Ekarṣi the sole seer, Yama the controller, Sūrya, Prājāpatya, child of the creator. The piling up of names is Vedic invocation at its most formal, and it establishes maximum distance between speaker and addressed. This is someone praying to a god.\n\nThe request is practical: spread apart the rays, gather the burning, so the form behind the glare becomes visible. Then the speaker looks — tat te paśyāmi, 'that of yours I behold' — and the distance the five names had established collapses in four syllables. So 'ham asmi. I am he.\n\nThe verse enacts in its own grammar the movement the whole text has argued for. What began as the worship of another ends as recognition, and the one being addressed turns out to be the one addressing. It is worth noting that this verse is absent entirely from the Mādhyandina recension — the most dramatic single difference between the two versions, and a reminder that even the received text has a history.",
    kn: "ಪ್ರಾರ್ಥನೆ ಸಂಬೋಧನೆಯಾಗುತ್ತದೆ, ಆಮೇಲೆ ಯಾವ ಬೇಡಿಕೆಯೂ ಸಿದ್ಧಗೊಳಿಸದ ಒಂದನ್ನು ಮಾಡುತ್ತದೆ.\n\nಸೂರ್ಯನನ್ನು ಐದು ಹೆಸರುಗಳಿಂದ ಕರೆಯಲಾಗಿದೆ — ಪೋಷಕನಾದ ಪೂಷನ್, ಏಕದ್ರಷ್ಟನಾದ ಏಕರ್ಷಿ, ನಿಯಾಮಕನಾದ ಯಮ, ಸೂರ್ಯ, ಸೃಷ್ಟಿಕರ್ತನ ಮಗನಾದ ಪ್ರಾಜಾಪತ್ಯ. ಹೆಸರುಗಳ ಈ ರಾಶಿ ವೈದಿಕ ಆವಾಹನೆಯ ಅತ್ಯಂತ ಔಪಚಾರಿಕ ರೂಪ, ಮತ್ತು ಅದು ವಕ್ತೃ ಮತ್ತು ಸಂಬೋಧಿತನ ನಡುವೆ ಗರಿಷ್ಠ ಅಂತರವನ್ನು ಸ್ಥಾಪಿಸುತ್ತದೆ. ಇದು ಒಬ್ಬ ದೇವರಿಗೆ ಪ್ರಾರ್ಥಿಸುತ್ತಿರುವವನು.\n\nಕೋರಿಕೆ ವ್ಯಾವಹಾರಿಕ: ಕಿರಣಗಳನ್ನು ಚದುರಿಸು, ತೇಜಸ್ಸನ್ನು ಸಂಗ್ರಹಿಸು, ಪ್ರಖರತೆಯ ಹಿಂದಿನ ರೂಪ ಕಾಣುವಂತೆ. ಆಮೇಲೆ ವಕ್ತೃ ನೋಡುತ್ತಾನೆ — 'ತತ್ ತೇ ಪಶ್ಯಾಮಿ' — ಮತ್ತು ಆ ಐದು ಹೆಸರುಗಳು ಸ್ಥಾಪಿಸಿದ್ದ ಅಂತರ ನಾಲ್ಕು ಅಕ್ಷರಗಳಲ್ಲಿ ಕುಸಿಯುತ್ತದೆ. 'ಸೋಽಹಮಸ್ಮಿ'. ನಾನೇ ಅವನು.\n\nಇಡೀ ಪಠ್ಯ ವಾದಿಸಿದ ಚಲನೆಯನ್ನು ಈ ಶ್ಲೋಕ ತನ್ನ ವ್ಯಾಕರಣದಲ್ಲಿಯೇ ನಡೆಸಿ ತೋರಿಸುತ್ತದೆ. ಬೇರೊಬ್ಬನ ಆರಾಧನೆಯಾಗಿ ಆರಂಭವಾದದ್ದು ಗುರುತಿಸುವಿಕೆಯಾಗಿ ಮುಗಿಯುತ್ತದೆ, ಮತ್ತು ಸಂಬೋಧಿಸಲ್ಪಟ್ಟವನೇ ಸಂಬೋಧಿಸುತ್ತಿದ್ದವನೆಂದು ತಿಳಿಯುತ್ತದೆ. ಈ ಶ್ಲೋಕ ಮಾಧ್ಯಂದಿನ ಪಾಠದಲ್ಲಿ ಸಂಪೂರ್ಣವಾಗಿ ಇಲ್ಲ ಎಂಬುದು ಗಮನಾರ್ಹ — ಎರಡು ಪಾಠಗಳ ನಡುವಿನ ಅತ್ಯಂತ ನಾಟಕೀಯ ವ್ಯತ್ಯಾಸ, ಮತ್ತು ಸ್ವೀಕೃತ ಪಠ್ಯಕ್ಕೂ ಒಂದು ಇತಿಹಾಸವಿದೆ ಎಂಬ ನೆನಪು.",
    hi: "प्रार्थना संबोधन बन जाती है, और फिर वह करती है जिसके लिए कोई याचना तैयार नहीं करती।\n\nसूर्य को पाँच नामों से पुकारा गया है — पोषक पूषन्, एकद्रष्टा एकर्षि, नियामक यम, सूर्य, सृष्टिकर्ता के पुत्र प्राजापत्य। नामों का यह ढेर वैदिक आवाहन का सर्वाधिक औपचारिक रूप है, और वह वक्ता तथा संबोधित के बीच अधिकतम दूरी स्थापित करता है। यह कोई देवता से प्रार्थना करता व्यक्ति है।\n\nयाचना व्यावहारिक है: किरणें बिखेर दे, तेज समेट ले, ताकि चकाचौंध के पीछे का रूप दिखे। फिर वक्ता देखता है — 'तत् ते पश्यामि' — और पाँच नामों से बनी वह दूरी चार अक्षरों में ढह जाती है। 'सोऽहमस्मि'। मैं वही हूँ।\n\nजिस गति का सारा पाठ तर्क करता रहा, उसे यह श्लोक अपने ही व्याकरण में घटित कर देता है। जो दूसरे की उपासना से आरंभ हुआ, वह पहचान बनकर समाप्त होता है, और जिसे संबोधित किया गया वही संबोधित करने वाला निकलता है। उल्लेखनीय है कि यह श्लोक माध्यंदिन पाठ में पूर्णतः अनुपस्थित है — दोनों पाठों के बीच सबसे नाटकीय अंतर, और यह स्मरण कि स्वीकृत पाठ का भी एक इतिहास है।",
  },

  "isha-17": {
    en: "The verse of the last moment, and its restraint is what gives it force.\n\nBreath and body are dispatched in half a line each. Let the breath return to the immortal air; let this body end in ash. No argument, no regret, no appeal — the reasoning finished four verses ago and there is nothing left to establish. The word bhasmānta, 'ending in ash', is flatly descriptive. It is not being brave about death; it is simply not treating death as a topic requiring persuasion.\n\nWhat remains is kratu — will, resolve, the power of intention — and it is addressed directly, as a person. Om krato smara. O Will, remember.\n\nThe doubling is not decoration. Repeating the same four words twice is how someone speaks at the edge of dissolution, holding attention on one thing as everything else lets go. And what is asked for is not merit, not reward, not a good outcome: it is memory. Kṛtaṃ smara — remember what was done. That the actual shape a life took should be present to it at the moment it ends.",
    kn: "ಕೊನೆಯ ಕ್ಷಣದ ಶ್ಲೋಕ, ಮತ್ತು ಅದರ ಸಂಯಮವೇ ಅದಕ್ಕೆ ಬಲ ಕೊಡುತ್ತದೆ.\n\nಪ್ರಾಣ ಮತ್ತು ದೇಹವನ್ನು ಅರ್ಧರ್ಧ ಸಾಲಿನಲ್ಲಿ ಕಳುಹಿಸಲಾಗಿದೆ. ಪ್ರಾಣವು ಅಮರ ವಾಯುವನ್ನು ಸೇರಲಿ; ಈ ದೇಹವು ಭಸ್ಮದಲ್ಲಿ ಕೊನೆಗೊಳ್ಳಲಿ. ವಾದವಿಲ್ಲ, ವಿಷಾದವಿಲ್ಲ, ಮನವಿಯಿಲ್ಲ — ತರ್ಕ ನಾಲ್ಕು ಶ್ಲೋಕಗಳ ಹಿಂದೆಯೇ ಮುಗಿದಿದೆ ಮತ್ತು ಸ್ಥಾಪಿಸಲು ಏನೂ ಉಳಿದಿಲ್ಲ. 'ಭಸ್ಮಾಂತ' — ಭಸ್ಮದಲ್ಲಿ ಕೊನೆಗೊಳ್ಳುವ — ಎಂಬ ಪದ ಸರಳ ವರ್ಣನೆ. ಇದು ಮರಣದ ಬಗ್ಗೆ ಧೈರ್ಯ ತೋರುವುದಲ್ಲ; ಮರಣವನ್ನು ಮನವೊಲಿಸಬೇಕಾದ ವಿಷಯವೆಂದೇ ಪರಿಗಣಿಸದಿರುವುದು.\n\nಉಳಿಯುವುದು 'ಕ್ರತು' — ಸಂಕಲ್ಪ, ಇಚ್ಛಾಶಕ್ತಿ — ಮತ್ತು ಅದನ್ನು ವ್ಯಕ್ತಿಯಂತೆಯೇ ನೇರವಾಗಿ ಸಂಬೋಧಿಸಲಾಗಿದೆ. 'ಓಂ ಕ್ರತೋ ಸ್ಮರ'. ಸಂಕಲ್ಪವೇ, ಸ್ಮರಿಸು.\n\nಈ ಪುನರಾವರ್ತನೆ ಅಲಂಕಾರವಲ್ಲ. ಅದೇ ನಾಲ್ಕು ಪದಗಳನ್ನು ಎರಡು ಬಾರಿ ಹೇಳುವುದು — ಉಳಿದೆಲ್ಲವೂ ಕಳಚಿಕೊಳ್ಳುತ್ತಿರುವಾಗ ಒಂದೇ ವಿಷಯದ ಮೇಲೆ ಗಮನ ಹಿಡಿದಿಡುತ್ತಾ ಲಯದ ಅಂಚಿನಲ್ಲಿ ನಿಂತವನು ಮಾತನಾಡುವ ಬಗೆ ಅದು. ಮತ್ತು ಕೇಳುತ್ತಿರುವುದು ಪುಣ್ಯವಲ್ಲ, ಪ್ರತಿಫಲವಲ್ಲ, ಒಳ್ಳೆಯ ಫಲಿತಾಂಶವೂ ಅಲ್ಲ: ಸ್ಮೃತಿ. 'ಕೃತಂ ಸ್ಮರ' — ಮಾಡಿದ್ದನ್ನು ಸ್ಮರಿಸು. ಬದುಕು ನಿಜವಾಗಿ ಪಡೆದ ಆಕಾರವು ಅದು ಮುಗಿಯುವ ಕ್ಷಣದಲ್ಲಿ ಅದರೆದುರಿಗಿರಬೇಕು ಎಂದು.",
    hi: "अंतिम क्षण का श्लोक, और उसका संयम ही उसे बल देता है।\n\nप्राण और शरीर को आधी-आधी पंक्ति में विदा कर दिया गया है। प्राण अमर वायु में लौटे; यह शरीर भस्म में समाप्त हो। न तर्क, न पश्चाताप, न निवेदन — विवेचन चार श्लोक पहले पूरा हो चुका और स्थापित करने को कुछ शेष नहीं। 'भस्मांत' — भस्म में समाप्त होने वाला — यह शब्द सपाट वर्णन है। यह मृत्यु के प्रति वीरता दिखाना नहीं; यह मृत्यु को ऐसा विषय ही न मानना है जिस पर मनाना पड़े।\n\nजो शेष है वह 'क्रतु' है — संकल्प, इच्छाशक्ति — और उसे व्यक्ति की भाँति सीधे संबोधित किया गया है। 'ॐ क्रतो स्मर'। हे संकल्प, स्मरण कर।\n\nयह द्विरुक्ति अलंकार नहीं। उन्हीं चार शब्दों को दो बार कहना — यही वह ढंग है जिससे लय के कगार पर खड़ा व्यक्ति बोलता है, जब बाकी सब छूट रहा हो और ध्यान एक ही वस्तु पर टिका हो। और जो माँगा जा रहा है वह पुण्य नहीं, प्रतिफल नहीं, अच्छा परिणाम भी नहीं: स्मृति है। 'कृतं स्मर' — जो किया गया उसे स्मरण कर। कि जीवन ने वस्तुतः जो आकार लिया, वह समाप्ति के क्षण उसके सामने हो।",
  },

  "isha-18": {
    en: "The Upaniṣad ends not in silence but in a Vedic prayer to fire, and after everything that has preceded it, the ordinariness is the point.\n\nLead us by the good path. Keep crooked sin from us. Receive our homage. After eighteen verses of paradox, negation and identity-collapse, the last word is practical and even humble — the concerns of someone who still has a road to walk.\n\nTwo details carry the ending. Agni is addressed as viśvāni deva vayunāni vidvān — the god who knows all our ways. The guide is not being informed of anything; it is only being asked. And juhurāṇa, 'crooked-going', names the danger precisely: not failure, not weakness, but deviousness — the path that bends away while appearing to continue.\n\nThe text that opened by wrapping the entire moving world in the Lord closes by asking, simply, to be led straight. That arc — from the largest possible statement to the most modest possible request — is the Isha's final argument about what knowledge is for. It does not exempt you from the road. It tells you whose road it is.",
    kn: "ಉಪನಿಷತ್ತು ಮೌನದಲ್ಲಲ್ಲ, ಅಗ್ನಿಗೆ ಸಲ್ಲಿಸಿದ ವೈದಿಕ ಪ್ರಾರ್ಥನೆಯಲ್ಲಿ ಮುಗಿಯುತ್ತದೆ, ಮತ್ತು ಹಿಂದೆ ಬಂದದ್ದೆಲ್ಲದರ ನಂತರ ಈ ಸಾಮಾನ್ಯತೆಯೇ ಸಾರ.\n\nಒಳ್ಳೆಯ ಮಾರ್ಗದಿಂದ ನಮ್ಮನ್ನು ಒಯ್ಯು. ವಕ್ರವಾದ ಪಾಪವನ್ನು ದೂರವಿಡು. ನಮ್ಮ ನಮಸ್ಕಾರವನ್ನು ಸ್ವೀಕರಿಸು. ಹದಿನೆಂಟು ಶ್ಲೋಕಗಳ ವಿರೋಧಾಭಾಸ, ನಿಷೇಧ ಮತ್ತು ಅಭೇದದ ನಂತರ ಕೊನೆಯ ಮಾತು ವ್ಯಾವಹಾರಿಕ ಮತ್ತು ವಿನಮ್ರ — ಇನ್ನೂ ನಡೆಯಬೇಕಾದ ದಾರಿಯಿರುವವನ ಕಾಳಜಿಗಳು.\n\nಎರಡು ಸಂಗತಿಗಳು ಈ ಅಂತ್ಯವನ್ನು ಹೊತ್ತಿವೆ. ಅಗ್ನಿಯನ್ನು 'ವಿಶ್ವಾನಿ ದೇವ ವಯುನಾನಿ ವಿದ್ವಾನ್' ಎಂದು ಸಂಬೋಧಿಸಲಾಗಿದೆ — ನಮ್ಮೆಲ್ಲ ದಾರಿಗಳನ್ನೂ ಬಲ್ಲ ದೇವ. ಮಾರ್ಗದರ್ಶಕನಿಗೆ ಯಾವ ಮಾಹಿತಿಯನ್ನೂ ಕೊಡುತ್ತಿಲ್ಲ; ಕೇವಲ ಕೇಳಿಕೊಳ್ಳಲಾಗುತ್ತಿದೆ. ಮತ್ತು 'ಜುಹುರಾಣ' — ವಕ್ರವಾಗಿ ನಡೆಯುವುದು — ಎಂಬ ಪದ ಅಪಾಯವನ್ನು ನಿಖರವಾಗಿ ಹೆಸರಿಸುತ್ತದೆ: ಸೋಲಲ್ಲ, ದೌರ್ಬಲ್ಯವಲ್ಲ, ವಕ್ರತೆ — ಮುಂದುವರಿಯುತ್ತಿರುವಂತೆ ಕಾಣುತ್ತಲೇ ಬದಿಗೆ ಬಾಗುವ ದಾರಿ.\n\nಇಡೀ ಚಲಿಸುವ ಜಗತ್ತನ್ನು ಈಶ್ವರನಿಂದ ಹೊದಿಸಿ ಆರಂಭವಾದ ಪಠ್ಯವು, ನೇರವಾಗಿ ನಡೆಸು ಎಂದು ಸರಳವಾಗಿ ಕೇಳುತ್ತಾ ಮುಗಿಯುತ್ತದೆ. ಸಾಧ್ಯವಾದ ಅತಿ ದೊಡ್ಡ ಹೇಳಿಕೆಯಿಂದ ಸಾಧ್ಯವಾದ ಅತಿ ವಿನಮ್ರ ಕೋರಿಕೆಯವರೆಗಿನ ಈ ಚಾಪವೇ — ಜ್ಞಾನ ಯಾವುದಕ್ಕಾಗಿ ಎಂಬುದರ ಕುರಿತ ಈಶಾವಾಸ್ಯದ ಕೊನೆಯ ವಾದ. ಅದು ನಿಮ್ಮನ್ನು ದಾರಿಯಿಂದ ವಿನಾಯಿತಿಗೊಳಿಸುವುದಿಲ್ಲ. ಆ ದಾರಿ ಯಾರದೆಂದು ಹೇಳುತ್ತದೆ.",
    hi: "उपनिषद् मौन में नहीं, अग्नि को की गई वैदिक प्रार्थना में समाप्त होता है, और पहले जो कुछ आया उसके बाद यही सामान्यता सार है।\n\nसुमार्ग से हमें ले चल। कुटिल पाप को हमसे दूर रख। हमारा नमस्कार स्वीकार कर। अठारह श्लोकों के विरोधाभास, निषेध और अभेद के बाद अंतिम बात व्यावहारिक और विनम्र है — उस व्यक्ति की चिंताएँ जिसे अभी रास्ता चलना है।\n\nदो बातें इस अंत को थामे हैं। अग्नि को 'विश्वानि देव वयुनानि विद्वान्' कहकर संबोधित किया गया है — वह देव जो हमारे सब मार्ग जानता है। मार्गदर्शक को कोई सूचना नहीं दी जा रही; केवल प्रार्थना की जा रही है। और 'जुहुराण' — कुटिल गति वाला — शब्द संकट को ठीक-ठीक नामित करता है: विफलता नहीं, दुर्बलता नहीं, बल्कि कुटिलता — वह मार्ग जो चलता हुआ दिखते हुए भी बगल में मुड़ जाता है।\n\nजो पाठ समस्त चराचर जगत् को ईश्वर से आवृत करके आरंभ हुआ, वह सीधे ले चलने की सरल याचना के साथ समाप्त होता है। संभव सबसे बड़े कथन से संभव सबसे विनम्र याचना तक का यही चाप — ज्ञान किसलिए है, इस पर ईशावास्य का अंतिम तर्क है। वह आपको रास्ते से छूट नहीं देता। वह बताता है कि रास्ता किसका है।",
  },
};
