import type { Locale } from "@/i18n/config";

// ─────────────────────────────────────────────────────────
//  Commentary on the Māṇḍūkya Upaniṣad.
//
//  Split from mandukya.ts for the same reason the Īśa's is: the
//  mūla is fixed, the commentary is the layer that keeps being
//  revised, and it should be editable without going near the
//  verse text.
//
//  What it draws on. Gauḍapāda's Kārikā is the indispensable
//  companion — the Māṇḍūkya is twelve sentences and the Kārikā is
//  two hundred and fifteen verses of argument built on them, and
//  Śaṅkara commented on both together. Where the Kārikā's reading
//  goes beyond what the mantra says on its face, that is stated
//  rather than blended in.
//
//  The site's own editorial prose, labelled as such wherever it
//  appears.
// ─────────────────────────────────────────────────────────

export type Commentary = Record<Locale, string>;

export const MANDUKYA_COMMENTARY: Record<string, Commentary> = {
  "mandukya-1": {
    en: "The text opens by identifying a sound with everything there is, and the word it uses is akṣara — which means both 'syllable' and 'the imperishable'. The pun is not decoration; it is the claim being made.\n\nWatch the structure. First the three times are gathered in: what was, what is, what shall be, all of it Om. A symbol could manage that much — anything can be made to stand for everything. Then the second clause does what a symbol cannot: whatever lies beyond the three times is also Om. So Om is not being offered as a name for the universe. It is being offered as the one term that covers both the temporal and what is not temporal at all, and that is precisely the work the rest of the text will do with the four quarters.\n\nŚaṅkara is careful here about why a sound can carry this. His argument is that name and named are not two in the way a label and an object are: the word is how the thing is available to a mind at all. On that reading Om is not a pointer to Brahman but the form in which Brahman is thinkable, which is why the last four mantras can treat chanting as a method rather than a devotion.",
    kn: "ಪಠ್ಯವು ಒಂದು ಧ್ವನಿಯನ್ನು ಇರುವ ಎಲ್ಲದರೊಂದಿಗೆ ಸಮೀಕರಿಸುತ್ತಾ ಆರಂಭವಾಗುತ್ತದೆ, ಮತ್ತು ಅದು ಬಳಸುವ ಪದ 'ಅಕ್ಷರ' — ಇದಕ್ಕೆ 'ಉಚ್ಚಾರಾಂಶ' ಮತ್ತು 'ನಾಶವಿಲ್ಲದ್ದು' ಎರಡೂ ಅರ್ಥ. ಈ ಶ್ಲೇಷೆ ಅಲಂಕಾರವಲ್ಲ; ಅದೇ ಇಲ್ಲಿನ ಪ್ರತಿಪಾದನೆ.\n\nರಚನೆಯನ್ನು ಗಮನಿಸಿ. ಮೊದಲು ಮೂರು ಕಾಲಗಳನ್ನೂ ಒಳಗೆ ತೆಗೆದುಕೊಳ್ಳಲಾಗಿದೆ: ಆಗಿಹೋದದ್ದು, ಇರುವುದು, ಆಗಲಿರುವುದು — ಎಲ್ಲವೂ ಓಂ. ಅಷ್ಟನ್ನು ಒಂದು ಸಂಕೇತವೂ ಮಾಡಬಲ್ಲದು; ಯಾವುದನ್ನಾದರೂ ಎಲ್ಲದಕ್ಕೂ ಪ್ರತಿನಿಧಿಯಾಗಿಸಬಹುದು. ಆದರೆ ಎರಡನೆಯ ವಾಕ್ಯ ಸಂಕೇತಕ್ಕೆ ಸಾಧ್ಯವಿಲ್ಲದ್ದನ್ನು ಮಾಡುತ್ತದೆ: ಮೂರು ಕಾಲಗಳನ್ನೂ ಮೀರಿರುವುದೂ ಓಂಕಾರವೇ. ಆದ್ದರಿಂದ ಓಂ ಇಲ್ಲಿ ವಿಶ್ವದ ಹೆಸರಾಗಿ ಕೊಡಲ್ಪಟ್ಟಿಲ್ಲ. ಕಾಲಿಕವಾದದ್ದನ್ನೂ ಕಾಲಾತೀತವಾದದ್ದನ್ನೂ ಒಟ್ಟಿಗೆ ಆವರಿಸುವ ಏಕೈಕ ಪದವಾಗಿ ಕೊಡಲ್ಪಟ್ಟಿದೆ — ಮುಂದೆ ನಾಲ್ಕು ಪಾದಗಳ ಮೂಲಕ ಪಠ್ಯ ಮಾಡಲಿರುವ ಕೆಲಸವೇ ಅದು.\n\nಒಂದು ಧ್ವನಿ ಇಷ್ಟನ್ನು ಹೊರಬಲ್ಲದೇಕೆ ಎಂಬುದರ ಬಗ್ಗೆ ಶಂಕರರು ಇಲ್ಲಿ ಎಚ್ಚರಿಕೆ ವಹಿಸುತ್ತಾರೆ. ಹೆಸರೂ ಹೆಸರಿಸಲ್ಪಟ್ಟದ್ದೂ ಚೀಟಿ ಮತ್ತು ವಸ್ತುವಿನಂತೆ ಎರಡಲ್ಲ ಎಂಬುದು ಅವರ ವಾದ: ಮನಸ್ಸಿಗೆ ವಸ್ತು ದೊರೆಯುವ ಕ್ರಮವೇ ಶಬ್ದ. ಆ ಓದಿನಲ್ಲಿ ಓಂಕಾರ ಬ್ರಹ್ಮದತ್ತ ತೋರಿಸುವ ಬೆರಳಲ್ಲ, ಬ್ರಹ್ಮ ಚಿಂತಿಸಲ್ಪಡಬಹುದಾದ ರೂಪ — ಆದ್ದರಿಂದಲೇ ಕೊನೆಯ ನಾಲ್ಕು ಮಂತ್ರಗಳು ಜಪವನ್ನು ಭಕ್ತಿಯಲ್ಲ, ವಿಧಾನವೆಂದು ಪರಿಗಣಿಸಬಲ್ಲವು.",
    hi: "पाठ एक ध्वनि को समस्त सत्ता के साथ अभिन्न बताकर आरंभ होता है, और जो शब्द वह प्रयोग करता है वह 'अक्षर' है — जिसका अर्थ 'वर्ण' भी है और 'अविनाशी' भी। यह श्लेष अलंकार नहीं; वही यहाँ का प्रतिपाद्य है।\n\nसंरचना देखिए। पहले तीनों काल समेटे गए: जो हुआ, जो है, जो होगा — सब ॐ। इतना तो कोई प्रतीक भी कर सकता है; किसी को भी सबका प्रतिनिधि बनाया जा सकता है। किंतु दूसरा वाक्य वह करता है जो प्रतीक नहीं कर सकता: जो तीनों कालों से परे है वह भी ॐकार ही है। अतः ॐ यहाँ विश्व के नाम के रूप में नहीं दिया गया। वह उस एक पद के रूप में दिया गया है जो कालिक और अकालिक दोनों को समेटता है — और आगे चार पादों के द्वारा पाठ यही काम करेगा।\n\nएक ध्वनि इतना कैसे उठा सकती है, इस पर शंकर सावधान हैं। उनका तर्क है कि नाम और नामी उस तरह दो नहीं जैसे लेबल और वस्तु: शब्द ही वह ढंग है जिससे वस्तु मन को उपलब्ध होती है। उस पाठ में ॐ ब्रह्म की ओर संकेत नहीं, बल्कि वह रूप है जिसमें ब्रह्म चिंतनीय है — इसीलिए अंतिम चार मंत्र जप को भक्ति नहीं, विधि मान सकते हैं।",
  },

  "mandukya-2": {
    en: "One of the four Mahāvākyas, and the one belonging to the Atharvaveda. Its force is in the demonstrative: ayam, 'this'. Not the Self in general, not the Self as a doctrine held about the world — this one, the one reading the sentence.\n\nThe first clause has already done something large. Sarvaṃ hy etad brahma — all this is Brahman — settles the world's status before the Self is mentioned, so that the identity to follow is not an escape from anything. Nothing has been declared unreal in order to make room for the Self.\n\nThe second half is what makes the text a method rather than a proclamation. Having identified Self and Brahman, it immediately says the Self is catuṣpāt, four-quartered, and the remaining ten mantras walk through those quarters one at a time. So the identity is not offered as something to believe. It is offered as something to check — against four states every reader already has, three of which they enter every night without instruction.\n\nGauḍapāda builds his entire first chapter on this word pāda, and notes the ambiguity deliberately: a pāda is a quarter, and also a foot — something you stand on, and something you move by.",
    kn: "ನಾಲ್ಕು ಮಹಾವಾಕ್ಯಗಳಲ್ಲಿ ಒಂದು, ಮತ್ತು ಅಥರ್ವವೇದಕ್ಕೆ ಸೇರಿದ್ದು. ಇದರ ಬಲವಿರುವುದು 'ಅಯಂ' ಎಂಬ ನಿರ್ದೇಶಕ ಪದದಲ್ಲಿ — 'ಈ'. ಸಾಮಾನ್ಯವಾಗಿ ಆತ್ಮವಲ್ಲ, ಜಗತ್ತಿನ ಬಗ್ಗೆ ಹೊಂದಿದ ಸಿದ್ಧಾಂತವಾಗಿ ಆತ್ಮವಲ್ಲ — ಇದೇ, ಈ ವಾಕ್ಯವನ್ನು ಓದುತ್ತಿರುವವನೇ.\n\nಮೊದಲ ವಾಕ್ಯಾಂಶ ಈಗಾಗಲೇ ದೊಡ್ಡದೊಂದನ್ನು ಮಾಡಿದೆ. 'ಸರ್ವಂ ಹ್ಯೇತದ್ ಬ್ರಹ್ಮ' — ಇದೆಲ್ಲವೂ ಬ್ರಹ್ಮ — ಆತ್ಮದ ಪ್ರಸ್ತಾಪಕ್ಕೂ ಮೊದಲೇ ಜಗತ್ತಿನ ಸ್ಥಾನವನ್ನು ಇತ್ಯರ್ಥಗೊಳಿಸುತ್ತದೆ, ಆದ್ದರಿಂದ ಮುಂದಿನ ಅಭೇದವು ಯಾವುದರಿಂದಲೂ ಪಲಾಯನವಲ್ಲ. ಆತ್ಮಕ್ಕೆ ಜಾಗ ಮಾಡಲೆಂದು ಯಾವುದನ್ನೂ ಮಿಥ್ಯೆಯೆಂದು ಘೋಷಿಸಿಲ್ಲ.\n\nಎರಡನೆಯ ಅರ್ಧವೇ ಈ ಪಠ್ಯವನ್ನು ಘೋಷಣೆಯಲ್ಲ, ವಿಧಾನವನ್ನಾಗಿ ಮಾಡುತ್ತದೆ. ಆತ್ಮ ಮತ್ತು ಬ್ರಹ್ಮದ ಅಭೇದವನ್ನು ಹೇಳಿದ ಕೂಡಲೇ ಆತ್ಮವು 'ಚತುಷ್ಪಾತ್' ಎಂದು ಹೇಳುತ್ತದೆ, ಮತ್ತು ಉಳಿದ ಹತ್ತು ಮಂತ್ರಗಳು ಆ ಪಾದಗಳ ಮೂಲಕ ಒಂದೊಂದಾಗಿ ನಡೆಸುತ್ತವೆ. ಆದ್ದರಿಂದ ಈ ಅಭೇದವನ್ನು ನಂಬಲು ಕೊಟ್ಟಿಲ್ಲ. ಪರೀಕ್ಷಿಸಲು ಕೊಟ್ಟಿದೆ — ಪ್ರತಿ ಓದುಗನಿಗೂ ಈಗಾಗಲೇ ಇರುವ ನಾಲ್ಕು ಅವಸ್ಥೆಗಳ ವಿರುದ್ಧ, ಅವುಗಳಲ್ಲಿ ಮೂರನ್ನು ಅವನು ಯಾವ ಬೋಧನೆಯೂ ಇಲ್ಲದೆ ಪ್ರತಿ ರಾತ್ರಿ ಪ್ರವೇಶಿಸುತ್ತಾನೆ.\n\nಗೌಡಪಾದರು ತಮ್ಮ ಇಡೀ ಮೊದಲ ಅಧ್ಯಾಯವನ್ನು ಈ 'ಪಾದ' ಎಂಬ ಪದದ ಮೇಲೆ ಕಟ್ಟುತ್ತಾರೆ, ಮತ್ತು ಈ ದ್ವ್ಯರ್ಥವನ್ನು ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಗಮನಿಸುತ್ತಾರೆ: ಪಾದವೆಂದರೆ ಕಾಲುಭಾಗ, ಮತ್ತು ಕಾಲೂ ಹೌದು — ನಿಂತುಕೊಳ್ಳುವುದು, ಮತ್ತು ನಡೆಯುವ ಸಾಧನ.",
    hi: "चार महावाक्यों में से एक, और अथर्ववेद का। इसका बल 'अयम्' इस निर्देशक शब्द में है — 'यह'। सामान्य रूप से आत्मा नहीं, जगत् के विषय में धारित सिद्धांत रूप में आत्मा नहीं — यही, जो इस वाक्य को पढ़ रहा है।\n\nपहला वाक्यांश पहले ही कुछ बड़ा कर चुका है। 'सर्वं ह्येतद् ब्रह्म' — यह सब ब्रह्म है — आत्मा के उल्लेख से पूर्व ही जगत् की स्थिति तय कर देता है, जिससे आगे की अभिन्नता किसी से पलायन नहीं रहती। आत्मा के लिए स्थान बनाने हेतु किसी को मिथ्या घोषित नहीं किया गया।\n\nदूसरा आधा ही इस पाठ को घोषणा नहीं, विधि बनाता है। आत्मा और ब्रह्म की अभिन्नता कहते ही वह कहता है कि आत्मा 'चतुष्पात्' है, और शेष दस मंत्र उन पादों से एक-एक करके चलते हैं। अतः यह अभेद मानने के लिए नहीं दिया गया। जाँचने के लिए दिया गया है — उन चार अवस्थाओं के सामने जो हर पाठक के पास पहले से हैं, जिनमें से तीन में वह बिना किसी उपदेश के हर रात प्रवेश करता है।\n\nगौडपाद अपना पूरा प्रथम अध्याय इसी 'पाद' शब्द पर खड़ा करते हैं, और इस द्व्यर्थ को जानबूझकर लक्षित करते हैं: पाद अर्थात् चौथाई, और पैर भी — जिस पर खड़े होते हैं, और जिससे चलते हैं।",
  },

  "mandukya-3": {
    en: "The waking state, described from outside rather than from inside it — and that shift of vantage is the whole method of the next three mantras.\n\nWhat is catalogued here is not the world but the apparatus. Seven limbs, from the Vaiśvānara imagery of the Chāndogya, and nineteen mouths: five organs of perception, five of action, five prāṇas, and mind, intellect, ego and citta. Nineteen doorways through which the gross is taken in. Nothing is said about what comes through them, because the point is that something is doing the taking.\n\nThe name is doing work. Vaiśvānara means 'common to all people', and waking is the one state where everyone agrees they are in the same world. That agreement is exactly what makes it feel like the real one, the standard against which dream is measured and found wanting. The text sets that assumption up carefully — and mantra 4 will describe dream in identical terms in order to take it apart.\n\nNote also sthūlabhuk, 'experiencer of the gross'. Even here the Self is named as the one who experiences, never as the body or the senses. The four quarters differ in what is experienced, not in who.",
    kn: "ಜಾಗ್ರದವಸ್ಥೆಯನ್ನು ಒಳಗಿನಿಂದಲ್ಲ, ಹೊರಗಿನಿಂದ ವರ್ಣಿಸಲಾಗಿದೆ — ಮತ್ತು ದೃಷ್ಟಿಕೋನದ ಈ ಬದಲಾವಣೆಯೇ ಮುಂದಿನ ಮೂರು ಮಂತ್ರಗಳ ಇಡೀ ವಿಧಾನ.\n\nಇಲ್ಲಿ ಪಟ್ಟಿಮಾಡಿರುವುದು ಜಗತ್ತನ್ನಲ್ಲ, ಸಾಧನವನ್ನು. ಛಾಂದೋಗ್ಯದ ವೈಶ್ವಾನರ ಕಲ್ಪನೆಯಿಂದ ಬಂದ ಏಳು ಅಂಗಗಳು, ಮತ್ತು ಹತ್ತೊಂಬತ್ತು ಮುಖಗಳು: ಐದು ಜ್ಞಾನೇಂದ್ರಿಯಗಳು, ಐದು ಕರ್ಮೇಂದ್ರಿಯಗಳು, ಐದು ಪ್ರಾಣಗಳು, ಮತ್ತು ಮನಸ್ಸು, ಬುದ್ಧಿ, ಅಹಂಕಾರ, ಚಿತ್ತ. ಸ್ಥೂಲವನ್ನು ಒಳಗೆ ತೆಗೆದುಕೊಳ್ಳುವ ಹತ್ತೊಂಬತ್ತು ಬಾಗಿಲುಗಳು. ಅವುಗಳ ಮೂಲಕ ಏನು ಬರುತ್ತದೆಂದು ಹೇಳಿಲ್ಲ, ಏಕೆಂದರೆ ತೆಗೆದುಕೊಳ್ಳುತ್ತಿರುವ ಏನೋ ಇದೆ ಎಂಬುದೇ ಸಾರ.\n\nಹೆಸರು ಕೆಲಸ ಮಾಡುತ್ತಿದೆ. 'ವೈಶ್ವಾನರ' ಎಂದರೆ 'ಎಲ್ಲ ಜನರಿಗೂ ಸಾಮಾನ್ಯ', ಮತ್ತು ಜಾಗ್ರತ್ ಎಂಬುದೇ ಎಲ್ಲರೂ ತಾವು ಒಂದೇ ಜಗತ್ತಿನಲ್ಲಿದ್ದೇವೆಂದು ಒಪ್ಪುವ ಏಕೈಕ ಅವಸ್ಥೆ. ಆ ಒಪ್ಪಿಗೆಯೇ ಅದನ್ನು ನಿಜವಾದದ್ದೆಂದು ಭಾಸವಾಗಿಸುತ್ತದೆ — ಸ್ವಪ್ನವನ್ನು ಅಳೆದು ಕಡಿಮೆಯೆಂದು ತೀರ್ಮಾನಿಸುವ ಮಾನದಂಡ. ಪಠ್ಯವು ಆ ಊಹೆಯನ್ನು ಎಚ್ಚರಿಕೆಯಿಂದ ಕಟ್ಟುತ್ತದೆ — ಮತ್ತು ನಾಲ್ಕನೆಯ ಮಂತ್ರವು ಅದನ್ನೇ ಬಿಡಿಸಲು ಸ್ವಪ್ನವನ್ನು ಇದೇ ಪದಗಳಲ್ಲಿ ವರ್ಣಿಸುತ್ತದೆ.\n\n'ಸ್ಥೂಲಭುಕ್' — ಸ್ಥೂಲವನ್ನು ಅನುಭವಿಸುವವನು — ಎಂಬುದನ್ನೂ ಗಮನಿಸಿ. ಇಲ್ಲಿಯೂ ಆತ್ಮವನ್ನು ಅನುಭವಿಸುವವನೆಂದೇ ಹೆಸರಿಸಲಾಗಿದೆ, ದೇಹವೆಂದೋ ಇಂದ್ರಿಯಗಳೆಂದೋ ಎಂದೂ ಅಲ್ಲ. ನಾಲ್ಕು ಪಾದಗಳು ಭಿನ್ನವಾಗಿರುವುದು ಏನನ್ನು ಅನುಭವಿಸಲಾಗುತ್ತದೆ ಎಂಬುದರಲ್ಲಿ, ಯಾರು ಎಂಬುದರಲ್ಲಿ ಅಲ್ಲ.",
    hi: "जाग्रत् अवस्था का वर्णन भीतर से नहीं, बाहर से किया गया है — और दृष्टिकोण का यही परिवर्तन अगले तीन मंत्रों की पूरी विधि है।\n\nयहाँ जिसकी सूची है वह जगत् नहीं, उपकरण है। छांदोग्य की वैश्वानर कल्पना से आए सात अंग, और उन्नीस मुख: पाँच ज्ञानेंद्रियाँ, पाँच कर्मेंद्रियाँ, पाँच प्राण, तथा मन, बुद्धि, अहंकार और चित्त। स्थूल को ग्रहण करने के उन्नीस द्वार। उनसे क्या आता है यह नहीं कहा गया, क्योंकि सार यही है कि ग्रहण करने वाला कोई है।\n\nनाम काम कर रहा है। 'वैश्वानर' अर्थात् 'सब मनुष्यों में समान', और जाग्रत् ही वह एक अवस्था है जिसमें सब मानते हैं कि वे एक ही जगत् में हैं। वही सहमति उसे वास्तविक प्रतीत कराती है — वह मानदंड जिससे स्वप्न को नापकर कम आँका जाता है। पाठ उस पूर्वधारणा को सावधानी से खड़ा करता है — और चौथा मंत्र उसी को खोलने के लिए स्वप्न का वर्णन ठीक इन्हीं शब्दों में करेगा।\n\n'स्थूलभुक्' — स्थूल का भोक्ता — पर भी ध्यान दें। यहाँ भी आत्मा को भोक्ता ही कहा गया है, कभी शरीर या इंद्रियाँ नहीं। चारों पाद इसमें भिन्न हैं कि क्या भोगा जाता है, इसमें नहीं कि कौन भोगता है।",
  },

  "mandukya-4": {
    en: "The description is deliberately identical to the waking state except for three words: the field is dream, the awareness is inward, and what is experienced is subtle rather than gross. Same seven limbs, same nineteen mouths. The apparatus does not change at all.\n\nThat parallel is the argument, and it is made by repetition rather than by assertion. If dreaming has the same structure as waking and differs only in the material it works on, then the felt solidity of the waking world is not evidence for its special status — a dream feels solid too, for exactly as long as it lasts, and its unreality is only ever discovered from outside it.\n\nTaijasa, 'the luminous', names the point precisely. In dream there is no sun, no lamp, no external light of any kind, and yet everything is seen. Consciousness is supplying the illumination. Gauḍapāda presses this hard: if awareness can produce a complete world with its own space, time and causation out of nothing but itself, the question of what it is doing in waking becomes open rather than settled.\n\npravivikta-bhuk, 'experiencer of the isolated', is worth noticing too. What dream offers is experience separated out from external objects — the same act of knowing, running without its usual supply.",
    kn: "ಈ ವರ್ಣನೆ ಜಾಗ್ರದವಸ್ಥೆಯದಕ್ಕೆ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಸಮಾನ, ಕೇವಲ ಮೂರು ಪದಗಳಲ್ಲಿ ಭೇದ: ಸ್ಥಾನ ಸ್ವಪ್ನ, ಪ್ರಜ್ಞೆ ಒಳಮುಖ, ಅನುಭವಿಸುವುದು ಸ್ಥೂಲವಲ್ಲ ಸೂಕ್ಷ್ಮ. ಅದೇ ಏಳು ಅಂಗಗಳು, ಅದೇ ಹತ್ತೊಂಬತ್ತು ಮುಖಗಳು. ಸಾಧನ ಸ್ವಲ್ಪವೂ ಬದಲಾಗುವುದಿಲ್ಲ.\n\nಈ ಸಮಾನಾಂತರವೇ ವಾದ, ಮತ್ತು ಅದನ್ನು ಪ್ರತಿಪಾದನೆಯಿಂದಲ್ಲ, ಪುನರಾವರ್ತನೆಯಿಂದ ಮಾಡಲಾಗಿದೆ. ಸ್ವಪ್ನಕ್ಕೂ ಜಾಗ್ರತ್ತಿಗೂ ಒಂದೇ ರಚನೆಯಿದ್ದು ಕೇವಲ ದ್ರವ್ಯದಲ್ಲಿ ಭೇದವಿದ್ದರೆ, ಜಾಗ್ರಜ್ಜಗತ್ತಿನ ಘನತೆಯ ಅನುಭವ ಅದರ ವಿಶೇಷ ಸ್ಥಾನಕ್ಕೆ ಸಾಕ್ಷಿಯಲ್ಲ — ಸ್ವಪ್ನವೂ ಉಳಿಯುವಷ್ಟು ಕಾಲ ಘನವಾಗಿಯೇ ತೋರುತ್ತದೆ, ಮತ್ತು ಅದರ ಮಿಥ್ಯೆ ಯಾವಾಗಲೂ ಅದರ ಹೊರಗಿನಿಂದಲೇ ತಿಳಿಯುತ್ತದೆ.\n\n'ತೈಜಸ' ಎಂಬ ಹೆಸರು ಇದನ್ನು ನಿಖರವಾಗಿ ಹೇಳುತ್ತದೆ. ಸ್ವಪ್ನದಲ್ಲಿ ಸೂರ್ಯನಿಲ್ಲ, ದೀಪವಿಲ್ಲ, ಯಾವ ಬಗೆಯ ಹೊರಗಿನ ಬೆಳಕೂ ಇಲ್ಲ, ಆದರೂ ಎಲ್ಲವೂ ಕಾಣುತ್ತದೆ. ಪ್ರಜ್ಞೆಯೇ ಬೆಳಕನ್ನು ಒದಗಿಸುತ್ತಿದೆ. ಗೌಡಪಾದರು ಇದನ್ನು ಬಲವಾಗಿ ಒತ್ತುತ್ತಾರೆ: ಅರಿವು ತನ್ನಿಂದಲೇ, ತನ್ನದೇ ದೇಶ-ಕಾಲ-ಕಾರಣಗಳಿರುವ ಸಂಪೂರ್ಣ ಜಗತ್ತೊಂದನ್ನು ಸೃಷ್ಟಿಸಬಲ್ಲದಾದರೆ, ಜಾಗ್ರತ್ತಿನಲ್ಲಿ ಅದು ಏನು ಮಾಡುತ್ತಿದೆ ಎಂಬ ಪ್ರಶ್ನೆ ಇತ್ಯರ್ಥವಾಗಿಲ್ಲ, ತೆರೆದಿದೆ.\n\n'ಪ್ರವಿವಿಕ್ತಭುಕ್' — ಬೇರ್ಪಡಿಸಲ್ಪಟ್ಟದ್ದನ್ನು ಅನುಭವಿಸುವವನು — ಎಂಬುದೂ ಗಮನಾರ್ಹ. ಸ್ವಪ್ನ ಕೊಡುವುದು ಹೊರಗಿನ ವಿಷಯಗಳಿಂದ ಬೇರ್ಪಟ್ಟ ಅನುಭವ — ಅದೇ ಅರಿವಿನ ಕ್ರಿಯೆ, ತನ್ನ ಎಂದಿನ ಪೂರೈಕೆಯಿಲ್ಲದೆ ನಡೆಯುತ್ತಿರುವುದು.",
    hi: "यह वर्णन जाग्रत् के वर्णन से जानबूझकर समान है, केवल तीन शब्दों का भेद: स्थान स्वप्न, प्रज्ञा अंतर्मुख, और भोग स्थूल नहीं सूक्ष्म। वही सात अंग, वही उन्नीस मुख। उपकरण तनिक भी नहीं बदलता।\n\nयही समांतरता तर्क है, और वह प्रतिपादन से नहीं, पुनरावृत्ति से किया गया है। यदि स्वप्न की संरचना जाग्रत् जैसी ही है और भेद केवल सामग्री का है, तो जाग्रत् जगत् की अनुभूत ठोसता उसकी विशेष स्थिति का प्रमाण नहीं — स्वप्न भी जितनी देर रहता है ठोस ही लगता है, और उसका मिथ्यात्व सदा उसके बाहर से ही जाना जाता है।\n\n'तैजस' नाम इसी बिंदु को ठीक-ठीक कहता है। स्वप्न में न सूर्य है, न दीप, न किसी प्रकार का बाहरी प्रकाश, फिर भी सब दिखता है। चेतना ही प्रकाश दे रही है। गौडपाद इसे ज़ोर से दबाते हैं: यदि चेतना केवल अपने से ही अपने देश, काल और कारण सहित एक पूर्ण जगत् रच सकती है, तो जाग्रत् में वह क्या कर रही है — यह प्रश्न तय नहीं, खुला हो जाता है।\n\n'प्रविविक्तभुक्' — पृथक् किए हुए का भोक्ता — भी ध्यान देने योग्य है। स्वप्न जो देता है वह बाह्य विषयों से अलग किया गया अनुभव है — वही जानने की क्रिया, अपनी सामान्य आपूर्ति के बिना चलती हुई।",
  },

  "mandukya-5": {
    en: "Deep sleep is defined first by two absences — no desire, no dream — and then, unexpectedly, by a positive term: ānandamaya, made of bliss. The text is not claiming deep sleep is pleasant. It is pointing at something everyone reports and nobody examines: we say we slept well. That report requires that something was present to register the absence of disturbance. Nothing can be reported from a state in which nobody was.\n\nEkībhūta, 'become one', is the key word. In waking and dream, awareness is divided into knower and known, and every experience has that shape. In deep sleep the division collapses — but awareness does not. What remains is prajñānaghana, a solid mass of knowing with nothing whatever to know.\n\nThis is the third quarter, not the fourth, and holding that line is the whole point of what follows. Undifferentiated is not the same as free. Deep sleep is ignorance with its contents removed rather than ignorance ended, which is why one returns from it exactly as one entered — the same person, with the same confusions intact. Gauḍapāda calls this the seed state, laya, and warns explicitly against mistaking absorption for liberation.",
    kn: "ಸುಷುಪ್ತಿಯನ್ನು ಮೊದಲು ಎರಡು ಅಭಾವಗಳಿಂದ ವ್ಯಾಖ್ಯಾನಿಸಲಾಗಿದೆ — ಬಯಕೆಯಿಲ್ಲ, ಸ್ವಪ್ನವಿಲ್ಲ — ಆಮೇಲೆ ಅನಿರೀಕ್ಷಿತವಾಗಿ ಒಂದು ವಿಧ್ಯಾತ್ಮಕ ಪದದಿಂದ: 'ಆನಂದಮಯ'. ಸುಷುಪ್ತಿ ಸುಖಕರವೆಂದು ಪಠ್ಯ ಹೇಳುತ್ತಿಲ್ಲ. ಎಲ್ಲರೂ ವರದಿ ಮಾಡುವ ಆದರೆ ಯಾರೂ ಪರೀಕ್ಷಿಸದ ಒಂದನ್ನು ಅದು ತೋರಿಸುತ್ತಿದೆ: 'ಚೆನ್ನಾಗಿ ನಿದ್ರಿಸಿದೆ' ಎನ್ನುತ್ತೇವೆ. ಆ ವರದಿಗೆ, ವಿಘ್ನದ ಅಭಾವವನ್ನು ದಾಖಲಿಸಲು ಏನೋ ಇದ್ದಿರಬೇಕು. ಯಾರೂ ಇಲ್ಲದ ಸ್ಥಿತಿಯಿಂದ ಏನನ್ನೂ ವರದಿ ಮಾಡಲಾಗದು.\n\n'ಏಕೀಭೂತ' — ಒಂದಾಗಿಬಿಟ್ಟದ್ದು — ಎಂಬುದೇ ಕೀಲಿ ಪದ. ಜಾಗ್ರತ್ ಮತ್ತು ಸ್ವಪ್ನದಲ್ಲಿ ಅರಿವು ಜ್ಞಾತೃ-ಜ್ಞೇಯವಾಗಿ ವಿಭಜಿತ, ಮತ್ತು ಪ್ರತಿ ಅನುಭವಕ್ಕೂ ಆ ಆಕಾರವಿದೆ. ಸುಷುಪ್ತಿಯಲ್ಲಿ ಆ ವಿಭಜನೆ ಕುಸಿಯುತ್ತದೆ — ಆದರೆ ಅರಿವು ಕುಸಿಯುವುದಿಲ್ಲ. ಉಳಿಯುವುದು 'ಪ್ರಜ್ಞಾನಘನ', ತಿಳಿಯಲು ಏನೂ ಇಲ್ಲದ ತಿಳಿವಿನ ಘನರೂಪ.\n\nಇದು ಮೂರನೆಯ ಪಾದ, ನಾಲ್ಕನೆಯದಲ್ಲ, ಮತ್ತು ಆ ಗೆರೆಯನ್ನು ಹಿಡಿದಿಡುವುದೇ ಮುಂದಿನದರ ಸಾರ. ಭೇದವಿಲ್ಲದಿರುವುದು ಮುಕ್ತವಾಗಿರುವುದಲ್ಲ. ಸುಷುಪ್ತಿ ಅಜ್ಞಾನದ ಅಂತ್ಯವಲ್ಲ, ವಿಷಯಗಳನ್ನು ತೆಗೆದ ಅಜ್ಞಾನ — ಆದ್ದರಿಂದಲೇ ಪ್ರವೇಶಿಸಿದಂತೆಯೇ ಅದರಿಂದ ಹಿಂತಿರುಗುತ್ತೇವೆ, ಅದೇ ವ್ಯಕ್ತಿಯಾಗಿ, ಅದೇ ಭ್ರಮೆಗಳೊಂದಿಗೆ. ಗೌಡಪಾದರು ಇದನ್ನು ಬೀಜಾವಸ್ಥೆ, 'ಲಯ' ಎಂದು ಕರೆದು, ಲೀನತೆಯನ್ನು ಮುಕ್ತಿಯೆಂದು ತಪ್ಪಾಗಿ ತಿಳಿಯದಂತೆ ಸ್ಪಷ್ಟವಾಗಿ ಎಚ್ಚರಿಸುತ್ತಾರೆ.",
    hi: "सुषुप्ति की परिभाषा पहले दो अभावों से दी गई है — न कामना, न स्वप्न — और फिर अप्रत्याशित रूप से एक विधेय पद से: 'आनंदमय'। पाठ यह दावा नहीं कर रहा कि सुषुप्ति सुखद है। वह उस बात की ओर संकेत कर रहा है जिसे सब बताते हैं और कोई जाँचता नहीं: हम कहते हैं 'अच्छी नींद आई'। उस कथन के लिए आवश्यक है कि विघ्न के अभाव को दर्ज करने वाला कुछ उपस्थित रहा हो। जिस अवस्था में कोई था ही नहीं, उससे कुछ बताया नहीं जा सकता।\n\n'एकीभूत' कुंजी शब्द है। जाग्रत् और स्वप्न में चेतना ज्ञाता और ज्ञेय में विभाजित है, और हर अनुभव का यही आकार है। सुषुप्ति में वह विभाजन ढह जाता है — किंतु चेतना नहीं ढहती। शेष रहता है 'प्रज्ञानघन', जानने योग्य कुछ भी बिना, जानने का घन।\n\nयह तृतीय पाद है, चतुर्थ नहीं, और उस रेखा को थामे रखना ही आगे का सार है। अभेद होना मुक्त होना नहीं। सुषुप्ति अज्ञान का अंत नहीं, विषय हटा हुआ अज्ञान है — इसीलिए उससे हम वैसे ही लौटते हैं जैसे गए थे, वही व्यक्ति, वही भ्रम लिए। गौडपाद इसे बीजावस्था, 'लय' कहते हैं, और लीनता को मुक्ति समझने के विरुद्ध स्पष्ट चेतावनी देते हैं।",
  },

  "mandukya-6": {
    en: "Five theological titles land on Prājña, the deep-sleep quarter, and on first reading that is startling. Why should dreamless sleep be called the Lord of all, the knower of all, the inner controller?\n\nBecause this is the causal state. Waking and dream are where the world stands manifest; deep sleep is where it is held unmanifest, the way a seed holds a tree — everything that will appear is present without being distinguished. That is exactly what 'source of all' and 'the origin and dissolution of beings' mean. Śaṅkara reads Prājña here as Īśvara approached from the individual side: the same undifferentiated ground, called personal and sovereign when regarded as the cause of the world.\n\nNotice how far the text is willing to go. Antaryāmī, the inner controller, is the term the Bṛhadāraṇyaka uses for the highest reality; sarvajña and sarveśvara are the vocabulary of theism. Nothing is being withheld.\n\nAnd then notice where it stops. It has now said the most exalted things available about the third quarter, and it is still the third. The next mantra will deny every one of these titles by name. Building Prājña this high is what makes that denial mean something.",
    kn: "ಐದು ದೈವಿಕ ಬಿರುದುಗಳು ಸುಷುಪ್ತಿಯ ಪಾದವಾದ ಪ್ರಾಜ್ಞನ ಮೇಲೆ ಬೀಳುತ್ತವೆ, ಮತ್ತು ಮೊದಲ ಓದಿಗೆ ಅದು ಬೆಚ್ಚಿಬೀಳಿಸುತ್ತದೆ. ಸ್ವಪ್ನರಹಿತ ನಿದ್ರೆಯನ್ನು ಸರ್ವೇಶ್ವರ, ಸರ್ವಜ್ಞ, ಅಂತರ್ಯಾಮಿ ಎಂದು ಏಕೆ ಕರೆಯಬೇಕು?\n\nಏಕೆಂದರೆ ಇದು ಕಾರಣಾವಸ್ಥೆ. ಜಾಗ್ರತ್ ಮತ್ತು ಸ್ವಪ್ನದಲ್ಲಿ ಜಗತ್ತು ವ್ಯಕ್ತವಾಗಿ ನಿಂತಿದೆ; ಸುಷುಪ್ತಿಯಲ್ಲಿ ಅದು ಅವ್ಯಕ್ತವಾಗಿ ಹಿಡಿದಿಡಲ್ಪಟ್ಟಿದೆ — ಬೀಜವು ಮರವನ್ನು ಹಿಡಿದಿಟ್ಟಂತೆ; ಕಾಣಿಸಲಿರುವ ಎಲ್ಲವೂ ಭೇದವಿಲ್ಲದೆ ಇರುತ್ತದೆ. 'ಎಲ್ಲದರ ಮೂಲ', 'ಭೂತಗಳ ಉತ್ಪತ್ತಿ ಮತ್ತು ಲಯ' ಎಂಬುದರ ಅರ್ಥವೇ ಅದು. ಶಂಕರರು ಇಲ್ಲಿನ ಪ್ರಾಜ್ಞನನ್ನು ವ್ಯಷ್ಟಿಯ ಕಡೆಯಿಂದ ಸಮೀಪಿಸಿದ ಈಶ್ವರನೆಂದು ಓದುತ್ತಾರೆ: ಅದೇ ಭೇದರಹಿತ ಆಧಾರ, ಜಗತ್ಕಾರಣವೆಂದು ಪರಿಗಣಿಸಿದಾಗ ವ್ಯಕ್ತಿರೂಪದ ಮತ್ತು ಒಡೆಯನ ಹೆಸರು ಪಡೆದದ್ದು.\n\nಪಠ್ಯ ಎಷ್ಟು ದೂರ ಹೋಗಲು ಸಿದ್ಧವಿದೆ ಎಂಬುದನ್ನು ಗಮನಿಸಿ. 'ಅಂತರ್ಯಾಮೀ' ಎಂಬುದು ಬೃಹದಾರಣ್ಯಕವು ಪರಮ ಸತ್ಯಕ್ಕೆ ಬಳಸುವ ಪದ; 'ಸರ್ವಜ್ಞ', 'ಸರ್ವೇಶ್ವರ' ಆಸ್ತಿಕ್ಯದ ಶಬ್ದಸಂಪತ್ತು. ಏನನ್ನೂ ತಡೆಹಿಡಿದಿಲ್ಲ.\n\nಆಮೇಲೆ ಅದು ಎಲ್ಲಿ ನಿಲ್ಲುತ್ತದೆ ಎಂಬುದನ್ನು ಗಮನಿಸಿ. ಮೂರನೆಯ ಪಾದದ ಬಗ್ಗೆ ಲಭ್ಯವಿರುವ ಅತ್ಯುನ್ನತ ಮಾತುಗಳನ್ನು ಈಗ ಹೇಳಿಯಾಗಿದೆ, ಮತ್ತು ಅದು ಇನ್ನೂ ಮೂರನೆಯದೇ. ಮುಂದಿನ ಮಂತ್ರ ಈ ಪ್ರತಿಯೊಂದು ಬಿರುದನ್ನೂ ಹೆಸರಿಸಿ ನಿರಾಕರಿಸುತ್ತದೆ. ಪ್ರಾಜ್ಞನನ್ನು ಇಷ್ಟು ಎತ್ತರಕ್ಕೆ ಕಟ್ಟಿದ್ದೇ ಆ ನಿರಾಕರಣೆಗೆ ಅರ್ಥ ಕೊಡುತ್ತದೆ.",
    hi: "पाँच ईश्वरीय उपाधियाँ प्राज्ञ पर, अर्थात् सुषुप्ति के पाद पर पड़ती हैं, और पहली बार पढ़ने पर यह चौंकाता है। स्वप्नरहित नींद को सर्वेश्वर, सर्वज्ञ, अंतर्यामी क्यों कहा जाए?\n\nक्योंकि यह कारण अवस्था है। जाग्रत् और स्वप्न में जगत् व्यक्त खड़ा है; सुषुप्ति में वह अव्यक्त रूप में धारित है — जैसे बीज वृक्ष को धारण करता है; जो कुछ प्रकट होगा वह अभेद रूप में उपस्थित है। 'सबका स्रोत' और 'भूतों की उत्पत्ति और लय' का यही अर्थ है। शंकर यहाँ प्राज्ञ को व्यष्टि की ओर से पहुँचा गया ईश्वर पढ़ते हैं: वही अभेद आधार, जगत्कारण मानने पर व्यक्तिवाची और स्वामी का नाम पा लेता है।\n\nध्यान दें कि पाठ कितनी दूर जाने को तैयार है। 'अंतर्यामी' वही शब्द है जो बृहदारण्यक परम सत्य के लिए प्रयोग करता है; 'सर्वज्ञ' और 'सर्वेश्वर' आस्तिक शब्दावली हैं। कुछ भी रोका नहीं गया।\n\nऔर फिर देखें कि वह कहाँ रुकता है। तृतीय पाद के विषय में उपलब्ध उच्चतम बातें अब कही जा चुकीं, और वह अब भी तृतीय ही है। अगला मंत्र इनमें से हर उपाधि का नाम लेकर निषेध करेगा। प्राज्ञ को इतना ऊँचा खड़ा करना ही उस निषेध को अर्थ देता है।",
  },

  "mandukya-7": {
    en: "The most famous sentence in the Upaniṣads, and its method is pure negation carried out in a strict order.\n\nSix denials clear away the three states just established. Not inward-knowing — that was Taijasa. Not outward-knowing — Vaiśvānara. Not both, not a mass of awareness — and that fourth denial removes prajñānaghana, the exalted description given to deep sleep one mantra ago. The text builds Prājña up to Lord of all and then takes it down, so that the reader cannot come to rest in undifferentiation and call it freedom. Then not aware, not unaware, closing the last two exits.\n\nSix more negations follow, each shutting a route by which the mind takes hold: unseen, not transactable, ungraspable, without characteristic, unthinkable, unnameable. Nothing is left to grip. Avyavahārya is the sharpest of them — it means 'not to be dealt with', outside the whole economy of doing and getting.\n\nThen four positive terms arrive, and none is a description of an object. Ekātmapratyayasāra: its essence is the certainty that there is one Self. Prapañcopaśama: the manifold has come to rest. Śānta, śiva, advaita. And turīya means only 'the fourth' — no name of its own, because it is not a further state alongside the other three but what all three are made of.",
    kn: "ಉಪನಿಷತ್ತುಗಳಲ್ಲಿ ಅತ್ಯಂತ ಪ್ರಸಿದ್ಧ ವಾಕ್ಯ, ಮತ್ತು ಅದರ ವಿಧಾನ ಕಟ್ಟುನಿಟ್ಟಾದ ಕ್ರಮದಲ್ಲಿ ನಡೆಸಿದ ಶುದ್ಧ ನಿಷೇಧ.\n\nಆರು ನಿಷೇಧಗಳು ಈಗಷ್ಟೇ ಸ್ಥಾಪಿಸಿದ ಮೂರು ಅವಸ್ಥೆಗಳನ್ನು ತೊಡೆದುಹಾಕುತ್ತವೆ. ಒಳಮುಖ ಪ್ರಜ್ಞೆಯಲ್ಲ — ಅದು ತೈಜಸ. ಹೊರಮುಖ ಪ್ರಜ್ಞೆಯಲ್ಲ — ವೈಶ್ವಾನರ. ಎರಡೂ ಅಲ್ಲ, ಪ್ರಜ್ಞಾನಘನವೂ ಅಲ್ಲ — ಈ ನಾಲ್ಕನೆಯ ನಿಷೇಧವು ಒಂದು ಮಂತ್ರದ ಹಿಂದೆ ಸುಷುಪ್ತಿಗೆ ಕೊಟ್ಟ ಉನ್ನತ ವರ್ಣನೆಯನ್ನೇ ತೆಗೆದುಹಾಕುತ್ತದೆ. ಪಠ್ಯವು ಪ್ರಾಜ್ಞನನ್ನು ಸರ್ವೇಶ್ವರನವರೆಗೆ ಏರಿಸಿ ಆಮೇಲೆ ಇಳಿಸುತ್ತದೆ, ಓದುಗನು ಭೇದರಾಹಿತ್ಯದಲ್ಲಿ ನಿಂತು ಅದನ್ನೇ ಮುಕ್ತಿಯೆಂದು ಕರೆಯದಂತೆ. ಆಮೇಲೆ ಪ್ರಜ್ಞವೂ ಅಲ್ಲ, ಅಪ್ರಜ್ಞವೂ ಅಲ್ಲ — ಕೊನೆಯ ಎರಡು ದಾರಿಗಳೂ ಮುಚ್ಚಿದವು.\n\nಇನ್ನೂ ಆರು ನಿಷೇಧಗಳು ಬರುತ್ತವೆ, ಪ್ರತಿಯೊಂದೂ ಮನಸ್ಸು ಹಿಡಿಯುವ ಒಂದೊಂದು ದಾರಿಯನ್ನು ಮುಚ್ಚುತ್ತದೆ: ಅದೃಷ್ಟ, ಅವ್ಯವಹಾರ್ಯ, ಅಗ್ರಾಹ್ಯ, ಅಲಕ್ಷಣ, ಅಚಿಂತ್ಯ, ಅವ್ಯಪದೇಶ್ಯ. ಹಿಡಿಯಲು ಏನೂ ಉಳಿಯುವುದಿಲ್ಲ. 'ಅವ್ಯವಹಾರ್ಯ' ಇವುಗಳಲ್ಲಿ ಅತ್ಯಂತ ತೀಕ್ಷ್ಣ — ವ್ಯವಹಾರಕ್ಕೆ ಸಿಗದ್ದು, ಮಾಡುವಿಕೆ-ಪಡೆಯುವಿಕೆಯ ಇಡೀ ವ್ಯವಸ್ಥೆಯ ಹೊರಗಿನದು.\n\nಆಮೇಲೆ ನಾಲ್ಕು ವಿಧ್ಯಾತ್ಮಕ ಪದಗಳು ಬರುತ್ತವೆ, ಯಾವುದೂ ವಸ್ತುವಿನ ವರ್ಣನೆಯಲ್ಲ. 'ಏಕಾತ್ಮಪ್ರತ್ಯಯಸಾರ': ಒಂದೇ ಆತ್ಮವಿದೆ ಎಂಬ ನಿಶ್ಚಯವೇ ಅದರ ಸಾರ. 'ಪ್ರಪಂಚೋಪಶಮ': ಪ್ರಪಂಚ ಶಮನಗೊಂಡಿದೆ. ಶಾಂತ, ಶಿವ, ಅದ್ವೈತ. ಮತ್ತು 'ತುರೀಯ' ಎಂದರೆ ಕೇವಲ 'ನಾಲ್ಕನೆಯದು' — ತನ್ನದೇ ಹೆಸರಿಲ್ಲ, ಏಕೆಂದರೆ ಅದು ಉಳಿದ ಮೂರರ ಪಕ್ಕದ ಇನ್ನೊಂದು ಅವಸ್ಥೆಯಲ್ಲ, ಆ ಮೂರೂ ಯಾವುದರಿಂದ ಆಗಿವೆಯೋ ಅದು.",
    hi: "उपनिषदों का सर्वाधिक प्रसिद्ध वाक्य, और उसकी विधि कठोर क्रम में किया गया शुद्ध निषेध है।\n\nछह निषेध अभी-अभी स्थापित तीनों अवस्थाओं को हटा देते हैं। अंतर्मुख प्रज्ञा नहीं — वह तैजस था। बहिर्मुख प्रज्ञा नहीं — वैश्वानर। दोनों नहीं, प्रज्ञानघन भी नहीं — और यह चौथा निषेध उसी उच्च वर्णन को हटाता है जो एक मंत्र पहले सुषुप्ति को दिया गया था। पाठ प्राज्ञ को सर्वेश्वर तक चढ़ाकर फिर उतार देता है, ताकि पाठक अभेद में ठहरकर उसी को मुक्ति न कह बैठे। फिर न प्रज्ञ, न अप्रज्ञ — अंतिम दो निकास भी बंद।\n\nछह और निषेध आते हैं, हर एक उस मार्ग को बंद करता है जिससे मन पकड़ता है: अदृष्ट, अव्यवहार्य, अग्राह्य, अलक्षण, अचिंत्य, अव्यपदेश्य। पकड़ने को कुछ नहीं बचता। 'अव्यवहार्य' इनमें सबसे तीक्ष्ण है — जिससे व्यवहार न हो सके, करने-पाने की समस्त अर्थव्यवस्था से बाहर।\n\nफिर चार विधेय पद आते हैं, और कोई भी किसी वस्तु का वर्णन नहीं। 'एकात्मप्रत्ययसार': एक ही आत्मा है, यह निश्चय ही उसका सार। 'प्रपंचोपशम': प्रपंच शांत हो गया। शांत, शिव, अद्वैत। और 'तुरीय' का अर्थ केवल 'चतुर्थ' है — उसका अपना कोई नाम नहीं, क्योंकि वह अन्य तीन के साथ की कोई और अवस्था नहीं, बल्कि वही है जिससे तीनों बनी हैं।",
  },

  "mandukya-8": {
    en: "The hinge of the text. Everything so far has analysed consciousness into four; now the syllable is analysed the same way, and the two analyses are declared to be one.\n\nThe phrasing is careful and deliberately reciprocal: pādā mātrā mātrāś ca pādāḥ — the quarters are the measures and the measures are the quarters. Said only one way round it would be symbolism, the sound standing for the states. Said both ways it is identity. A symbol would leave two things in place, one pointing at the other; this says there is one structure, met either by attending to awareness or by attending to sound.\n\nThat is what makes Om a practice rather than an emblem. Chanting it is not recalling a doctrine or invoking a deity. It is traversing the same four-part structure in a medium slow enough and gross enough to be noticed — A opening at the back of the mouth, U rolling forward, M closing at the lips, and then the silence.\n\nŚaṅkara notes that this is why the Māṇḍūkya can be called complete in twelve sentences. It has given the analysis and then given the instrument for verifying it, and the instrument is available to anyone with a voice.",
    kn: "ಪಠ್ಯದ ತಿರುಗುಗಂಬ. ಇಲ್ಲಿಯವರೆಗೆ ಪ್ರಜ್ಞೆಯನ್ನು ನಾಲ್ಕಾಗಿ ವಿಶ್ಲೇಷಿಸಲಾಗಿತ್ತು; ಈಗ ಅಕ್ಷರವನ್ನೂ ಅದೇ ರೀತಿ ವಿಶ್ಲೇಷಿಸಿ, ಎರಡೂ ವಿಶ್ಲೇಷಣೆಗಳು ಒಂದೇ ಎಂದು ಘೋಷಿಸಲಾಗಿದೆ.\n\nಪದಪ್ರಯೋಗ ಎಚ್ಚರಿಕೆಯದು ಮತ್ತು ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಪರಸ್ಪರವಾದದ್ದು: 'ಪಾದಾ ಮಾತ್ರಾ ಮಾತ್ರಾಶ್ಚ ಪಾದಾಃ' — ಪಾದಗಳೇ ಮಾತ್ರೆಗಳು ಮತ್ತು ಮಾತ್ರೆಗಳೇ ಪಾದಗಳು. ಒಂದೇ ದಿಕ್ಕಿನಲ್ಲಿ ಹೇಳಿದ್ದರೆ ಅದು ಸಂಕೇತವಾಗುತ್ತಿತ್ತು, ನಾದವು ಅವಸ್ಥೆಗಳಿಗೆ ಪ್ರತಿನಿಧಿ. ಎರಡೂ ದಿಕ್ಕಿನಲ್ಲಿ ಹೇಳಿದ್ದರಿಂದ ಅದು ಅಭೇದ. ಸಂಕೇತವಾಗಿದ್ದರೆ ಎರಡು ವಸ್ತುಗಳು ಉಳಿಯುತ್ತಿದ್ದವು, ಒಂದು ಇನ್ನೊಂದನ್ನು ತೋರಿಸುತ್ತಾ; ಇಲ್ಲಿ ಹೇಳುತ್ತಿರುವುದು ಒಂದೇ ರಚನೆಯಿದೆ, ಅರಿವಿನ ಕಡೆ ಗಮನ ಕೊಟ್ಟೂ ನಾದದ ಕಡೆ ಗಮನ ಕೊಟ್ಟೂ ಅದನ್ನೇ ಎದುರುಗೊಳ್ಳಬಹುದು ಎಂದು.\n\nಓಂಕಾರವನ್ನು ಲಾಂಛನವಲ್ಲ, ಸಾಧನೆಯನ್ನಾಗಿ ಮಾಡುವುದು ಇದೇ. ಅದನ್ನು ಜಪಿಸುವುದು ಸಿದ್ಧಾಂತವನ್ನು ನೆನಪಿಸಿಕೊಳ್ಳುವುದೂ ಅಲ್ಲ, ದೇವತೆಯನ್ನು ಆವಾಹಿಸುವುದೂ ಅಲ್ಲ. ಗಮನಿಸಲು ಸಾಕಷ್ಟು ನಿಧಾನವಾದ ಮತ್ತು ಸ್ಥೂಲವಾದ ಮಾಧ್ಯಮದಲ್ಲಿ ಅದೇ ಚತುಷ್ಪಾದ ರಚನೆಯನ್ನು ದಾಟುವುದು — ಅಕಾರ ಬಾಯಿಯ ಹಿಂದೆ ತೆರೆಯುತ್ತಾ, ಉಕಾರ ಮುಂದೆ ಉರುಳುತ್ತಾ, ಮಕಾರ ತುಟಿಗಳಲ್ಲಿ ಮುಚ್ಚುತ್ತಾ, ಆಮೇಲೆ ಮೌನ.\n\nಹನ್ನೆರಡು ವಾಕ್ಯಗಳಲ್ಲಿ ಮಾಂಡೂಕ್ಯವನ್ನು ಪರಿಪೂರ್ಣವೆಂದು ಕರೆಯಲು ಇದೇ ಕಾರಣವೆಂದು ಶಂಕರರು ಗಮನಿಸುತ್ತಾರೆ. ಅದು ವಿಶ್ಲೇಷಣೆಯನ್ನು ಕೊಟ್ಟು ಆಮೇಲೆ ಅದನ್ನು ಪರೀಕ್ಷಿಸುವ ಸಾಧನವನ್ನೂ ಕೊಟ್ಟಿದೆ, ಮತ್ತು ಆ ಸಾಧನ ಧ್ವನಿಯಿರುವ ಪ್ರತಿಯೊಬ್ಬರಿಗೂ ದೊರೆಯುತ್ತದೆ.",
    hi: "पाठ की धुरी। अब तक चेतना का चार में विश्लेषण हुआ; अब अक्षर का भी वैसे ही विश्लेषण होता है, और दोनों विश्लेषण एक घोषित किए जाते हैं।\n\nशब्दयोजना सावधान और जानबूझकर पारस्परिक है: 'पादा मात्रा मात्राश्च पादाः' — पाद ही मात्राएँ और मात्राएँ ही पाद। केवल एक ओर से कहा जाता तो वह प्रतीकवाद होता, नाद अवस्थाओं का प्रतिनिधि। दोनों ओर से कहने पर वह अभेद है। प्रतीक होता तो दो वस्तुएँ बनी रहतीं, एक दूसरे की ओर संकेत करती; यहाँ कहा जा रहा है कि संरचना एक ही है, जिससे चेतना पर ध्यान देकर भी और नाद पर ध्यान देकर भी भेंट होती है।\n\nयही ॐ को प्रतीक नहीं, साधना बनाता है। उसका जप न सिद्धांत का स्मरण है न देवता का आवाहन। वह उसी चतुष्पाद संरचना को इतने धीमे और स्थूल माध्यम में पार करना है कि उसे लक्षित किया जा सके — अकार मुख के पीछे खुलता, उकार आगे लुढ़कता, मकार ओष्ठों पर बंद होता, और फिर मौन।\n\nशंकर लक्षित करते हैं कि बारह वाक्यों में माण्डूक्य को पूर्ण क्यों कहा जाता है। उसने विश्लेषण दिया और फिर उसे जाँचने का उपकरण भी दिया, और वह उपकरण हर उस व्यक्ति को उपलब्ध है जिसके पास वाणी है।",
  },

  "mandukya-9": {
    en: "The correspondence is argued etymologically, which is how these texts establish that a mapping is not arbitrary. A is linked to āpti, pervading or obtaining, and to ādimattva, being first.\n\nBoth fit. Waking pervades the other states in a specific sense: you enter dream and deep sleep from it and return to it, and it is the state in which the other two are remembered and discussed. And it comes first in any account of experience, because it is where accounts are given.\n\nBy modern standards the etymology is loose, and it is worth being clear about that rather than pretending otherwise. What matters is the form of the claim. The letter is not assigned to the state by convention but derived from it, so a practitioner sounding A is meant to feel why it belongs where it does. The technique runs through the Brāhmaṇa literature and is a way of reasoning, not a decoration.\n\nThe promised fruit is worth noting for its modesty: all desires, and precedence. These are worldly attainments and the text says so plainly, without apology and without inflation. The larger fruit is deliberately held back for the twelfth mantra, where it will not be a fruit at all.",
    kn: "ಈ ಸಂವಾದವನ್ನು ವ್ಯುತ್ಪತ್ತಿಯ ಮೂಲಕ ಮಂಡಿಸಲಾಗಿದೆ — ಈ ಹೊಂದಾಣಿಕೆ ಯಾದೃಚ್ಛಿಕವಲ್ಲ ಎಂದು ಇಂಥ ಪಠ್ಯಗಳು ಸ್ಥಾಪಿಸುವ ಕ್ರಮವೇ ಇದು. ಅಕಾರವನ್ನು 'ಆಪ್ತಿ' ಅಂದರೆ ವ್ಯಾಪಿಸುವಿಕೆ ಅಥವಾ ಪಡೆಯುವಿಕೆಗೂ, 'ಆದಿಮತ್ತ್ವ' ಅಂದರೆ ಮೊದಲಿಗನಾಗಿರುವುದಕ್ಕೂ ಜೋಡಿಸಲಾಗಿದೆ.\n\nಎರಡೂ ಹೊಂದುತ್ತವೆ. ಜಾಗ್ರತ್ ಉಳಿದ ಅವಸ್ಥೆಗಳನ್ನು ಒಂದು ನಿರ್ದಿಷ್ಟ ಅರ್ಥದಲ್ಲಿ ವ್ಯಾಪಿಸುತ್ತದೆ: ಸ್ವಪ್ನ ಮತ್ತು ಸುಷುಪ್ತಿಗೆ ಅದರಿಂದಲೇ ಪ್ರವೇಶಿಸಿ ಅದಕ್ಕೇ ಹಿಂತಿರುಗುತ್ತೇವೆ, ಮತ್ತು ಉಳಿದೆರಡನ್ನೂ ನೆನಪಿಸಿಕೊಂಡು ಚರ್ಚಿಸುವುದೂ ಅದರಲ್ಲಿಯೇ. ಮತ್ತು ಅನುಭವದ ಯಾವ ವಿವರಣೆಯಲ್ಲಿಯೂ ಅದು ಮೊದಲು ಬರುತ್ತದೆ, ಏಕೆಂದರೆ ವಿವರಣೆಗಳು ಕೊಡಲ್ಪಡುವುದೇ ಅಲ್ಲಿ.\n\nಆಧುನಿಕ ಮಾನದಂಡಗಳಿಂದ ಈ ವ್ಯುತ್ಪತ್ತಿ ಸಡಿಲ, ಮತ್ತು ಅದನ್ನು ಮುಚ್ಚಿಡದೆ ಸ್ಪಷ್ಟವಾಗಿ ಹೇಳುವುದು ಯೋಗ್ಯ. ಮುಖ್ಯವಾದದ್ದು ಪ್ರತಿಪಾದನೆಯ ರೂಪ. ಅಕ್ಷರವನ್ನು ಅವಸ್ಥೆಗೆ ಸಂಪ್ರದಾಯದಿಂದ ನಿಗದಿಪಡಿಸಿಲ್ಲ, ಅದರಿಂದಲೇ ನಿಷ್ಪನ್ನಗೊಳಿಸಲಾಗಿದೆ — ಆದ್ದರಿಂದ ಅಕಾರವನ್ನು ಉಚ್ಚರಿಸುವ ಸಾಧಕನು ಅದು ಅಲ್ಲಿಯೇ ಏಕೆ ಸೇರುತ್ತದೆಂದು ಅನುಭವಿಸಬೇಕು. ಈ ತಂತ್ರ ಬ್ರಾಹ್ಮಣ ಸಾಹಿತ್ಯದಾದ್ಯಂತ ಸಾಗುತ್ತದೆ ಮತ್ತು ಅದು ಅಲಂಕಾರವಲ್ಲ, ತರ್ಕಿಸುವ ಕ್ರಮ.\n\nವಾಗ್ದಾನಿಸಿದ ಫಲದ ಸಾಧಾರಣತೆ ಗಮನಾರ್ಹ: ಎಲ್ಲ ಕಾಮನೆಗಳು, ಮತ್ತು ಪ್ರಾಧಾನ್ಯ. ಇವು ಲೌಕಿಕ ಸಿದ್ಧಿಗಳು ಮತ್ತು ಪಠ್ಯ ಅದನ್ನು ಕ್ಷಮೆಯಿಲ್ಲದೆ, ಉತ್ಪ್ರೇಕ್ಷೆಯಿಲ್ಲದೆ ನೇರವಾಗಿ ಹೇಳುತ್ತದೆ. ದೊಡ್ಡ ಫಲವನ್ನು ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಹನ್ನೆರಡನೆಯ ಮಂತ್ರಕ್ಕೆ ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ, ಮತ್ತು ಅಲ್ಲಿ ಅದು ಫಲವೇ ಆಗಿರುವುದಿಲ್ಲ.",
    hi: "यह संगति व्युत्पत्ति से सिद्ध की गई है — ऐसे पाठ यही विधि अपनाते हैं यह दिखाने को कि यह मेल मनमाना नहीं। अकार को 'आप्ति' अर्थात् व्याप्ति या प्राप्ति से, और 'आदिमत्त्व' अर्थात् प्रथम होने से जोड़ा गया है।\n\nदोनों बैठते हैं। जाग्रत् अन्य अवस्थाओं में एक विशिष्ट अर्थ में व्याप्त है: स्वप्न और सुषुप्ति में उसी से प्रवेश होता है और उसी में लौटना होता है, और उन दोनों का स्मरण तथा विवेचन भी उसी में होता है। और अनुभव के किसी भी विवरण में वह पहले आती है, क्योंकि विवरण दिए ही वहाँ जाते हैं।\n\nआधुनिक मानदंडों से यह व्युत्पत्ति ढीली है, और इसे छिपाने के बजाय स्पष्ट कह देना उचित है। महत्वपूर्ण दावे का रूप है। अक्षर अवस्था को रूढ़ि से नहीं सौंपा गया, उसी से निष्पन्न किया गया है — इसलिए अकार का उच्चारण करने वाले साधक को अनुभव होना चाहिए कि वह वहीं क्यों बैठता है। यह युक्ति ब्राह्मण साहित्य भर में चलती है और वह अलंकार नहीं, तर्क करने का ढंग है।\n\nप्रतिज्ञात फल की सादगी ध्यान देने योग्य है: सब कामनाएँ, और प्रथमता। ये लौकिक सिद्धियाँ हैं और पाठ यह बिना क्षमा और बिना अतिशयोक्ति के सीधे कहता है। बड़ा फल जानबूझकर बारहवें मंत्र के लिए रोका गया है, और वहाँ वह फल होगा ही नहीं।",
  },

  "mandukya-10": {
    en: "Again the derivation carries the argument, and this time it is unusually apt. U is the middle sound of Om, formed between the openness of A and the closure of M — and dream is the middle state, between the outwardness of waking and the closure of deep sleep. Ubhayatva, 'partaking of both', names that position exactly.\n\nUtkarṣa, elevation, is the second derivation offered, and it fits the state rather than the sound. The dream state lifts awareness clear of gross objects without yet dissolving it, so it stands higher than waking in one specific respect: it shows consciousness operating without external supply. Whatever one finally makes of dream, it demonstrates that a complete world does not require material outside the knower.\n\nThe fruit is subtler than the first mantra's. Jñānasantati, the continuity of knowledge — not a possession but a thread that holds, an unbroken line of understanding rather than an acquisition. And samāna, becoming equal: not superior to others, which is what the first fruit offered.\n\nThe closing line about the family is a standard Vedic idiom for a result outlasting the individual. It should be read as saying the knowledge propagates, not as a claim about heredity.",
    kn: "ಇಲ್ಲಿಯೂ ವ್ಯುತ್ಪತ್ತಿಯೇ ವಾದವನ್ನು ಹೊತ್ತಿದೆ, ಮತ್ತು ಈ ಬಾರಿ ಅದು ಅಸಾಧಾರಣವಾಗಿ ಸೂಕ್ತ. ಉಕಾರ ಓಂಕಾರದ ಮಧ್ಯನಾದ, ಅಕಾರದ ತೆರೆದಿರುವಿಕೆ ಮತ್ತು ಮಕಾರದ ಮುಚ್ಚುವಿಕೆಯ ನಡುವೆ ರೂಪುಗೊಂಡದ್ದು — ಮತ್ತು ಸ್ವಪ್ನ ಮಧ್ಯದ ಅವಸ್ಥೆ, ಜಾಗ್ರತ್ತಿನ ಹೊರಮುಖತೆ ಮತ್ತು ಸುಷುಪ್ತಿಯ ಮುಚ್ಚುವಿಕೆಯ ನಡುವೆ. 'ಉಭಯತ್ವ' ಎಂಬುದು ಆ ಸ್ಥಾನವನ್ನು ನಿಖರವಾಗಿ ಹೆಸರಿಸುತ್ತದೆ.\n\n'ಉತ್ಕರ್ಷ' ಎಂಬುದು ಕೊಟ್ಟ ಎರಡನೆಯ ನಿಷ್ಪತ್ತಿ, ಮತ್ತು ಅದು ನಾದಕ್ಕಿಂತ ಅವಸ್ಥೆಗೆ ಹೊಂದುತ್ತದೆ. ಸ್ವಪ್ನಾವಸ್ಥೆ ಅರಿವನ್ನು ಸ್ಥೂಲ ವಿಷಯಗಳಿಂದ ಮೇಲೆತ್ತುತ್ತದೆ, ಆದರೆ ಇನ್ನೂ ಕರಗಿಸುವುದಿಲ್ಲ; ಆದ್ದರಿಂದ ಒಂದು ನಿರ್ದಿಷ್ಟ ಅರ್ಥದಲ್ಲಿ ಅದು ಜಾಗ್ರತ್ತಿಗಿಂತ ಎತ್ತರದಲ್ಲಿ ನಿಲ್ಲುತ್ತದೆ: ಹೊರಗಿನ ಪೂರೈಕೆಯಿಲ್ಲದೆ ಪ್ರಜ್ಞೆ ಕೆಲಸ ಮಾಡುವುದನ್ನು ಅದು ತೋರಿಸುತ್ತದೆ. ಸ್ವಪ್ನದ ಬಗ್ಗೆ ಕೊನೆಗೆ ಏನೇ ಅಭಿಪ್ರಾಯ ಬಂದರೂ, ಸಂಪೂರ್ಣ ಜಗತ್ತೊಂದಕ್ಕೆ ಜ್ಞಾತೃವಿನ ಹೊರಗಿನ ದ್ರವ್ಯ ಬೇಕಿಲ್ಲ ಎಂಬುದನ್ನು ಅದು ತೋರಿಸುತ್ತದೆ.\n\nಫಲ ಮೊದಲ ಮಂತ್ರದ್ದಕ್ಕಿಂತ ಸೂಕ್ಷ್ಮ. 'ಜ್ಞಾನಸಂತತಿ', ಜ್ಞಾನದ ನಿರಂತರತೆ — ಸ್ವತ್ತಲ್ಲ, ಹಿಡಿದಿಡುವ ಎಳೆ; ಸಂಪಾದನೆಯಲ್ಲ, ತಿಳಿವಳಿಕೆಯ ಅಖಂಡ ಸಾಲು. ಮತ್ತು 'ಸಮಾನ', ಸಮಾನನಾಗುವುದು: ಇತರರಿಗಿಂತ ಶ್ರೇಷ್ಠನಲ್ಲ — ಮೊದಲ ಫಲ ಕೊಟ್ಟದ್ದು ಅದನ್ನೇ.\n\nವಂಶದ ಕುರಿತ ಕೊನೆಯ ಸಾಲು ವ್ಯಕ್ತಿಯನ್ನು ಮೀರಿ ಉಳಿಯುವ ಫಲಕ್ಕೆ ಪ್ರಮಾಣಿತ ವೈದಿಕ ನುಡಿಗಟ್ಟು. ಜ್ಞಾನ ಮುಂದುವರಿಯುತ್ತದೆ ಎಂದು ಓದಬೇಕು, ಅನುವಂಶಿಕತೆಯ ಪ್ರತಿಪಾದನೆಯೆಂದಲ್ಲ.",
    hi: "यहाँ भी व्युत्पत्ति ही तर्क उठाए है, और इस बार वह असाधारण रूप से उपयुक्त है। उकार ॐकार का मध्य नाद है, अकार के खुलेपन और मकार के बंद होने के बीच बना — और स्वप्न मध्य अवस्था है, जाग्रत् की बहिर्मुखता और सुषुप्ति के बंद होने के बीच। 'उभयत्व' उसी स्थिति को ठीक-ठीक नामित करता है।\n\n'उत्कर्ष' दूसरी दी गई निष्पत्ति है, और वह नाद से अधिक अवस्था पर बैठती है। स्वप्नावस्था चेतना को स्थूल विषयों से ऊपर उठाती है, पर अभी विलीन नहीं करती; अतः एक विशिष्ट अर्थ में वह जाग्रत् से ऊँची खड़ी है: वह चेतना को बाहरी आपूर्ति के बिना काम करते दिखाती है। स्वप्न के विषय में अंततः जो भी मत बने, वह यह दिखाता है कि पूर्ण जगत् के लिए ज्ञाता के बाहर की सामग्री आवश्यक नहीं।\n\nफल पहले मंत्र से सूक्ष्म है। 'ज्ञानसंतति', ज्ञान की निरंतरता — संपत्ति नहीं, थामने वाला सूत्र; अर्जन नहीं, समझ की अखंड रेखा। और 'समान', समान होना: औरों से श्रेष्ठ नहीं — पहला फल वही देता था।\n\nकुल वाली अंतिम पंक्ति व्यक्ति से आगे टिकने वाले फल के लिए मानक वैदिक मुहावरा है। इसे यह कहते हुए पढ़ना चाहिए कि ज्ञान आगे चलता है, आनुवंशिकता का दावा मानकर नहीं।",
  },

  "mandukya-11": {
    en: "M closes the syllable. The lips come together and the sound ends — and deep sleep is where the world closes and returns to its unmanifest condition. Apīti, merging, is the exact word for what happens to both, and the derivation needs no stretching.\n\nThe first derivation, miti, is the more interesting of the two. To measure something is to take its whole extent at once rather than piece by piece. Deep sleep does that to the world: everything is present there, undivided, the way a total is present without its parts being enumerated. Śaṅkara draws out the corn-measure image — grain poured into a vessel is all there, but nothing in it is distinguished.\n\nWith this the three sounded measures are exhausted, and so are the three states. Every quarter with a name, a faculty and a fruit has now been given.\n\nWhat comes next is the mantra the whole text has been arranged to arrive at, and it is about what is left when the sound stops. Note that the text has spent eleven mantras building a structure it is about to say nothing is outside of — which is why the twelfth cannot be a summary.",
    kn: "ಮಕಾರ ಅಕ್ಷರವನ್ನು ಮುಚ್ಚುತ್ತದೆ. ತುಟಿಗಳು ಸೇರುತ್ತವೆ, ನಾದ ಮುಗಿಯುತ್ತದೆ — ಮತ್ತು ಸುಷುಪ್ತಿಯಲ್ಲಿಯೇ ಜಗತ್ತು ಮುಚ್ಚಿ ತನ್ನ ಅವ್ಯಕ್ತ ಸ್ಥಿತಿಗೆ ಮರಳುತ್ತದೆ. 'ಅಪೀತಿ' ಎಂಬುದು ಎರಡಕ್ಕೂ ಆಗುವುದನ್ನು ನಿಖರವಾಗಿ ಹೇಳುವ ಪದ, ಮತ್ತು ಈ ನಿಷ್ಪತ್ತಿಗೆ ಎಳೆದಾಟ ಬೇಕಿಲ್ಲ.\n\nಮೊದಲ ನಿಷ್ಪತ್ತಿಯಾದ 'ಮಿತಿ' ಎರಡರಲ್ಲಿ ಹೆಚ್ಚು ಕುತೂಹಲಕರ. ಒಂದನ್ನು ಅಳೆಯುವುದೆಂದರೆ ಅದರ ಪೂರ್ಣ ವ್ಯಾಪ್ತಿಯನ್ನು ತುಂಡುತುಂಡಾಗಿ ಅಲ್ಲ, ಒಟ್ಟಿಗೆ ತೆಗೆದುಕೊಳ್ಳುವುದು. ಸುಷುಪ್ತಿ ಜಗತ್ತಿಗೆ ಅದನ್ನೇ ಮಾಡುತ್ತದೆ: ಎಲ್ಲವೂ ಅಲ್ಲಿ ಅವಿಭಕ್ತವಾಗಿ ಇರುತ್ತದೆ, ಘಟಕಗಳನ್ನು ಎಣಿಸದೆಯೇ ಮೊತ್ತವೊಂದು ಇರುವಂತೆ. ಶಂಕರರು ಧಾನ್ಯದ ಅಳತೆಯ ಉಪಮೆಯನ್ನು ವಿಸ್ತರಿಸುತ್ತಾರೆ — ಪಾತ್ರೆಗೆ ಸುರಿದ ಕಾಳು ಎಲ್ಲವೂ ಅಲ್ಲಿದೆ, ಆದರೆ ಅದರಲ್ಲಿ ಯಾವುದೂ ಪ್ರತ್ಯೇಕವಾಗಿ ಗುರುತಿಸಲ್ಪಡುವುದಿಲ್ಲ.\n\nಇದರೊಂದಿಗೆ ಉಚ್ಚರಿಸಲ್ಪಡುವ ಮೂರು ಮಾತ್ರೆಗಳೂ ಮುಗಿದವು, ಮೂರು ಅವಸ್ಥೆಗಳೂ ಮುಗಿದವು. ಹೆಸರು, ಶಕ್ತಿ ಮತ್ತು ಫಲವಿರುವ ಪ್ರತಿ ಪಾದವನ್ನೂ ಈಗ ಕೊಟ್ಟಾಗಿದೆ.\n\nಮುಂದೆ ಬರುವುದೇ ಇಡೀ ಪಠ್ಯ ತಲುಪಲು ಜೋಡಿಸಲ್ಪಟ್ಟ ಮಂತ್ರ, ಮತ್ತು ಅದು ನಾದ ನಿಂತಾಗ ಏನು ಉಳಿಯುತ್ತದೆ ಎಂಬುದರ ಬಗ್ಗೆ. ಯಾವುದೂ ಇದರ ಹೊರಗಿಲ್ಲ ಎಂದು ಹೇಳಲಿರುವ ರಚನೆಯೊಂದನ್ನು ಕಟ್ಟಲು ಪಠ್ಯ ಹನ್ನೊಂದು ಮಂತ್ರಗಳನ್ನು ಕಳೆದಿದೆ ಎಂಬುದನ್ನು ಗಮನಿಸಿ — ಆದ್ದರಿಂದಲೇ ಹನ್ನೆರಡನೆಯದು ಸಾರಾಂಶವಾಗಿರಲಾರದು.",
    hi: "मकार अक्षर को बंद करता है। ओष्ठ मिलते हैं और नाद समाप्त होता है — और सुषुप्ति में ही जगत् बंद होकर अपनी अव्यक्त दशा में लौटता है। 'अपीति' दोनों के साथ जो होता है उसका ठीक शब्द है, और इस निष्पत्ति को खींचने की आवश्यकता नहीं।\n\nपहली निष्पत्ति 'मिति' दोनों में अधिक रोचक है। किसी वस्तु को मापना अर्थात् उसका पूरा विस्तार टुकड़ों में नहीं, एक साथ लेना। सुषुप्ति जगत् के साथ यही करती है: वहाँ सब कुछ अविभक्त उपस्थित है, जैसे योग उपस्थित होता है बिना उसके अंगों की गणना के। शंकर अन्न-माप की उपमा खोलते हैं — पात्र में डाला अनाज पूरा वहीं है, किंतु उसमें कुछ भी पृथक् नहीं पहचाना जाता।\n\nइसके साथ उच्चरित तीनों मात्राएँ समाप्त, और तीनों अवस्थाएँ भी। नाम, शक्ति और फल वाला हर पाद अब दिया जा चुका।\n\nआगे वही मंत्र है जिस तक पहुँचने के लिए सारा पाठ सजाया गया, और वह इस विषय में है कि नाद रुकने पर क्या शेष रहता है। ध्यान दें कि पाठ ने ग्यारह मंत्र उस संरचना को खड़ा करने में लगाए जिसके बारे में वह कहने वाला है कि कुछ भी उसके बाहर नहीं — इसीलिए बारहवाँ सारांश नहीं हो सकता।",
  },

  "mandukya-12": {
    en: "Amātra — measureless, without a mātrā. The first three quarters had sounds; the fourth has none. In practice this is the silence after the chant has ended, and the text is precise about what that silence is: not an absence, but the thing the three sounds were made of. You do not add a fourth noise. You stop, and what was there throughout is what remains.\n\nThe final clause is the most exact sentence in the Upaniṣad: saṃviśaty ātmanātmānam — enters the Self by the Self. Three occurrences of one word, functioning as agent, instrument and object, and no second thing anywhere in the grammar. There is no traveller, no vehicle, no destination. The sentence does not assert advaita; it performs it, and no paraphrase into a subject acting on an object can preserve that.\n\nNote also what is not promised. Mantras 9, 10 and 11 each ended with a fruit — desires, continuity of knowledge, absorption. This one ends with no fruit at all, because there is nobody left outside the result to receive it.\n\nThe doubled ya evaṃ veda ya evaṃ veda is the traditional marker that an Upaniṣad has finished. Here it is also the last thing a text about sound does before falling silent.",
    kn: "'ಅಮಾತ್ರ' — ಅಳತೆಯಿಲ್ಲದ್ದು, ಮಾತ್ರೆಯಿಲ್ಲದ್ದು. ಮೊದಲ ಮೂರು ಪಾದಗಳಿಗೆ ನಾದವಿತ್ತು; ನಾಲ್ಕನೆಯದಕ್ಕೆ ಇಲ್ಲ. ಆಚರಣೆಯಲ್ಲಿ ಇದು ಜಪ ಮುಗಿದ ನಂತರದ ಮೌನ, ಮತ್ತು ಆ ಮೌನ ಏನೆಂಬುದರ ಬಗ್ಗೆ ಪಠ್ಯ ನಿಖರ: ಅದು ಅಭಾವವಲ್ಲ, ಆ ಮೂರು ನಾದಗಳು ಯಾವುದರಿಂದ ಆಗಿದ್ದವೋ ಅದೇ. ನೀವು ನಾಲ್ಕನೆಯ ಸದ್ದನ್ನು ಸೇರಿಸುವುದಿಲ್ಲ. ನಿಲ್ಲಿಸುತ್ತೀರಿ, ಮತ್ತು ಉದ್ದಕ್ಕೂ ಇದ್ದದ್ದೇ ಉಳಿಯುತ್ತದೆ.\n\nಕೊನೆಯ ವಾಕ್ಯವೇ ಈ ಉಪನಿಷತ್ತಿನ ಅತ್ಯಂತ ನಿಖರವಾದದ್ದು: 'ಸಂವಿಶತ್ಯಾತ್ಮನಾಽಽತ್ಮಾನಮ್' — ಆತ್ಮದಿಂದ ಆತ್ಮವನ್ನು ಪ್ರವೇಶಿಸುತ್ತಾನೆ. ಒಂದೇ ಪದದ ಮೂರು ಪ್ರಯೋಗಗಳು, ಕರ್ತೃ, ಕರಣ ಮತ್ತು ಕರ್ಮವಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತಾ, ಮತ್ತು ವ್ಯಾಕರಣದಲ್ಲಿ ಎಲ್ಲಿಯೂ ಎರಡನೆಯ ವಸ್ತುವಿಲ್ಲ. ಪ್ರಯಾಣಿಕನಿಲ್ಲ, ವಾಹನವಿಲ್ಲ, ಗಮ್ಯವಿಲ್ಲ. ಈ ವಾಕ್ಯ ಅದ್ವೈತವನ್ನು ಪ್ರತಿಪಾದಿಸುವುದಿಲ್ಲ; ಅದನ್ನು ನಡೆಸಿ ತೋರಿಸುತ್ತದೆ, ಮತ್ತು ಕರ್ತೃ ಕರ್ಮದ ಮೇಲೆ ಕ್ರಿಯೆ ಮಾಡುವ ಯಾವ ಪುನರುಕ್ತಿಯೂ ಅದನ್ನು ಉಳಿಸಿಕೊಳ್ಳಲಾರದು.\n\nಏನನ್ನು ವಾಗ್ದಾನಿಸಿಲ್ಲ ಎಂಬುದನ್ನೂ ಗಮನಿಸಿ. ೯, ೧೦ ಮತ್ತು ೧೧ನೆಯ ಮಂತ್ರಗಳು ಪ್ರತಿಯೊಂದೂ ಒಂದು ಫಲದಿಂದ ಮುಗಿದವು — ಕಾಮನೆಗಳು, ಜ್ಞಾನಸಂತತಿ, ಲಯ. ಇದು ಯಾವ ಫಲವೂ ಇಲ್ಲದೆ ಮುಗಿಯುತ್ತದೆ, ಏಕೆಂದರೆ ಫಲವನ್ನು ಸ್ವೀಕರಿಸಲು ಫಲಿತಾಂಶದ ಹೊರಗೆ ಯಾರೂ ಉಳಿದಿಲ್ಲ.\n\nದ್ವಿಗುಣಗೊಂಡ 'ಯ ಏವಂ ವೇದ ಯ ಏವಂ ವೇದ' ಎಂಬುದು ಉಪನಿಷತ್ತು ಮುಗಿಯಿತೆಂಬ ಸಾಂಪ್ರದಾಯಿಕ ಗುರುತು. ಇಲ್ಲಿ ಅದು ನಾದದ ಕುರಿತ ಪಠ್ಯವೊಂದು ಮೌನವಾಗುವ ಮೊದಲು ಮಾಡುವ ಕೊನೆಯ ಕೆಲಸವೂ ಹೌದು.",
    hi: "'अमात्र' — मात्रारहित, मापरहित। पहले तीन पादों के नाद थे; चतुर्थ का नहीं। साधना में यह जप समाप्त होने के बाद का मौन है, और वह मौन क्या है इस पर पाठ सटीक है: वह अभाव नहीं, बल्कि वही है जिससे तीनों नाद बने थे। आप चौथा शब्द नहीं जोड़ते। आप रुकते हैं, और जो आरंभ से अंत तक था वही शेष रहता है।\n\nअंतिम वाक्य इस उपनिषद् का सर्वाधिक सटीक वाक्य है: 'संविशत्यात्मनाऽऽत्मानम्' — आत्मा से आत्मा में प्रवेश करता है। एक ही शब्द के तीन प्रयोग, कर्ता, करण और कर्म के रूप में कार्य करते हुए, और व्याकरण में कहीं दूसरी वस्तु नहीं। न यात्री, न वाहन, न गंतव्य। यह वाक्य अद्वैत का प्रतिपादन नहीं करता; उसे घटित कर देता है, और कर्ता का कर्म पर क्रिया करना — ऐसा कोई भी पुनर्कथन उसे बचा नहीं सकता।\n\nयह भी देखें कि क्या प्रतिज्ञात नहीं है। ९, १० और ११ — हर मंत्र एक फल पर समाप्त हुआ: कामनाएँ, ज्ञानसंतति, लय। यह किसी फल के बिना समाप्त होता है, क्योंकि फल पाने के लिए परिणाम के बाहर कोई शेष ही नहीं।\n\nद्विगुणित 'य एवं वेद य एवं वेद' यह पारंपरिक चिह्न है कि उपनिषद् पूर्ण हुआ। यहाँ वह नाद के विषय में लिखे पाठ का मौन होने से पूर्व का अंतिम कार्य भी है।",
  },
};
