import type { Locale } from "@/i18n/config";
import commons from "../../../public/images/practice/commons.json";

// ─────────────────────────────────────────────────────────
//  A photograph for each sitting.
//
//  Generated by scripts/images/fetch-commons.mjs, which asks the
//  Commons API for each file's real licence and author and refuses
//  anything not freely licensed.
//
//  The choices are literal rather than atmospheric: dawn on the
//  Ganges for the Gāyatrī, which is said at first light; rudrāksha
//  for the japa, which is what a mala is strung from; Arunachala for
//  self-enquiry, which is where it is at home. A stock photograph of
//  somebody meditating would say nothing true about any of them.
// ─────────────────────────────────────────────────────────

export interface PracticeImage {
  src: string;
  width: number;
  height: number;
  credit: string;
  sourceUrl: string;
  alt: Record<Locale, string>;
  position?: string;
}

const ALT: Record<string, Record<Locale, string>> = {
  gayatri: {
    en: "Dawn over the Ganges, the water still dark and the sky going pale",
    kn: "ಗಂಗೆಯ ಮೇಲೆ ಮುಂಜಾವು — ನೀರು ಇನ್ನೂ ಕಪ್ಪಗೆ, ಆಕಾಶ ಬೆಳ್ಳಗಾಗುತ್ತ",
    hi: "गंगा पर भोर — जल अभी श्याम, आकाश उजला होता हुआ",
  },
  "ganapati-japa": {
    en: "Rudraksha seeds, the kind a japa mala is strung from",
    kn: "ರುದ್ರಾಕ್ಷಿ ಬೀಜಗಳು — ಜಪಮಾಲೆ ಪೋಣಿಸುವುದು ಇವುಗಳಿಂದಲೇ",
    hi: "रुद्राक्ष बीज — जपमाला इन्हीं से पिरोई जाती है",
  },
  atharvashirsha: {
    en: "A brass temple lamp",
    kn: "ಹಿತ್ತಾಳೆಯ ದೇವಾಲಯದ ದೀಪ",
    hi: "पीतल का मंदिर दीप",
  },
  breath: {
    en: "A lake under mist at first light, the far shore not yet visible",
    kn: "ಮುಂಜಾವಿನ ಮಂಜಿನಲ್ಲಿ ಕೆರೆ — ಆಚೆಯ ದಡ ಇನ್ನೂ ಕಾಣದು",
    hi: "भोर के कुहरे में झील — दूसरा किनारा अभी अदृश्य",
  },
  silence: {
    en: "Arunachala, the hill at Tiruvannamalai",
    kn: "ಅರುಣಾಚಲ — ತಿರುವಣ್ಣಾಮಲೈನ ಬೆಟ್ಟ",
    hi: "अरुणाचल — तिरुवण्णामलै की पहाड़ी",
  },
};

type Entry = { src: string; width: number; height: number; credit: string; sourceUrl: string };
const FROM_COMMONS = commons as Record<string, Entry>;

const IMAGES: Record<string, PracticeImage> = {};
for (const [id, entry] of Object.entries(FROM_COMMONS)) {
  const alt = ALT[id];
  if (!alt) continue;
  IMAGES[id] = { ...entry, alt, position: "50% 50%" };
}

export function practiceImage(slug: string): PracticeImage | undefined {
  return IMAGES[slug];
}
