import type { Locale } from "@/i18n/config";
import commons from "../../../public/images/rituals/commons.json";

// ─────────────────────────────────────────────────────────
//  Pictures for the rites, where a good one exists.
//
//  Generated by scripts/images/fetch-commons.mjs, which asks the
//  Commons API for each file's real licence and author and refuses
//  anything not freely licensed.
//
//  **A rite with no picture is a valid state, and the commonest one
//  here.** The festivals could all be illustrated because a festival
//  is a public thing somebody photographed. A rite mostly is not:
//  nobody publishes a photograph of a jātakarma, and the few
//  photographs of a śrāddha that exist are of somebody's grief.
//  Where there is no picture the page shows the rite's name in the
//  reader's own script instead — the same fallback a temple with no
//  free photograph already uses.
//
//  **Alt text says what is in the frame**, not what the rite means,
//  and an id with no alt entry is treated as having no picture at
//  all. A photograph with no description is not an improvement on
//  none.
//
//  **Look at the picture before shipping it.** The festivals shipped
//  a museum exhibit label and a boy with a water pistol by filtering
//  on licence, size and filename and never opening the results.
//
//  Ids are ritual slugs, plus `g-<group>` for the plate at the head
//  of each group on the section's front page.
// ─────────────────────────────────────────────────────────

export interface RitualImage {
  src: string;
  width: number;
  height: number;
  credit: string;
  sourceUrl: string;
  alt: Record<Locale, string>;
  /** Which part of the frame a 4:3 or 16:9 crop must keep. */
  position?: string;
}

const ALT: Record<string, Record<Locale, string>> = {
  // ── the plate at the head of each group ────────────────────
  "g-samskara": {
    en: "A domestic rite in progress: an infant on a mat between a priest and the parents, with brass lamps lit",
    kn: "ಮನೆಯಲ್ಲಿ ನಡೆಯುತ್ತಿರುವ ಸಂಸ್ಕಾರ: ಚಾಪೆಯ ಮೇಲೆ ಮಗು, ಪುರೋಹಿತ ಮತ್ತು ತಂದೆತಾಯಿಯ ನಡುವೆ, ಹಿತ್ತಾಳೆಯ ದೀಪಗಳು ಉರಿಯುತ್ತಿವೆ",
    hi: "घर में चलता एक संस्कार: चटाई पर शिशु, पुरोहित और माता-पिता के बीच, पीतल के दीप जलते हुए",
  },
  "g-vrata": {
    en: "A crescent moon with Venus beside it, in a pale evening sky",
    kn: "ಮಸುಕಾದ ಸಂಜೆಯ ಆಕಾಶದಲ್ಲಿ ಚಂದ್ರನ ಕಲೆ, ಪಕ್ಕದಲ್ಲಿ ಶುಕ್ರ",
    hi: "धुँधले सांध्य आकाश में चंद्रकला, पास ही शुक्र",
  },
  "g-yajna": {
    en: "Wood burning in a portable havana kunda, turmeric and rose petals scattered on its rim, people seated behind it",
    kn: "ಸಾಗಿಸಬಹುದಾದ ಹವನ ಕುಂಡದಲ್ಲಿ ಉರಿಯುತ್ತಿರುವ ಕಟ್ಟಿಗೆ, ಅಂಚಿನಲ್ಲಿ ಚೆಲ್ಲಿದ ಅರಿಶಿನ ಮತ್ತು ಗುಲಾಬಿ ಎಸಳುಗಳು, ಹಿಂದೆ ಕುಳಿತ ಜನ",
    hi: "उठाकर ले जाने योग्य हवन कुंड में जलती लकड़ी, किनारे पर बिखरी हल्दी और गुलाब की पंखुड़ियाँ, पीछे बैठे लोग",
  },
  "g-pitru": {
    en: "A river ghat with a shrine tower above it, people gathered at the water",
    kn: "ನದೀ ದಡದ ಘಟ್ಟ, ಮೇಲೆ ಗುಡಿಯ ಗೋಪುರ, ನೀರಿನ ಬಳಿ ಸೇರಿದ ಜನ",
    hi: "नदी का घाट, ऊपर मंदिर का शिखर, जल के पास जुटे लोग",
  },
  "g-kshetra": {
    en: "The Chennakeshava temple at Anekere, seen inside its walled enclosure",
    kn: "ಅಣೆಕೆರೆಯ ಚೆನ್ನಕೇಶವ ದೇವಾಲಯ, ಪ್ರಾಕಾರದ ಒಳಗಿನಿಂದ",
    hi: "अनेकेरे का चेन्नकेशव मंदिर, अपने प्राकार के भीतर से",
  },

  // ── the rites ──────────────────────────────────────────────
  annaprashana: {
    en: "A family seated on the floor feeding a baby from a plate of rice",
    kn: "ನೆಲದ ಮೇಲೆ ಕುಳಿತ ಕುಟುಂಬ, ಅನ್ನದ ತಟ್ಟೆಯಿಂದ ಮಗುವಿಗೆ ಉಣಿಸುತ್ತಿದೆ",
    hi: "फर्श पर बैठा परिवार, चावल की थाली से शिशु को खिलाता हुआ",
  },
  upanayana: {
    en: "Boys in yellow seated around a kindled fire in a yard, mid-ceremony",
    kn: "ಅಂಗಳದಲ್ಲಿ ಹೊತ್ತಿಸಿದ ಅಗ್ನಿಯ ಸುತ್ತ ಹಳದಿ ಉಟ್ಟ ಹುಡುಗರು, ಸಮಾರಂಭದ ನಡುವೆ",
    hi: "आँगन में प्रज्वलित अग्नि के चारों ओर पीत वस्त्र में बालक, समारोह के बीच",
  },
  vivaha: {
    en: "The wedding fire burning high over its offerings, cloth and feet just visible behind it",
    kn: "ಅರ್ಪಣೆಗಳ ಮೇಲೆ ಎತ್ತರಕ್ಕೆ ಉರಿಯುತ್ತಿರುವ ವಿವಾಹಾಗ್ನಿ, ಹಿಂದೆ ಬಟ್ಟೆ ಮತ್ತು ಪಾದಗಳು ಮಸುಕಾಗಿ",
    hi: "अर्पणों के ऊपर ऊँची उठती विवाह-अग्नि, पीछे वस्त्र और पाँव धुँधले",
  },
  antyeshti: {
    en: "The Manikarnika cremation ghat at Varanasi seen from the river, smoke rising behind the boats",
    kn: "ನದಿಯಿಂದ ಕಾಣುವ ವಾರಾಣಸಿಯ ಮಣಿಕರ್ಣಿಕಾ ಸ್ಮಶಾನ ಘಟ್ಟ, ದೋಣಿಗಳ ಹಿಂದೆ ಏಳುತ್ತಿರುವ ಹೊಗೆ",
    hi: "नदी से दिखता वाराणसी का मणिकर्णिका घाट, नावों के पीछे उठता धुआँ",
  },
  sandhyavandana: {
    en: "Four students of a veda pāṭhaśāla seated in a row with water vessels before them",
    kn: "ವೇದ ಪಾಠಶಾಲೆಯ ನಾಲ್ವರು ವಿದ್ಯಾರ್ಥಿಗಳು ಸಾಲಾಗಿ ಕುಳಿತಿದ್ದಾರೆ, ಮುಂದೆ ನೀರಿನ ಪಾತ್ರೆಗಳು",
    hi: "वेद पाठशाला के चार विद्यार्थी पंक्ति में बैठे, सामने जल-पात्र",
  },
  puja: {
    en: "A hand holding an āratī plate with lit wicks and flowers on it",
    kn: "ಉರಿಯುತ್ತಿರುವ ಬತ್ತಿಗಳು ಮತ್ತು ಹೂವುಗಳಿರುವ ಆರತಿ ತಟ್ಟೆಯನ್ನು ಹಿಡಿದ ಕೈ",
    hi: "जलती बातियों और फूलों वाली आरती की थाली थामे एक हाथ",
  },
  ekadashi: {
    en: "A tulasī plant in its painted bṛndāvana pot, with lamps and vessels set before it",
    kn: "ಚಿತ್ರಿಸಿದ ಬೃಂದಾವನದಲ್ಲಿ ತುಳಸಿ ಗಿಡ, ಮುಂದೆ ದೀಪಗಳು ಮತ್ತು ಪಾತ್ರೆಗಳು",
    hi: "चित्रित बृंदावन में तुलसी का पौधा, सामने दीप और पात्र",
  },
  "sankashtahara-chaturthi": {
    en: "Steamed modakas on a plate",
    kn: "ತಟ್ಟೆಯಲ್ಲಿ ಹಬೆಯಲ್ಲಿ ಬೇಯಿಸಿದ ಮೋದಕಗಳು",
    hi: "थाली में भाप में पके मोदक",
  },
  agnihotra: {
    en: "A fire burning in a walled hearth indoors, tended by a man seated beside it",
    kn: "ಒಳಾಂಗಣದ ಕಟ್ಟಿದ ಕುಂಡದಲ್ಲಿ ಉರಿಯುತ್ತಿರುವ ಅಗ್ನಿ, ಪಕ್ಕದಲ್ಲಿ ಕುಳಿತವನು ಅದನ್ನು ನೋಡಿಕೊಳ್ಳುತ್ತಿದ್ದಾನೆ",
    hi: "भीतर बनी वेदी में जलती अग्नि, पास बैठा व्यक्ति उसकी देखभाल करता हुआ",
  },
  shraddha: {
    en: "An offering being made on the steps of a river ghat, plates and vessels set out on the stone",
    kn: "ನದೀ ಘಟ್ಟದ ಮೆಟ್ಟಿಲುಗಳ ಮೇಲೆ ನಡೆಯುತ್ತಿರುವ ಅರ್ಪಣೆ, ಕಲ್ಲಿನ ಮೇಲೆ ಜೋಡಿಸಿದ ತಟ್ಟೆ ಮತ್ತು ಪಾತ್ರೆಗಳು",
    hi: "नदी घाट की सीढ़ियों पर होता अर्पण, पत्थर पर सजी थालियाँ और पात्र",
  },
  "mahalaya-paksha": {
    en: "A crowd at the water's edge with offerings spread on the ground before them",
    kn: "ನೀರಿನ ಅಂಚಿನಲ್ಲಿ ಜನಸಂದಣಿ, ಮುಂದೆ ನೆಲದ ಮೇಲೆ ಹರಡಿದ ಅರ್ಪಣೆಗಳು",
    hi: "जल के किनारे भीड़, सामने ज़मीन पर फैले अर्पण",
  },
  pradakshina: {
    en: "A pillared circumambulation corridor at the Meenakshi temple, Madurai, its ceiling painted",
    kn: "ಮಧುರೈನ ಮೀನಾಕ್ಷಿ ದೇವಾಲಯದ ಕಂಬಗಳ ಪ್ರದಕ್ಷಿಣಾ ಪ್ರಾಕಾರ, ಚಿತ್ರಿಸಿದ ಮೇಲ್ಛಾವಣಿ",
    hi: "मदुरै के मीनाक्षी मंदिर का स्तंभयुक्त प्रदक्षिणा गलियारा, चित्रित छत",
  },
};

/**
 * Where a crop must hold, for the frames that are not centred. The
 * card is square and the hero is a wide band, so a tall photograph
 * loses a third of itself in each and has to say which third.
 */
const POSITION: Record<string, string> = {
  "g-vrata": "56% 34%", // the crescent sits high and right of centre
  "g-yajna": "50% 46%", // a portrait frame; the kunda is below the middle
  vivaha: "50% 56%", // the fire, not the dark ceiling above it
  antyeshti: "50% 44%",
};

type Entry = { src: string; width: number; height: number; credit: string; sourceUrl: string };
const FROM_COMMONS = commons as Record<string, Entry>;

const IMAGES: Record<string, RitualImage> = {};
for (const [id, entry] of Object.entries(FROM_COMMONS)) {
  const alt = ALT[id];
  if (!alt) continue;
  IMAGES[id] = { ...entry, alt, position: POSITION[id] ?? "50% 50%" };
}

export function ritualImage(slug: string): RitualImage | undefined {
  return IMAGES[slug];
}

export function ritualGroupImage(group: string): RitualImage | undefined {
  return IMAGES[`g-${group}`];
}

export function allRitualImages(): [string, RitualImage][] {
  return Object.entries(IMAGES);
}
